### ISSUE TITLE
Question: Is it possible to create a dynamic editor for an array property?

### ISSUE THREAD

**Issue by sirockin** [node-red/node-red#1004]
I'd like to create a node which will carry out linear interpolation between for two or more pairs of XY values - eg similar to the 'range' node but with more than one line segment - with the xy values stored as node properties.

I could implement this crudely for example by allowing the user to enter the array, as a single JSON string but ideally, I'd like to display two rows of XY data by default, then allow the user to add more rows as necessary.

Is there any way that I could achieve this?

**Comment by knolleary** [comment]
Hi,
the node edit dialog can present whatever UI you want to create in it.

Are you asking if you can do 'complex' UIs for editing nodes, or more specifically how you might achieve the effect you're after?

Either way, best place for this is the mailing list (link at bottom of nodered.org) as we try to keep this issue list to bugs etc rather than general support questions.

Nick
