### ISSUE TITLE
MQTT payload selection enhancement

### ISSUE THREAD

**Issue by smadds** [node-red/node-red#1082]
Would it be possible to enhance the MQTT publish connector to select a part of the payload rather than the whole? I see this functionality in other nodes and it would save having to add an additional node each time to rewrite the payload.

**Comment by knolleary** [comment]
Hi,

for feature requests/discussions, please can you use the mailing list - link from bottom of nodered.org

We try to keep the this issue like for real bugs or planned features.

Thanks,
Nick

**Comment by smadds** [comment]
sure - and apologies. I had misunderstood the tickets marked enhancement

**Comment by knolleary** [comment]
The vast majority of nodes operate on `payload` by convention. Some of the core nodes do let you operate on other properties, but that is by design to avoid having to resort to the Function node - such as the `Change` and `Switch` nodes.

So on balance, I don't think this is a change we'd make to the mqtt and (to be consistent) all other output nodes.
