### ISSUE TITLE
MQTT - Birth / Subscribe

### ISSUE THREAD

**Issue by brendonparker** [node-red/node-red#1089]
I'm want to use the birth message/topic feature on the mqtt node to request state once the mqtt connection is established (or re-established). So I have a input mqtt node that subscribes to a separate topic that the state will come in on. However, it seems that most of the time I don't receive that message. 

I believe it is a timing issue since the subscription wire-up and the publish are happening very close to each other upon re-connect, perhaps the subscription isn't quite established yet?

To test, I wrapped the publish of the birthMessage in a `setTimeout` and that seemed to give me reliable results.

So a few questions:
1) Does this birth topic pattern make sense for connection/re-connection events?
2) Does that `setTimeout` hack make sense?
3) Should I open a pull request for it?

**Comment by knolleary** [comment]
Hi,

so have you got another application subscribed to the birth topic set to reply with the current state or is that part of the same node-red application?

1. Rather than request/response, an alternative is to publish the state with the retain flag set. Then whenever the subscriber reconnects it will re-receive the most recent retained message on the topic. That removes the need to do any request/response.

2. it is a hack. Generally the purpose of the birth message is to be the first message published. If you add an artificial delay it would be possible for an MQTT Out node to get a publish out first. Then there's the question of how long a timeout is needed. You have found something that works for you. We know some users have flows that can take a few seconds to fully deploy.

3. I'm not sure this is something we'd want to change.

**Comment by brendonparker** [comment]
It is another application subscribed to the birth topic that replies with the current state (using the get topic with AWS IOT for shadow state).

I'll give the retain flag a shot and see if that fixes my problem. Will update this thread if it works.

Understood - thanks for your patience. Mqtt noob here.

**Comment by brendonparker** [comment]
Err - didn't work for me, but looks to be a gap with AWS IoT mqtt.
From [documentation](http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html) *emphasis added*
> The MQTT specification provides a provision for the publisher to request that the broker retain the last message sent to a topic and send it to all future topic subscribers. AWS IoT does not support retained messages. **If a request is made to retain messages, the connection is disconnected**.

Thanks for schooling me on the retain flag - that is the feature I want. This issue can be closed.

**Comment by knolleary** [comment]
If you add a Status node you can get events when an MQTT node's status changes. If you experiment with that, you should be able to trigger a publish after a short delay.

**Comment by brendonparker** [comment]
Excellent - that'll work. Thanks for schooling me twice ;)
