### ISSUE TITLE
Deploy failed: {"error":"unexpected_error"}

### ISSUE THREAD

**Issue by Ahmed-Talha** [node-red/node-red#1129]
My node-red flows were working fine, I was using them with IBM Bluemix App, then suddenly I am seeing this error while deploying even minor changes. "Deploy failed: {"error":"unexpected_error"}"

On debug section, I am seeing error saving flows: undefined.

I have checked, there are no undefined variables. Also the last saved copy of my flow is working fine. I can verify it by data.

**Comment by knolleary** [comment]
Hi

please can you have a look at the logs of your app on Bluemix when this error occurs? That should help us understand what is happening.

1. log into Bluemix
2. go to your applications dashboard page
3. select the logs page from the left-hand list

**Comment by Ahmed-Talha** [comment]
I got it, I mistakenly deleted the nodered database created in the cloudantDB service of my Bluemix which has all nodered setup and flow related documents.

I had to re-create the flows. DB was created again, its working fine now.

**Comment by knolleary** [comment]
Ok, thanks for the update. Glad to hear you're back up and running.

**Comment by Mouradak** [comment]
Hey. Could you please detail how you fixed this issue? 
I ran into it today and I am unable to reset the 'nodered' DB.

I know this happened a year ago, but I hope you still remember how to fix it.

**Comment by knolleary** [comment]
@Mouradak that error is a generic error message. The runtime logs should have captured much more detail. Rather than use a year-old closed issue, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack) for help.

Thanks!

**Comment by kletkeman** [comment]
Wow ... I've been suffering this error for weeks because I had the temerity to try to actually use the cloudant instance. Of course, the 10 msg/s limit (I was getting the errors that come from data arriving faster than that) made is useless and interestingly created the same issue as this thread is about. I recreated all the flows and everything worked again, but I decided to delete the cloudant instance since I was not using it ... or so I thought.

Is there a reason why the error message has to say absolutely nothing? If the logs have the answer, then node-red has it to and should just show it to us so we don't suffer for weeks with unexplainable issues ...
