### ISSUE TITLE
Flow export Inconsistency with API

### ISSUE THREAD

**Issue by SalehAly** [node-red/node-red#1149]
Hey All,

I have recently been using the export function in the UI of node-red while also using the HTTP API, 
I noticed that the JSON format of the flow export is different than requesting the same flow via REST.

Moreover, one cant not use an exported flow from the UI in JSON and POST it to another node-red instance because it expects the REST format.

Is there a specific reason of why their representation are different?

First Representation
```js
 [
  {
    "id": "e251ec3c.9a5c6",
    "type": "tab",
    "label": "Flow 2"
  },
  {
    "id": "a9aef78e.f25878",
    "type": "inject",
    "z": "e251ec3c.9a5c6",
    "name": "",
    "topic": "",
    "payload": "",
    "payloadType": "date",
    "repeat": "",
    "crontab": "",
    "once": false,
    "x": 114.5,
    "y": 253,
    "wires": [
      [
        "4ec97390.2daf9c"
      ]
    ]
  },
  {
    "id": "4ec97390.2daf9c",
    "type": "debug",
    "z": "e251ec3c.9a5c6",
    "name": "",
    "active": true,
    "console": "false",
    "complete": "false",
    "x": 272.5,
    "y": 218,
    "wires": [
      
    ]
  }
]
 ```

The Second representation

```js {
  "id": "e251ec3c.9a5c6",
  "label": "Flow 2",
  "nodes": [
    {
      "id": "a9aef78e.f25878",
      "type": "inject",
      "z": "e251ec3c.9a5c6",
      "name": "",
      "topic": "",
      "payload": "",
      "payloadType": "date",
      "repeat": "",
      "crontab": "",
      "once": false,
      "x": 114.5,
      "y": 253,
      "wires": [
        [
          "4ec97390.2daf9c"
        ]
      ]
    },
    {
      "id": "4ec97390.2daf9c",
      "type": "debug",
      "z": "e251ec3c.9a5c6",
      "name": "",
      "active": true,
      "console": "false",
      "complete": "false",
      "x": 272.5,
      "y": 218,
      "wires": [
        
      ]
    }
  ]
}```

**Comment by knolleary** [comment]
Hi - this is a limitation of the current flow api that needs some rethinking and reworking. The individual flow api needed a representation that encapsulated a single flow. But changing the main `/flows` format which has existed since the very start was not something we could undertake lightly - too many things depend on it.

This leaves us in the current state caught between the two - this is one of the reasons we've not widely publicised the individual flow api; it exists and can be used but isn't the most useable api.

The design of the new flow format, and some of the thinking behind it, is here: https://github.com/node-red/node-red/wiki/Design%3A-Flow-file-format-v2

We'll revisit this api at some point - have captured a task on the whiteboard for it: https://trello.com/c/pmwMcnFk/86-tidy-up-flow-api
