### ISSUE TITLE
Failing to re-install nodes on Bluemix

### ISSUE THREAD

**Issue by hardillb** [node-red/node-red#1187]
An Issue to track why Node-RED is failing to install some nodes installed via the "Manage Pallet" function when Bluemix restarts/restages instances.

While debuging this I noticed that the callback for the process has the arguments miss named 
https://github.com/node-red/node-red/blob/0a96259ddfacb10713d1419c155b40123dc54100/red/runtime/nodes/registry/installer.js#L95

The [doc](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) says then should be `err,stdout,stderr` not `err,stdin,stdout`

It might be worth logging the stderr/stdout for npm in the case of a failure (or at least making it optional in the settings)

**Comment by knolleary** [comment]
I think these issues have now been resolved with the latest version of the Node-RED boilerplate.

The main issue was that the `~/.node-red` directory didn't exist as we don't use the `localfilesystem` storage plugin that would otherwise have created it.

We invoke `npm` with the current working directory set to `~/.node-red`. That caused the ENOENT error - we mistakenly thought it meant `npm` didn't exist, but in fact it was the directory we were trying to run the command in.
