### ISSUE TITLE
NodeRed not reporting the messages in the debug column after the pricing plan upgrade

### ISSUE THREAD

**Issue by chouc** [node-red/node-red#1192]
The NodeRed is not reporting the messages in the debug column after I upgrade from the WIoTP Lite Plan to the WIoTP Standard Plan.

The app and NodeRed are both operating just fine but I don't see the messages in the debug column.

![nodered](https://cloud.githubusercontent.com/assets/26091683/23806930/7adf076a-0578-11e7-8441-d09026016e7e.jpg)

**Comment by knolleary** [comment]
Hi,

I assume this means you are running on IBM Bluemix? You don't say so, but given you mention WIoTP I can only guess that is the case.

Try accessing your instance use https rather than http. That normally sorts out an underlying websocket issue we get with Bluemix that disrupts the connection.

Also, please note the warning shown in the screenshot. You are not running on a support version of node.js. Please edit your application's `package.json` file to change the `engines` entry to say `4.x` rather than `0.10` or `0.12`.

If you continue have issues, please raise them on the Node-RED Mailing List (link at bottom of nodered.org). This issue list is for the core of node-red and not for support on particular platforms.

Many thanks.
