### ISSUE TITLE
URL property of HTTP node 

### ISSUE THREAD

**Issue by machadotiago** [node-red/node-red#1218]
When I configure the HTTP node with the URL param as "test" like this:

![capture](https://cloud.githubusercontent.com/assets/3775353/24632770/d8a6f0d4-189b-11e7-9677-17129a256d25.PNG)

and click on "DONE", the node shows that the URL configured is "/test" (the slash is added automatically) 

![capture2](https://cloud.githubusercontent.com/assets/3775353/24632788/efb21204-189b-11e7-8260-8f68811a2410.PNG)

But if I try to access the specified URL (127.0.0.1:1880/test) it doesn't work

![capture3](https://cloud.githubusercontent.com/assets/3775353/24632983/9bee39f8-189c-11e7-813f-45318e6fb28e.PNG)

It only works if I open the HTTP node configuration and set URL to "/test"
Shouldn't the HTTP node add the slash not only to the view but also to the parameter itself

BTW:
NR Version is: 0.16.2
Node version is: 4.4.4

**Comment by knolleary** [comment]
Hi, as per the docs of the HTTP In node, you must end your flow with an HTTP Response node in order to send a response back to the browser.

See this cookbook recipe: http://cookbook.nodered.org/http/create-an-http-endpoint.html

Please note, for general questions or 'how do i' type things, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

Thanks!

**Comment by machadotiago** [comment]
Oh ! I think you misunderstood what I mean. I wasn't talking about a missing HTTP response. I was talking about the **slash** added to the URL parameter only in the view window and not to the parameter itself. The flow that I printed above was just an example (which can also be used to demonstrate the problem because in that case you won't see any message in that debug node, even if you access the configured URL)

**Comment by knolleary** [comment]
Ah sorry - I see what you mean. Will take a look at what our expected behaviour is - all of our examples use a leading slash.

**Comment by knolleary** [comment]
Fixed in 0.17 branch - will be in the next release.

We now prepend the url with a `/` if it needs one.
