### ISSUE TITLE
oneditsave seems to only run once

### ISSUE THREAD

**Issue by troywweber7** [node-red/node-red#1225]
If I have a config input of `aNumber`, when you access the config object, it is of course a string immediately. personally, I don't like the idea of always having to use `parseInt()` to change it to a number, so I thought I could use the `oneditsave` function like so

```
...
oneditsave : function() { this.aNumber = parseInt(this.aNumber); }
...
```

I've noticed it works on the very first save/deployment, but if you change the number, then on future deployments, it is a string again. This seems to indicate that the oneditsave event is not running every time you save that node. Is that intentional? Is a "once" event being used instead of perhaps an "on" event?

**Comment by knolleary** [comment]
Hi,

When `oneditsave` is called, the properties of `this` have not yet been updated from the edit form. So your line `this.aNumber = parseInt(this.aNumber)` is not using the new value from the form.

Assuming you have an `<input>` with an id `node-input-aNumber`, you should do:

    this.aNumber = parseInt($("#node-input-aNumber").val());

By which I mean you should grab the new value from the edit form yourself, convert it and assign it.

If you have any general questions we prefer to handle them on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole node-red user community can help answer the questions, rather than rely on the core dev team.

Thanks!
