### ISSUE TITLE
How can a node get the name of the flow it is in?

### ISSUE THREAD

**Issue by tchristian32** [node-red/node-red#1237]
I want to be able to get the name of the flow so that I can add that to the output that I am producing.  Is it possible to get the name of the flow?  Or do I have to add a flow name textbox to the node and have them add the name in there?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. Please note we prefer to handle this sort of thing (general how-to questions) on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

A node knows the id of the flow it is on, but nothing more than that - `this.z` contains that information. We don't expose any api's to the node to find out any more details about the flow from that id.

Thanks!
