### ISSUE TITLE
See node information/output in modal overlay?

### ISSUE THREAD

**Issue by brylie** [node-red/node-red#1245]
I see that it is possible to show node configuration in the Info tab and some node output in the debugging tab or even in a separate browser tab. In some cases, for example a dynamic chart, it would be nice to **quickly inspect the node state** through a graphical widget that would appear near the node. 

Are there any examples of viewing the state or output of a node in a modal overlay?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle discussions on possible features on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack).

That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
