### ISSUE TITLE
How to create new node, based on C DLL library?

### ISSUE THREAD

**Issue by Vladyslav93** [node-red/node-red#1247]
Hello. I am new in node-red, I already know "What is node-red" and "How to work". The next step creates one more node, which will be based on the C DLL library(I have also .exe application, which working with this library...but I wanna use NODE-RED)). If it possible? Because I can´t find information on the internet, maybe it´s unreal?!

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
Just to answer your immediate question, nodes are node.js modules. If you have a C DLL/exe, you'll need to figure out how to wrap it up as a node.js module. It is possible to wrap C code in a node.js module, but isn't something we can help with - there are lots of guides online for doing that sort of thing.

For an exe, you could look at using the [child_process](https://nodejs.org/api/child_process.html) module to spawn it and interact via stdin/out - see also the `exec` node for doing that sort of thing.

**Comment by Baael** [comment]
There is nice article about using DLL's

https://nodeaddons.com/calling-native-c-dlls-from-a-node-js-web-app/
https://nodejs.org/api/addons.html

Then just connect your DLL behaviour with nodejs node events following
guidelines.

Wojciech Zieliński zielinskiwojciech@gmail.com gg#3062261 / tel. 0 694 434
073

2017-05-03 11:56 GMT+02:00 knolleary <notifications@github.com>:

**Comment by Vladyslav93** [comment]
@Baael It is not me closed the topic. Thank you for the links, it´s really important for me. Thanks
