### ISSUE TITLE
Timestamp in file name

### ISSUE THREAD

**Issue by Kartheek1512** [node-red/node-red#1252]
Hi, I want to create a file with name "example mmddyyyy hh:mm:ss.csv" every 5 mins with data from msg.payload in it. So, "example" remains and every 5 mins, the timestamp changes creating a new file. As of now, I am using the "file' node which which I cannot change the file name. Can anyone help if they already achieved this.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
but - check the Info panel for the file node - you can set the filename by including a `msg.filename` property
