### ISSUE TITLE
Store flow state permanently

### ISSUE THREAD

**Issue by MaksymMPanchyshyn** [node-red/node-red#1259]
Hi everyone!
  I'm using node-RED to design asynchronous chain of tasks which may take a lot of time. And I need an ability to store flow state permanently for those moments when server shutdown and restore that flow state on server startup.
  Let's say I have 4 asynchronous tasks in my chain, each of this task depends on previous, and what I need is to resume tasks execution from that task on which server restarts. 

Is some sort of such feature planned?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of question on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
