### ISSUE TITLE
pretty-print JSON

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1261]
would it be possible to add a tick-box on the JSON converter node to make it produce formatted JSON on object->stringify conversion, please?
This would make it possible to write "readable" JSON to a file.

Or is there another way to get pretty JSON out (like the option when you export nodes from a flow) ?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle feature requests/suggestions on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack). That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
In this instance, I can see the value here, so will reopen and add to the backlog.

But please use our preferred channels in the future.

Thanks!

**Comment by dceejay** [comment]
if this is done should the indent be (yet another) option/variable or just fix it ?

**Comment by knolleary** [comment]
Add to 0.17 branch - will be in next release.

**Comment by andysc** [comment]
just fix it - it’s either “ugly” or “pretty” - keep it simple

**Comment by andysc** [comment]
thanks :)

**Comment by andysc** [comment]
thanks :)
