### ISSUE TITLE
http input node connection refused

### ISSUE THREAD

**Issue by philbowles** [node-red/node-red#1264]
v0.15.3

I have an http input node running on raspberry pi (192.168.1.4:1880) serving up http updates to all my esp8266 devices. Yesterday it was working fine. This morning I had a power outage. After coming back up, Every esp8266 device is getting "connection refused". The NODE-RED debug log shows that nothing is being accepted by the input node (makes sense...!). If I enter the url directly in the browser on a PC , I get the expected response, and fiddler confirms that everything is as I would predict. This tends to rule out a firewall issue on the pi...as the main ui is accessible.

This is where it gets odd: When I select the flow that runs the http input node, and select debug messages for "current flow" I'm still seeing debug messages from my other flow (I have only two).

Adding the two up, it looks like my "updater" flow isn't running. 

The summary  is: NODE-RED is definitely listening on   192.168.1.4:1880. My input node listens to "/update/truc"
a recent debug log from my ESP code:

runUpdate: http://192.168.1.4:1880/update/truc?v=3_5_1
trucPublish: updating payload=now
[httpUpdate] HTTP error: connection refused
runUpdate HTTP_UPDATE_FAILD Error (-1): HTTP error: connection refused

And NODE-RED debug log for the current "failing" flow is showing message produced by the only other flow.

![capture](https://cloud.githubusercontent.com/assets/27769598/26352887/11acbadc-3fbe-11e7-8823-458e6be8c66a.PNG)

All of the code worked fine before the power outage and I can't see any other "odd" messages anywhere. - any ideas anyone?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team - particularly as this is likely to be some environmental issue rather than a bug with node-red itself.

Thanks!

**Comment by philbowles** [comment]
Thanks for the "heads-up". I'm pretty new to all of this (including those other forums (fora?)). FYI I just upgraded to v0.16 and I'm getting the same problem.

PS great job on the pubsubclient library!

**Comment by knolleary** [comment]
From the mailing list, it sounds like you've resolved this issue.
