### ISSUE TITLE
Make mqtt node to send acknowledgement if message fails to be received

### ISSUE THREAD

**Issue by ghugan** [node-red/node-red#1283]
May i know how do i make mqtt node to receive acknowledgement if the message fails to be delivered due to network failure.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

For your specific question, that is not something we currently expose or make particularly easy to handle.

Thanks!

**Comment by dceejay** [comment]
though the status node will indicate if it detects the link to the broker is broken. (but not on an individual message)

**Comment by knolleary** [comment]
I'm going to close this issue here. Please follow up on the mailing list/slack channel as I describe above if you'd like to discuss further
