### ISSUE TITLE
multiple device sending

### ISSUE THREAD

**Issue by farahgara17** [node-red/node-red#1292]
Hello
I'm working on a projet where i have to get information from multiple device.
I use IBM bluemix and the service IoT platform to register devices.
When i execute my process with one message . it's okey.
But when i send multiple message from multiple devices in 1s, node red crashed.
Can' I multiply the flow when i get informations at the same time ?
thank you

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
