### ISSUE TITLE
Mysql not working.

### ISSUE THREAD

**Issue by hemangjoshi37a** [node-red/node-red#1306]
I get this error in my debug window : "Error: connect ECONNREFUSED 192.168.0.101:3306"
Please help me.
Thank you.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
When you do contact the mailing list/slack/stack overflow, you will need to provide more information to get any help.

**Comment by hemangjoshi37a** [comment]
I think github has just best UI for a forum, it's like apple of all the forums. But as you suggested I will try it on stackoverflow. And thanks for your suggestion man.....
