### ISSUE TITLE
UI and HTTP nodes on different port numbers.

### ISSUE THREAD

**Issue by ProgramErgoSum** [node-red/node-red#1322]
Hi,
I would like to maintain two different port numbers - one for UI and one for HTTP end-points. Can this be done? If so, how?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

To address your question briefly, I've never tried to do so, but you could try following our (admittedly-short) guide to [embedding Node-RED in your own app](https://nodered.org/docs/embedding) and mount `RED.httpAdmin` and `RED.httpNode` express apps on different http servers. I don't know if that will work - you may get into issues with websockets as assumptions are made that both admin and node sides are attached to the same server.

In the future we plan to separate the editor and runtime to allow them to be run independently - that would be what you'd use for this. 

Thanks!

**Comment by rcarmo** [comment]
I'd like to know if this is still on the roadmap at all, since I've come across a number of scenarios where it is a hard requirement.

**Comment by knolleary** [comment]
Hi @rcarmo - this issue is closed. It is not on a roadmap.

But as I describe in my response above, if you embed Node-RED in your own node.js app then you can mount the admin and node endpoints on different servers yourself.

**Comment by rcarmo** [comment]
Yes, I've seen the example (which, BTW, only uses a single port). I'm wondering if setting up two distinct servers would actually work consistently, though.

**Comment by osos** [comment]
What I have just done is to setup a reverseproxy to forward http(s) requests to specific path of nodered.

On my raspberry pi 3 I have setup tinyproxy - only 2 mb in memory footprint - which is very easy to configure for reverseproxy for this purpose.
