### ISSUE TITLE
Flow stops due to exception in http request node

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red#1344]
Dear,

some time ago I created pull request [1176](https://github.com/node-red/node-red/pull/1176).  In short: always ask NodeJs to return Buffers, to avoid unnecessary buffer->string->buffer conversions (bad performance).  At the end all buffers in the array are appended to a single buffer.

However sometimes my flow is stopped by following exception:

![image](https://user-images.githubusercontent.com/14224149/28257606-6f0ea3d2-6acc-11e7-8292-da2c6bb3c447.png)

Seems when the client (device) stops the connection abruptly, NodeJs ends the connection with an error string (instead of an array of Buffers).  So we arrive in `res.on('end',function() {` :

![image](https://user-images.githubusercontent.com/14224149/28257683-e4d7bc16-6acc-11e7-9307-1a860db337a9.png)

It could be solved like this (adding code in the red rectangles), but perhaps you have a better solution:

![image](https://user-images.githubusercontent.com/14224149/28257747-523392b2-6acd-11e7-81d8-87ce490ebb5f.png)

Kind regards,
Bart

**Comment by knolleary** [comment]
Hi @bartbutenaers, thanks for raising this.

The proper fix is subtly different. The reason `msg.payload` is a string at this point is because the `req.on('error'` handler has already been called. That handler sets `msg.payload` to the error string and logs the error. In that scenario, when the `res.on('end'` handler is called, we should not send on another message.

Fix incoming - will be available in 0.17.5 soon.
