### ISSUE TITLE
http request node should enable options for POST, PUT, PATCH request body

### ISSUE THREAD

**Issue by wnmills3** [node-red/node-red#1355]
It seems the msg.payload is the only choice for the request body of the http request node. It would be nice if we were able to send the entire msg so we could consider adding other fields to it when calling a REST service.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to discuss things on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack)in the first instance, rather than raise an issue.

Nothing stopping you from setting `msg.payload` to be an object with whatever fields you want to send. There's no pressing reason to expose an 'entire message' option.

Thanks!

**Comment by wnmills3** [comment]
Thanks -- I tried setting msg.payload=msg.toString(); and that didn't work but I understand what you've suggested (e.g., being selective about which fields to include). Thanks.

**Comment by knolleary** [comment]
The intended behaviour is you set `msg.payload` to the body of the request. More often than not, the complete msg will include properties you don't want going near the request. I don't think there's anything more to consider here. Please reopen if you think there's more to address.
