### ISSUE TITLE
Use node extract on a web page where authentication is needed

### ISSUE THREAD

**Issue by Pikron** [node-red/node-red#1368]
Hi everyone,
I'd like to use node-red in order to extract information from a website. Kinda simple, but the difficulty for me is that you have to login on this website if you want an access to the useful information. 
Basically, when I want to send a http request to the web page, I'm redirected in the  https login page.
There is the problem, I don't know how to tell node-red to use my login informations. 
I tried to understand how the option "enable secure (ssl/tls) connection" of the http request node works but I'm kinda lost with that.
Any idea ?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
