### ISSUE TITLE
Keep getting "Error: two instances of WebSocketServer cannot listen on the same http server path"

### ISSUE THREAD

**Issue by kahveci** [node-red/node-red#1374]
After playing websocket node for some time, I started getting an error "_Error: two instances of WebSocketServer cannot listen on the same http server path_". 

That's absolutely fine! I most likely made a mistake during my tests. So, I decided to delete related nodes and even all flows. The problem is that I still keep getting exactly the same error message although there is no such websocket node.

Is there any sort of caching or something? Where does that error come from?

Node-RED version: **0.17.5**

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

In this instance, my guess is you haven't deleted the WebSocket configuration nodes. Open the config nodes sidebar from the menu and see if you have any websocket config nodes listed - dbl click and delete.

Thanks!
