### ISSUE TITLE
No debug output to console

### ISSUE THREAD

**Issue by patricktokeeffe** [node-red/node-red#1380]
Using nodered 0.15.3 on Raspbian Jessie with kernel 4.9.46-v7

I observe despite changing the debug node output to "debug tab and console", the browser console never receives debug messages. Neither does a function node containing `node.error("ERROR"); node.log("LOG")` work: only the "ERROR" message is displayed in the debug tab.

I get this problem using Chromium 60.0.3112.78 on RPi3 running Ubuntu Mate, and with Chromium 56 & Firefox 43.0.1 on Windows 7.

**Comment by hardillb** [comment]
Enabling console output means to output to the console where Node-RED is running on Raspberry Pi not the browser console.

Depending on how you started Node-RED will depend where this ends up, if you started it manually with the `node-red` command then the log will be in the console where you started it. If you are running Node-RED as a  service then the output will be in the log, you can view the log with the `node-red-log` command.

Also as mentioned in the Contribution guide, basic usage questions should be asked in the Slack team or on the Google Group mailing list, both of these are linked to from the Node-RED home page, rather than raising issues.

**Comment by dceejay** [comment]
The messages go to the system console not the browser console

**Comment by patricktokeeffe** [comment]
Oops, I had to assume it was the browser console because I always encounter Node-RED as a service.

**Comment by knolleary** [comment]
To be fair, console is an ambiguous label to use - we should improve that.
