### ISSUE TITLE
Node-red fills syslog with error close messages

### ISSUE THREAD

**Issue by mrohner** [node-red/node-red#1381]
Get hundreds of error messges filling the syslog. What should I do?

Console:
---------
Starting as a systemd service.
Started Node-RED graphical event wiring tool..
31 Aug 11:39:24 - [info]
Welcome to Node-RED
===================
31 Aug 11:39:24 - [info] Node-RED version: v0.17.2
31 Aug 11:39:24 - [info] Node.js  version: v6.11.2
31 Aug 11:39:24 - [info] Linux 3.4.113-sun8i arm LE
31 Aug 11:39:26 - [info] Loading palette nodes
31 Aug 11:39:38 - [info] Dashboard up and running
31 Aug 11:39:43 - [info] Dashboard version 2.4.1 started at /ui
31 Aug 11:39:45 - [warn] ------------------------------------------------------
31 Aug 11:39:45 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
31 Aug 11:39:45 - [warn] ------------------------------------------------------
31 Aug 11:39:45 - [info] Settings file  : /home/pi/.node-red/settings.js
31 Aug 11:39:45 - [info] User directory : /home/pi/.node-red
31 Aug 11:39:45 - [info] Flows file     : /home/pi/.node-red/flows_mosquitto.json
31 Aug 11:39:46 - [info] Server now running at http://127.0.0.1:1880/
31 Aug 11:39:46 - [info] Starting flows
31 Aug 11:39:49 - [info] Started flows
error
close
31 Aug 11:39:49 - [info] [mqtt-broker:8e79b041.968cc] Connected to broker: mqtt://192.168.178.59:8                                   883
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close
error
close

Syslog:
-------
![image](https://user-images.githubusercontent.com/15965653/29917611-c67222ae-8e42-11e7-8d2e-d35194c2c7ac.png)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

You'll need to provide some more information about what you're doing. There's nothing in node-red that will output those sorts of messages. It appears you have something that is doing `console.log` rather than using node-red's own logging system.


Thanks!

**Comment by mrohner** [comment]
Issue was with "blynk-websockets-out-write" node. I had to restore an older DB. Now Node-Red its working again

**Comment by dceejay** [comment]
Did you report that error to the author of the node ? Thanks.
