### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by LaFrish** [node-red/node-red#1384]
The [website](https://nodered.org/) not working on chrome. I was told it works in explorer.

**Comment by knolleary** [comment]
Hi @LaFrish.

Please can you provide more details? What isn't working for you? The website is working fine across all major browsers for me here.

In general, this sort of project level question is best suited on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack). That way the whole Node-RED user community can help, rather than rely on the core development team. This issue tracker is for code issues with node-red itself.

Thanks!

**Comment by knolleary** [comment]
Hi @LaFrish - any updates on this? Given the website is working fine for us and we've not had any other reports of issues, I'm going to close this issue.

But please do let us know if you're still having a problem and we can help you figure it out.
