### ISSUE TITLE
Feature: allow a node's icon to be set dynamically

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#1385]
Issue to track discussion on https://trello.com/c/PkIhjRHx

**Comment by Kazuki-Nakanishi** [comment]
> As with other properties, the proposal is to allow that to be a Function that is called when the editor needs to determine the required icon.
> This allows a node to dynamically change its icon based on its configuration.

My understanding is that only the icon of the nodes with this change can be dynamically changed. Am I correct?

I came up with another option.
- If a user specifies an icon, set it to `node.icon`. 
- When retrieving an icon path:
  - if `node.icon` is defined, use the path.
  - otherwise, use `node._def.icon`.

I think this implementation allows any node to change the icon dynamically without modifying the existing nodes.  What do you think of this option?

> the node edit dialog will need updating to give space for the user to specify the icon. We don't have an agreed design for this yet. There are two possible options:

I prefer the second option, too because the number of sections should be as small as possible.

> the user should be able to enter the icon name directly, or pick from a list of available icons (need runtime api to expose the available icon names). Ideally a graphical picker could be created.

I prefer a graphical picker if an appropriate library exists.

> If a node uses an icon from a 3rd party module, when the node is exported how will that export identify what module provided the custom icon.

There are two topics that should be considered for this question.

- What data should be included in an exported flow data
The data format of node.icon should be `{module_name}/{icon_filename}` so that Node-RED can recognize which module contains the icon file.
e.g. `node-red/trigger.png`, `node-red-dashboard/ui_button.png`.

- How to express that an icon is unknown
Unlike the case of unknown node, it is hard to express which module contains the unknown icon on the workspace because of the small space.
To express the unknown icon:
  - show `node-error.png` icon on the top of the node.
  - surround the input field of icon in `node settings` section with red frame.

**Comment by knolleary** [comment]
> My understanding is that only the icon of the nodes with this change can be dynamically changed. Am I correct?

There are two separate parts here:

1. allowing a node to automatically change its icon based on its configuration
2. allow a user to specify a custom icon for any node

If a user specifies a custom icon it will override whatever icon configuration the node definition provides. If the user does not specify a custom icon, the node definition will be used - which can either be a static icon name (as-is today) or a Function to return an icon name based on the node's configuration.

> If a user specifies an icon, set it to `node.icon`.
> When retrieving an icon path:
>     - if `node.icon` is defined, use the path.
>     - otherwise, use `node._def.icon`.

Yes - that is how I see this working. The only outstanding question is whether `icon` is a safe name to use for the user-specified icon name. The risk is an existing node has already defined a property called `icon` which would clash here. I plan to use the Flow Library to build an index of all node properties used today so we can see if it clashes (this won't happen for a few days, so we can go with `node.icon` for now, but will need to check it before releasing).

> I prefer the second option, too because the number of sections should be as small as possible.

👍 

> I prefer a graphical picker if an appropriate library exists.

Me too - we can start with a select box or even text input to get going and add a graphical picker later.

>The data format of node.icon should be `{module_name}/{icon_filename}` so that Node-RED can recognize which module contains the icon file. e.g. node-red/trigger.png, node-red-dashboard/ui_button.png.

Yes, I think that's right. 

> Unlike the case of unknown node, it is hard to express which module contains the unknown icon on the workspace because of the small space.


If the user-specified node is unknown, it should show the icon from the node-definition. One small thing to be aware of: the HTTP request to get the icon has been written so that it always returns something; if it requests an icon that doesn't exist, it currently returns a default icon. That would need changing to return a 404 so the editor can then fall-back.

> show node-error.png icon on the top of the node.
> surround the input field of icon in node settings section with red frame.

👍

**Comment by Kazuki-Nakanishi** [comment]
> 1.allowing a node to automatically change its icon based on its configuration
> 2.allow a user to specify a custom icon for any node

Thank you very much for your explanation.
Although I mixed those two parts before, I could finally figure it out.

>  I plan to use the Flow Library to build an index of all node properties used today so we can see if it clashes

Sounds interesting! I look forward to hearing the result.


I will write a design note with covering these discussions, and will notify later. Thanks!

**Comment by Kazuki-Nakanishi** [comment]
With regard to "Node definition changes", it seems that a node can already change its icon dynamically.
It was implemented at `getNodeIcon` function in `utils.js`.
The following is a sample code for 20-inject.html. After modified, an icon of inject node dynamically changes when you change `Repeat` property.
```
icon: function() {
    if (!this.repeat && !this.crontab) {
        return "inject.png";
    } else {
        return "timer.png";
    }
},
```
Although I looked into source code that is related to this feature, I found nothing that should be modified.
So I think that "Node definition changes" is already implemented. Is my understanding correct?

---
With regard to "User-defined icons", I think that some users may want to use their own icon files.
Please let me discuss how to realize it.

First of all, there are three ideas that a user installs and/or specifies icon files on Node-RED.
1. Install the existing contributed nodes that contain icon files
1. Specify a URL of an icon file
1. Add icon files to a project [(Projects design memo)](https://github.com/node-red/node-red/wiki/Design%3A-Projects)

Conditions                             | 1             | 2             | 3
-------------------------------------- | ------------- | ------------- | ------------- 
Show icons under offline environment   |   &#10004;    |   &#10006;    | &#10004;
Specify icon files created by a user   |   &#10006;    |   &#10004;    | &#10004;
Share icon files with only flow.json   |   &#10006;    |   &#10004;    | &#10006;

Comments for each idea:
1. Although this is good as a first step, this does not satisfy the use case that a user uses their own icon files.
2. Although this is very flexible, the necessity of internet connection may be unacceptable.
3. - With regard to "We don’t want to become a generic IDE." in the Projects design memo, are icon files acceptable?
   - Can a user share a project that contains icon files with other users (e.g. via a remote git repository)?
   - In the case that a user imports a flow that contains unknown icon files, the user cannot know where the icon files exist. Is this restriction acceptable as Node-RED shows a default icon of the node instead of a user-defined icon?


Although I considered another idea "Create an npm package that contains only icon files", the npm package that contains only resource files is not allowed. [(Acceptable Content)](https://www.npmjs.com/policies/open-source-terms#acceptable-content)


If idea 3 is acceptable, I think that starting at 1, then implementing 3 seems good.
What do you think of this idea?

**Comment by knolleary** [comment]
Which version of the file are you looking at?  That doesn't appear in any version I have... https://github.com/node-red/node-red/blob/ef53dca0628cca360795fe05cab91e146c8207fb/nodes/core/core/20-inject.html#L188

Will respond to the second part when I have a change to read it properly.

**Comment by Kazuki-Nakanishi** [comment]
Sorry to make you confuse.
The code I provided was just a sample code not an actual code on GitHub.

> 1. allowing a node to automatically change its icon based on its configuration

My understanding is that a node can automatically change its icon if the node developer defines a function for icon property like the above sample code.

Please let me take another example with a procedure.
1. Switch to 0.18 branch (another branch should be OK).
2. Install node-red-dashboard node.
3. Change `icon` definition of `ui_button.html` from "ui_button.png" to:
```
        icon: function() {
            if (this.name === "form") {
                return "ui_form.png";
            } else if (this.name === "join") {
                return "join.png";
            } else {
                return "ui_button.png";
            }
        },
```
4. Run a Node-RED.
5. Deploy a ui_button node on workspace.
6. Open edit dialog, set `form` to `Name` property, and click Done. Then the icon dynamically changes to `ui_form.png`.
7. Open edit dialog, set `join` to `Name` property, and click Done. Then the icon dynamically changes to `join.png`.

So I thought that the feature "Node definition changes" is already realized.
Is my understanding correct?

> Will respond to the second part when I have a change to read it properly.

Thank you!

**Comment by knolleary** [comment]
Hi - I have no memory of writing that code, but clearly I did.... well, that makes this easier then!

Will definitely get back to you on the other part of your question today.

**Comment by Kazuki-Nakanishi** [comment]
> Hi - I have no memory of writing that code, but clearly I did.... well, that makes this easier then!

Thanks for your confirmation.  Yes, it is somehow already implemented :)
And yes, I can use this code to implement `User-defined icons`.  I will modify the code to enable it to specify 3rd party icon path.

**Comment by knolleary** [comment]
Closing this issue as the feature is in the 0.18 branch
