### ISSUE TITLE
node-red Error saving flows: EROFS: 

### ISSUE THREAD

**Issue by Wolfgang777** [node-red/node-red#1388]
Hello,
suddenly comes the Failure on deploying:
"Error: EROFS: read-only file system, open '/home/root/.node-red/flows_iot2000.json' at Error (native)"
before it has worked for weeks good

Tahnk you

**Comment by hardillb** [comment]
Have you checked that the filesystem hasn't actually been remounted read-only due to corruption? It is normal for Linux to remount broken filesystems read-only to prevent further damage.

Also please check the [contribution](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) guide, questions should be asked on the Google Group or Slack as we like to keep issues for identified defects.

**Comment by nielsnl68** [comment]
Wolfgang are you using the neopixel node? I have seen that it would bring the filesystem to a hold (readonly)

**Comment by Wolfgang777** [comment]
this Problem apears since I have nodes with Console :"mount -a" and "umount -a"
to copy files to USB-Stick
I have tried to solve the Problem with reinstall of Yocto-Linux-Image but the Failure is still coming by deploying even if I delete the exec-Nodes
the filesystem /.node-red has 755 permission actually, and it can't be changed

Thanks a lot

**Comment by hardillb** [comment]
umount -a unmount ALL filesystems, this is not a good idea and probably should only be used as part of the system shutdown scripts.

This is not a Node-RED problem.

**Comment by Wolfgang777** [comment]
oh, thank you

**Comment by knolleary** [comment]
Closing as it isn't a NR issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
