### ISSUE TITLE
nodered demo suddenly not working

### ISSUE THREAD

**Issue by Danizu** [node-red/node-red#1400]
Hello, I've prepared demo that is basically the nodered coursera excersize and the noderes application was working properly on RaspberryPi and on Bluemix.
Running the app for a demo this morning, the app is not working and sensehat appears as disconnected.
I really don't understand the cause.
On Raspberry nodered I get the error: 
1)
"[wiot:connectionPool:getClient] [GatewayClient:unsubscribe] Client is not connected"
(and I'm not able to see which node is connected to this message)
and then 
2)
"Error stopping node: TypeError: Cannot read property 'unsubscribe' of undefined"
and this is related to Watson IOT Input node.

I had the some problem when I activated a rules on sensehat data but then removing the rule all worked again. But this time I have no rules active.
Any suggestion?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. There are better places to ask this question; this issue tracker is for development issues, not general support.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
