### ISSUE TITLE
cannot delete SQLITE

### ISSUE THREAD

**Issue by GuyPi3** [node-red/node-red#1407]
I copied flow with sqlite node ->reports: missing node
then I installed sqlite -> problem with the install, did not install sqlite
so I deleted the flow en hit deploy
I get an error: "imported unrecognized type:sqlitedb"
I cannot delete nodes in 'manage palette' or in 'configuration nodes'
How can I solve this please?

Guy

![error2](https://user-images.githubusercontent.com/32207116/30762030-a41b4a1e-9fe0-11e7-8e82-4d03122facc9.png)

![error](https://user-images.githubusercontent.com/32207116/30761921-5109d8fe-9fe0-11e7-8fe5-2594f36553af.png)

![error3](https://user-images.githubusercontent.com/32207116/30762047-beb929cc-9fe0-11e7-9f83-a40a9bb07f74.png)

![error4](https://user-images.githubusercontent.com/32207116/30762058-c39b3da4-9fe0-11e7-9476-44f8af528800.png)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle general support questions on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

You should also mention what version of node-red you are using.

When you double-click on the node in the configuration node sidebar can you check the browser javascript console for any errors and share them here. There must be something wrong there that needs fixing.

Without knowing what's preventing you from opening the unknown config node's edit dialog, the only alternative is to manually edit the relevant nodes out of your flow file. When node-red starts it logs the full path to the flow file it is using. Once you've identified that, open it in a text editor and search for references to `sqlitedb` and then to delete the surrounding object. Needless to say, make sure you backup your flow file first! Once you've edited it, restart node-red and see where you get to.


Thanks!

**Comment by GuyPi3** [comment]
Thanks very much, I got it working again!

Guy
