### ISSUE TITLE
Hang / Stall while Deploying - Cannot Deploy Flow with only Standard Nodes

### ISSUE THREAD

**Issue by MWals** [node-red/node-red#1409]
Dear Node Red Team,

i am Using this Flow in a Node Red instance in Bluemix:
[flow.zip](https://github.com/node-red/node-red/files/1327860/flow.zip)

I built the Flow Sequentially and everythin works fine if you just make changes to only one of the Template Nodes in the lower group at a time, which each contain around 1200 lines of JSON.

When i try to import the flow or make changes to more than one of the template nodes with many lines inside, deploying crashes and data is lost after refreshing the page. This issue caused us to loose a lot of time and work lately...

When opening the browser console, we can see the following error messages:
![errors](https://user-images.githubusercontent.com/11655219/30787736-d75aaad6-a18f-11e7-9bff-b2862e46b81f.PNG)
![errors](https://user-images.githubusercontent.com/11655219/30787795-9483cc54-a191-11e7-8eaa-fc9f85bc2999.PNG)

Bluemix does not give me any errors in the logs. I have been able to reproduce this error with current and slightly older versions of Chrome, Firefox and Safari browsers.

Please update the template node as it seems as node red is not able to handle template nodes with moderate amounts of data in it as well as multiple template nodes with some data in it.

Deploying the Flow works when i delete all of the template nodes containing the json data but one and then deploying. I then keep adding them one by one and deploying every time.

Thx in advance!!!

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

For general support questions we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

My guess is your flows are too big for the default API payload size node-red accepts - although I am unable to open the zip file you've attached to see for myself.
In which case, you'll need to add `apiMaxLength` to your `bluemix-settings.js` file and increase the limit to something big enough to accept your flows - https://github.com/node-red/node-red/blob/master/settings.js#L102

Thanks!
