### ISSUE TITLE
reverse proxying fails with default httpRoot

### ISSUE THREAD

**Issue by richlv** [node-red/node-red#1419]
if httpRoot is left undefined, it is supposed to be '/'.
when reverse-proxying (with apache) in such a config, several of the resources (images etc) are looked up under absolute path of '/red'.

if httpRoot is explicitly defined to, for example, '/nodered' and reverse proxying uses '/nodered' as well, all resources are properly referenced.

it would be expected that empty httpRoot would still use relative URL and allow all resources to be found.

**Comment by knolleary** [comment]
Hi,
I'm not clear from your description what problem you're reporting - what is failing?

I don't have a reverse proxy setup to hand to try this out, so any more specific details you can 
provide would be very helpful.

Are you running node-red directly or embedding it in your own node.js application?

If the former, then httpRoot will be explicitly set to `/` if it's otherwise undefined. In which case `httpAdminRoot` and `httpNodeRoot` will also be set to `/` (unless they are explicitly set themselves).

The editor resources live under `<httpAdminRoot>/red` - so if root is `/`, it will load resources from `/red`.

If root is `/nodered` then the resources will be loaded from `/nodered/red`.

**Comment by richlv** [comment]
i was able to reproduce that with a login form, but without it all works as expected. weird :)

closing now - sorry about the trouble. will reopen if i manage to make it happen again.

**Comment by Harishgopal** [comment]
Hello Nick,
I was running node-red for node red. when i tried integrating the world map in dashboard i m getting error like cannot get /red/worldmap in my dashboard.
Kindly help this out !!!
