### ISSUE TITLE
Websocket clients can never send data? How do you subscribe to a channel on a websocket?

### ISSUE THREAD

**Issue by andersea** [node-red/node-red#1421]
Hi. I don't see how you can ever send any data the way the node is designed if you only have a client connection.

As far as I am able to see the code that sends messages is this.

```javascript
    WebSocketListenerNode.prototype.reply = function(id,data) {
        var session = this._clients[id];
        if (session) {
            try {
                session.send(data);
            }
            catch(e) { // swallow any errors
            }
        }
    }
```
So you need a session object from _clients.

_clients is set here:

```javascript
        function handleConnection(/*socket*/socket) {
            var id = (1+Math.random()*4294967295).toString(16);
            if (node.isServer) { node._clients[id] = socket; node.emit('opened',Object.keys(node._clients).length); }
            socket.on('open',function() {
                if (!node.isServer) { node.emit('opened',''); }
            });
//...
```
node.isServer is a piece of regex
`node.isServer = !/^ws{1,2}:\/\//i.test(node.path);`

This returns false if you are a client connection.

Can you not send any messages if you are a client? What am I missing?

**Comment by knolleary** [comment]
Hi, 
It only uses the .reply function if the message came from another websocket node due to the check here:
https://github.com/node-red/node-red/blob/cb4f46decceaf39caf608838f1af01dcbbf5f51f/nodes/core/io/22-websocket.js#L250

In the case of a websocket outbound client, it will use the broadcast function which does have a code path for the `!node.isServer` case.

 https://github.com/node-red/node-red/blob/cb4f46decceaf39caf608838f1af01dcbbf5f51f/nodes/core/io/22-websocket.js#L171
