### ISSUE TITLE
Grove Pi with Node Red

### ISSUE THREAD

**Issue by sallen135** [node-red/node-red#1428]
I have been trying to set up GrovePi to be used with node-red, but am getting an error. I can download all of the files, but get a warning upon loading node-red in the terminal:

[grovepi] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

And the nodes for GrovePi are not shown. I can see in my Palette Manager that I have the grove pi contrib module installed but none of the nodes are activated (circle next to the node is not filled with a color.) Any ideas how to solve this? I have also installed node-grovepi as that was said to be a dependency.﻿
 Anything at all could be helpful. Thanks!

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

This issue tracker is for the core of Node-RED.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
