### ISSUE TITLE
Improve DELAY node for variable wait time

### ISSUE THREAD

**Issue by NicSil** [node-red/node-red#1429]
I came on an issue where many Hue bulbs seems have a problem to be managed at the exact same time: some don't receive the command but receive it if I introduce a short delay before sending the Hue command to this bulb.
Thus, the right solution is to add a delay node before each Hue node if there are many, with different wait time.
My suggestion is to improve the delay node to allow a random wait time between two values.
![image](https://user-images.githubusercontent.com/9283001/31310006-7c8d724a-ab90-11e7-86c9-0addfe93aab4.png)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

In this instance, the Delay node can already be set to Random delay which does exactly what you suggest.

Thanks!

**Comment by dceejay** [comment]
Hi,
not sure what version of Node-RED you are using but the delay node already offers this capability.
![image](https://user-images.githubusercontent.com/5375409/31310375-142abe2a-ab8f-11e7-9a5f-218e8126a17e.png)
