### ISSUE TITLE
multiple projects same instance

### ISSUE THREAD

**Issue by aryeharmon** [node-red/node-red#1440]
I'd like to have multiple projects running on the same node red instance. there is a plugin for this that no longer works. https://github.com/Negrero/node-red-contrib-multiproject and was wondering if there is a better way for me to do this.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
