### ISSUE TITLE
Add settings at runtime and one node

### ISSUE THREAD

**Issue by rudacs** [node-red/node-red#1459]
Guys,

Needing to get some doubts, because I'm creating some nodes.

The first is if there is a possibility that there is only one such item in the whole project?

Another thing is that I have a node type that receives information and it needs to automatically create nodes of the configuration type.
This is because the user does not create because he does not have all the necessary information. When I plug in the network, the node will detect it and create a configuration node so that the user can edit and use it on some other node (which I am also creating).

Would anyone have a solution?
Thank you.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by rudacs** [comment]
Many thanks for the super fast reply :)
I'll ask where you pointed.
