### ISSUE TITLE
Inject node is not found in node red v0.17.5

### ISSUE THREAD

**Issue by rskhatri** [node-red/node-red#1471]
Hi,
I have added node red in embedded project with cortex a8 based SOC.
Every thing is working fine but there is no inject node. I am not able to get inject node when draw a flow in node red work space.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
Just to add to my comment above, you'll need to provide a lot more information.

1. how have you added node-red to your project?
2. are there any relevant error messages on start-up?
3. what version of node.js are you using (this question (and others) were on the Issue Template you deleted whilst raising your issue...)

**Comment by rskhatri** [comment]
1. Added node red by yocto project. Used meta-nodejs-contrib for node red recipe.
2. No there are no error messages on start up.
3. node js version 7.10.0

Thanks !

**Comment by knolleary** [comment]
Do you have a link to the recipe you used? We don't provide anything specific for yocto ourselves, so we are not familiar with it. Please follow-up on the node-red mailing list as this is not a core issue with node-red. Thanks!

**Comment by rskhatri** [comment]
https://github.com/imyller/meta-nodejs-contrib/tree/master/recipes-extended/node-red

Thanks!

**Comment by knolleary** [comment]
Just to be clear, this isn't an issue we're going to look at on this issue list. Please follow up, with the relevant information, on the node-red mailing list.
