### ISSUE TITLE
node.send(msg), but not arriving in debug node

### ISSUE THREAD

**Issue by piejanssens** [node-red/node-red#1502]
The node in my flow is always updating its status, but not always ending up in my debug node.
Does this mean an exception is taking place? I have put the logging level to debug, but don't see anything special.

This is the code (from node-red-contrib-homekit):
```
    // emit message when value changes
    service.on('characteristic-change', function (info) {
      var msg = { payload: {}, hap: info}
      var key = info.characteristic.displayName.replace(/ /g, '')
      msg.payload[key] = info.newValue
      node.status({fill: 'yellow', shape: 'dot', text: key + ': ' + info.newValue})
      setTimeout(function () { node.status({}) }, 3000)
      node.send(msg)
    })
```
I made a screencap to make it easier to explain my problem. You will see the HomeKit node receive messages from the Home app. The code that processes this message is printed above, for some reason the message never reaches the output (the debug node). Then I press one of the test buttons I added sending the same messages and now it goes through.

https://youtu.be/pz9MPDSKJwo

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by piejanssens** [comment]
https://stackoverflow.com/questions/47642347/node-sendmsg-but-not-arriving-in-debug-node
