### ISSUE TITLE
send message payload then stop the flow for 5 second 

### ISSUE THREAD

**Issue by Akhilshines** [node-red/node-red#1519]
i am using proximity sensor in raspberry pi.it detects the object by PI-SRF node.when the distance become less than 30cm it say "you are in the circle". the issue is when the object in the circle it continuously shows the message.i need only one message in around 5 sec. simply i need a node or the function to direct once the message and stop for 5sec.

[{"id":"4071177c.6d66c8","type":"rpi-srf","z":"5a455de1.1eab64","name":"","topic":"SRF","pulse":".004","pins":"26,23","x":101,"y":214,"wires":[["313a5d4e.e43912"]]},{"id":"1b3c9a07.ccca46","type":"function","z":"5a455de1.1eab64","name":"","func":"\nif (msg.payload ===\"30\") {\n   return {payload:\"welcome have a nice day\"};\n} \nelse if(msg.payload ===\"28\")\n{\n   return {payload:\"welcome have a nice day\"}; \n}\n\n\n","outputs":1,"noerr":0,"x":435.00000762939453,"y":279.75000762939453,"wires":[["9b6bffe2.30b73"]]},{"id":"9b6bffe2.30b73","type":"play audio","z":"5a455de1.1eab64","name":"","voice":"0","x":621.75,"y":277.75,"wires":[]},{"id":"313a5d4e.e43912","type":"switch","z":"5a455de1.1eab64","name":"","property":"payload","propertyType":"msg","rules":[{"t":"lt","v":"30","vt":"num"},{"t":"gt","v":"30","vt":"num"}],"checkall":"false","outputs":2,"x":259.50000381469727,"y":286.00000762939453,"wires":[["1b3c9a07.ccca46"],[]]}]

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
Try the trigger node.
