### ISSUE TITLE
nodered.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by TheZoker** [node-red/node-red#1547]
### What are the steps to reproduce?
Start node red via `node-red-start` or via service

### What happens?
```
Starting as a systemd service.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
Started Node-RED graphical event wiring tool..
nodered.service: Main process exited, code=exited, status=127/n/a
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
Started Node-RED graphical event wiring tool..
nodered.service: Main process exited, code=exited, status=127/n/a
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
Started Node-RED graphical event wiring tool..
/usr/bin/env: „node-red-pi“: Datei oder Verzeichnis nicht gefunden
nodered.service: Main process exited, code=exited, status=127/n/a
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
Started Node-RED graphical event wiring tool..
nodered.service: Main process exited, code=exited, status=127/n/a
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool..
nodered.service: Start request repeated too quickly.
Failed to start Node-RED graphical event wiring tool..
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
```
### What do you expect to happen?
Start without issue
### Please tell us about your environment:

- [ ] Node-RED version: 0.17.5
- [ ] node.js version: 8.9.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Rasbian 4.9

The strange thing is, that when I run `node-red` within `/home/pi` it starts without any issue

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. We normally use this issue tracker with actual defects with node-red - not as a support channel for user issues.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

In this instance the error says (in German..) 'node-red-pi' File or Directory not found. So when you do follow up, some additional information will be needed:

 - How did you install node-red?
 - Does the command `node-red-pi` work when you run it manually?
 - What does the command `node-red-log` give you?


Thanks!

**Comment by knolleary** [comment]
Hi - as per my comment above, given the lack of further information, I'm going to close this issue. Please follow up on the mailing list or slack, with the extra information, if you're still hitting this.
