### ISSUE TITLE
Http Request node with a possibility to receive webhook. Is it possible to?

### ISSUE THREAD

**Issue by GermaN-st** [node-red/node-red#1556]
Hello.

We often use third-party api. For example, to create chat-bots using Node-RED.
We encounter the situation when, after sending a request, we need to receive not only the response of the service, but also that it will send the service to the webhook specified by us.
For example. We send a message to the user using the http request node. After that, the user can respond to the bot and in this case a message will come to our webhook. But since we only get an answer that we have successfully called a service and can not get what comes to webhook in the same node, we can not continue the full chain (flow). Thus, all calls to our web-based hook can be obtained only in another node http in. And our flow is interrupted.

Is it possible to implement a new node that can, in addition to calling the service, also wait for receiving a message on the web -hook and give in addition to the reply also the message received by Webhook ?

A similar implementation already exists in additional nodes for interaction with telegrams, for example.
But since you need to use a third party, you need a new node. Which can be a universal tool for the case when you need to call API and get more data that will come to webhook. I think a lot where it might be needed.

How do I imagine the implementation. The flow starts with the node http in which the data is received (our webhook), then we have a flow with some logic and there comes a time when we need to call api and in the same node get in addition a reply message that will come to webhook. In this case, if the node specifies that we need to get data from the webhook in addition to the service, then the first node does not receive a message so that the chain can continue.

As now it is possible to realize for example connectors to telegrams(very convenient):
![image](https://user-images.githubusercontent.com/30233260/34919646-8463ef22-f978-11e7-8852-74b41231a859.png)
It is seen that the conversation chain is not interrupted, but in the connector Telegram Sender we send a message to the user and there we are waiting for the answer, which can be processed further. In this case, after sending the message, we receive the answer in the same node, and not in the first one.

How to see the implementation of a new node:
![image](https://user-images.githubusercontent.com/30233260/34919765-6eb9e022-f979-11e7-8f7a-4308721e7508.png)

I would gladly have tried to implement it myself, but unfortunately I'm still very new to the Node.js

Tell me please, is it possible to implement this and will it be in your plans? Or maybe there is still some way to solve this case?
Thank you so much and sorry for my bad english. Node-RED  - very powerful tool!

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

We have no plans for such a node. One of the strengths of node-red is that anyone can create new nodes and publish them - it doesn't have to be done by the core team. If you send your idea to the mailing list you will reach a much larger audience and someone may want to help

Thanks!
