### ISSUE TITLE
Which technologies should I learn for customising Node-RED to embed with Node js application?

### ISSUE THREAD

**Issue by pradeep4sure** [node-red/node-red#1572]
Hi,

I want to do some changes to Node-RED embed with my Node js application. Please suggest me which technologies should I learn to do that.

Thanks

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. If you had read the guidelines you were presented with when you clicked the 'New Issue' button, you'd see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
