### ISSUE TITLE
Convert voltage to temperature (PT100)

### ISSUE THREAD

**Issue by foscamhomeiq** [node-red/node-red#1589]
I have a pt100 sensor which is connected to RTD transmitter with 0 to 5v output, temperature -50 to 300*c, input voltage 24v. I connected the temperature sensor with transmitter to Advantech WISE 4012E analog input and i get the values in node red as voltage. How to convert that voltage into temperatue and help me with the code.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
Maybe look at the scale node ? If the relationship is linear then that can re-scale one range of inputs to another.

**Comment by knolleary** [comment]
Closing this issue. Please follow up on the mailing list or slack for more help.
