### ISSUE TITLE
i18n for core nodes and nodesDir

### ISSUE THREAD

**Issue by SiBorya** [node-red/node-red#1604]
1. It seems that there is no way to create i18n for core nodes help text
2. If `nodesDir` or `userDir`/nodes is defined, the `locales` inside the node package(directory) will not be loaded

**Comment by HiroyasuNishiyama** [comment]
For item 1. you can put i18n help text at `nodes/core/<category>/locales/<locale>`.  But, creating `locales` directory under `<category>` leads some message lookup to be failed.  
I have proposed placing help file under `nodes/core/locales/<locale>/<category>` similar to message catalogs.

**Comment by Kroderia** [comment]
Item 1 I means those text inside tag `<script type="text/x-red" data-help-name="nodeNameHere">`.

**Comment by HiroyasuNishiyama** [comment]
Here is an example of Japanese info text for SWITCH node.  
Japanese help file is placed at `nodes/core/logic/locales/ja/10-switch.html`.

![switch-jp](https://user-images.githubusercontent.com/30289092/35914765-cbfd44e6-0c47-11e8-8e5e-505f2d09f679.png)

**Comment by Kroderia** [comment]
Thanks a lot.  
This really should be mentioned in wiki. [Design: i18n](https://github.com/node-red/node-red/wiki/Design:-i18n) only talks about the `message.json` about the core nodes, not the html with help text.

**Comment by joelguittet** [comment]
Hello,

Just want to pick this issue up! I have the same problem that point 2 in the first message.

Context: I have a linux embedded device with 2 rootfs partitions to manage the upgrade. Only one is active at a time. There is a data partition for permanent data.

My usage of node-red: I have set `userDir` to a sub-directory of the data partition (`/data/node-red`) + `nodesDir` to another sub-directory of the data partition to handle extra nodes installation managed with a system of plugins (`/data/plugins`).

Problem is the locales defined in the plugins are not loaded at all. If the plugin is moved to `/usr/lib/node` then this is properly working (but as describe above because the rootfs partitions can switch, this is not convenient for my usage, plugins need to remain in the data partition).

I may help on this topic (and propose a PR) but I'm not sure it's trivial and don't know really where to start exactly. @knolleary if you can point the right location (I ask you particularly because I don't want to propose something which doesn't fit the architecture or roadmap).

Regards
Joel

**Comment by AllanOricil** [comment]
I have the same issue. Described it in this slack thread
https://node-red.slack.com/archives/C024NDNRUSJ/p1725237526953619

**Comment by knolleary** [comment]
This was tidied up via https://github.com/node-red/node-red/pull/3676.

If `nodesDir` points to a directory with a `package.json`, it will treat it more like a regular module (and all the features that includes). If it cannot determine its a module, then it loads them as bare node files without locales etc.

The PR description covers the full details.
