### ISSUE TITLE
Any plan to goes with es6/babel?

### ISSUE THREAD

**Issue by Kroderia** [node-red/node-red#1606]
As title.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
Hi - sorry for the instant close, but the issue template you were shown is very clear that questions should be directed to the mailing list.

**Comment by knolleary** [comment]
Oh, and to answer you question. No, no plans to ever touch babel.
