### ISSUE TITLE
[node-red-node-xmpp/xmpp] 'xmpp-server' already registered by module node-red

### ISSUE THREAD

**Issue by drJeckyll** [node-red/node-red#1608]
After upgrade to 0.18.1 I'm getting this message:
[node-red-node-xmpp/xmpp] 'xmpp-server' already registered by module node-red

Reinstalling node-red-node-xmpp did not solve the problem.

How can I resolve this issue?

**Comment by knolleary** [comment]
It appears you have two copies of node-red-node-xmpp installed. You need to hunt them down and remove one.
In ~/.node-red/.config.json you'll find a list of all modules Node-RED has found. Search that for xmpp and see if it is listed twice.

Please use the mailing list or slack for further assistance - that allows the whole user community to help, rather than rely on the core developers.

Thanks.
