### ISSUE TITLE
After a stop or palette update, start blocked at "Error loading flows: Error: Failed to decrypt credentials"

### ISSUE THREAD

**Issue by ArfyFR** [node-red/node-red#1611]
Since 0.18.0 

- It occurred several times after an update of Palettes.
- Sometimes after a CTRL-C and "`node-red -v`" (I am on Windows)

Here are the logs:
```
5 Feb 16:46:50 - [info] Node-RED version: v0.18.0
5 Feb 16:46:50 - [info] Node.js  version: v6.9.1
5 Feb 16:46:50 - [info] Windows_NT 6.1.7601 x64 LE
5 Feb 16:46:52 - [info] Loading palette nodes
5 Feb 16:46:56 - [warn] ------------------------------------------------------
5 Feb 16:46:56 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
5 Feb 16:46:56 - [warn] [node-red/tail] Not currently supported on Windows.
5 Feb 16:46:56 - [warn] ------------------------------------------------------
5 Feb 16:46:56 - [info] Settings file  : \Users\paborsch\.node-red\settings.js
5 Feb 16:46:56 - [info] User directory : \Users\paborsch\.node-red
5 Feb 16:46:56 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
5 Feb 16:46:56 - [info] Flows file     : \Users\paborsch\.node-red\flows_LG5Z5D72.json
5 Feb 16:46:56 - [info] Server now running at http://127.0.0.1:1880/
5 Feb 16:46:56 - [debug] loaded flow revision: 38e2f168f032cb645c74aa74c9d8626a
5 Feb 16:46:56 - [debug] red/runtime/nodes/credentials.load : no user key present
5 Feb 16:46:56 - [debug] red/runtime/nodes/credentials.load : using default key
5 Feb 16:46:56 - [debug] red/runtime/nodes/credentials.load : keyType=system
5 Feb 16:46:56 - [warn] Error loading credentials: SyntaxError: Unexpected token � in JSON at position 0
5 Feb 16:46:56 - [warn] Error loading flows: Error: Failed to decrypt credentials
```

In order to make it work again, I have to delete the credential file, launch it again and enter all the cred again !!!
(Twitter, openweather, Rainbow, Facebook) ...

I also tried to use the credential backup file, but same error.

And the cred file looked well (nothing weird at position 0)
![image](https://user-images.githubusercontent.com/3436322/35814327-159157fe-0a96-11e8-8230-256343b4979a.png)

**Comment by knolleary** [comment]
Hi,

node-red generates an encryption key for your credentials and stores it in `~/.node-red/.config.json` under the property name `_credentialSecret`. As long as that is there and is not changed, then Node-RED can decrypt your credentials.

The only time we remove the `_credentialSecret` property is if you add a `credentialSecret` of your own to your settings file - in which case we migrate from the system generated secret to the one you provided.

Here we can see in the log you haven't provided your own credential secret and it is using the default system key. But, for some reason, it isn't the right key for your credentials.

So, something has happened to the `_credentialSecret` property in `~/.node-red/.config.json`.

For example, if you created these flow files on a different instance of node-red and copied the flow/credential files over to this one... if you didn't copy the credential secret as well, the new instance wouldn't be able to decrypt.

Simply upgrading Node-RED should not have any effect on the .config.json file.

So, not sure how this has happened. It is a code path that I test frequently prior to the release of any new version.

**Comment by ArfyFR** [comment]
Hi,

Ok, I stored now the `_credentialSecret` to check it next times.
And I'll also ZIP a `flows_LG5Z5D72_cred.json` for next time =)

Other remark, in editor, if I don't delete the `flows_LG5Z5D72_cred.json`, I get/see
![image](https://user-images.githubusercontent.com/3436322/35818743-18642726-0aa1-11e8-882e-eef8de07b756.png)
but if I click on "setup Credentials" I see nothing relevant:
![image](https://user-images.githubusercontent.com/3436322/35818793-391f4752-0aa1-11e8-8241-adf48db629de.png)

I'll enter again my credentials ;)

**Comment by ArfyFR** [comment]
Hi,
Today I launched nore-red and error went back: 
```
D:\git\node-red-contrib-ale-rainbow>node-red -v
8 Feb 18:13:46 - [info]

Welcome to Node-RED
===================

8 Feb 18:13:46 - [info] Node-RED version: v0.18.2
8 Feb 18:13:46 - [info] Node.js  version: v6.9.1
8 Feb 18:13:46 - [info] Windows_NT 6.1.7601 x64 LE
8 Feb 18:13:48 - [info] Loading palette nodes
8 Feb 18:13:54 - [warn] ------------------------------------------------------
8 Feb 18:13:54 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
8 Feb 18:13:54 - [warn] [node-red/tail] Not currently supported on Windows.
8 Feb 18:13:54 - [warn] ------------------------------------------------------
8 Feb 18:13:54 - [info] Settings file  : \Users\paborsch\.node-red\settings.js
8 Feb 18:13:54 - [info] User directory : \Users\paborsch\.node-red
8 Feb 18:13:54 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
8 Feb 18:13:54 - [info] Flows file     : \Users\paborsch\.node-red\flows_LG5Z5D72.json
8 Feb 18:13:54 - [debug] loaded flow revision: 38e2f168f032cb645c74aa74c9d8626a
8 Feb 18:13:54 - [debug] red/runtime/nodes/credentials.load : no user key present
8 Feb 18:13:54 - [debug] red/runtime/nodes/credentials.load : no default key present - generating one
8 Feb 18:13:54 - [debug] red/runtime/nodes/credentials.load : keyType=system
8 Feb 18:13:54 - [info] Server now running at http://127.0.0.1:1880/
8 Feb 18:13:54 - [warn] Error loading credentials: SyntaxError: Unexpected token   in JSON at position 0
8 Feb 18:13:54 - [warn] Error loading flows: Error: Failed to decrypt credentials
```
in .config.json, _credentialSecret changed to

>  "_credentialSecret": "01243e9097b4b85c4bcd55586253af6e60f6a07b76ecfe11528b0afda871bcea"

After restoring the previous one I saved which looks like:
```
"_credentialSecret": "<not the same key>",
 "users": {
  "_": {
   "editor": {
    "view": {
     "view-grid-size": 20,
     "view-node-status": true,
     "view-show-tips": true
    }
   }
  }
 }
```
all went back OK =)

**Comment by anandrajana** [comment]
Hi I'm getting same issue. Is there a fix for this?. I tried changing the _credentialSecret but it didn't work.
![image](https://user-images.githubusercontent.com/5894623/36426962-c9e15768-1671-11e8-9be0-7dd6e9ee7507.png)

**Comment by chewbaccah** [comment]
Same issue here.  Mine went down after upgrading Dietpi to 6.2.  I did not save my old .config.json file.  Any ideas?

**Comment by knolleary** [comment]
@anandrajana @chewbaccah please see my comment above https://github.com/node-red/node-red/issues/1611#issuecomment-363133120 for the background. If you don't have the credential secret that was used to encrypt the file, you're not going to be able to decrypt it.

Move your credentials file sideways and restart node-red - you'll then need to re-enter any credentials you had configured. You credentials file is the same name as your flow file, but with `_cred` in the name.

In meantime, I'm trying to figure out what can cause the cred secret to get wiped - it isn't something we do in our code.

**Comment by joseska** [comment]
same here.... yesterday work with node-red. Today I open and get this error....

**Comment by Silvia-t** [comment]
I got the same error after messing with the settings.js :(

I ended up deleting the credentials file, rebooting, entering the credentials again and deploying, and it worked. So no more playing with settings for the moment! :laughing:

**Comment by mblackstock** [comment]
We're working on upgrading our customers from 0.17.5 to 0.18.4 with no project features, but running into similar snags related to credentials:

In FRED, we set an environment variable to the instance's credentials key when we create our docker container.
This is configured in settings.js by setting the secret to process.env.CREDENTIALS_SECRET (or similar).

When we upgraded a few instances on our test system to 0.18.4 from 0.17.5 we sometimes see the new error message, and a "Setup Credentials" button with "project settings" tab with no content inside.  Note that the error message refers to project functionality, even when projects are disabled.

So far this happens only in a few cases, and we're not sure what's caused this.  We have tried a number of things to get Node-RED to read the credentials file, but no luck.

We're pretty convinced the secret we supply is the same and the credentials file hasn't changed, however once this error appears, the credentials file cannot be decrypted even if we roll back to 0.17.x or older.   Not completely sure since old versions didn't come up with an error in the UI, and allowed flows to run.  Still looking into it.

We're struggling to get to the bottom of this, but will keep you posted.  Regarding the error box, our suggestion is to remove the references to projects functionality when the feature is disabled, and provide an option to create a new credentials file in case the credentials are no longer readable, otherwise, it's not possible to re-enter credentials and start flows without resorting to the command line.

**Comment by skiddex-ga** [comment]
I had a similar problem in adding projects to settings.js, until I noticed the comma at the end of the preceding curly brace in the block. After adding the comma, the project code could be added without error. 
When I restarted node-red in Powershell (Windows installation) and opened the address localhost:1880 in the editor, the project add on started as expected. I would presume other devices such as Raspberry Pi, android, etc., could be configured in a similar fashion.

**Comment by skiddex-ga** [comment]
Sorry about my previous comment regarding this question. The device I edited settings.js for was on a Raspberry Pi with Stretch by using sudo nano, not Pshell on Windows. I just added a comma to the preceding closing curly brace on settings.js saved it and restarted node-red, and it worked to add projects to the editor.  The editor was run on a Window's browser linked to the Pi. Node Red was running in a bash shell on the Pi.

**Comment by knolleary** [comment]
This scenario will be better handled in 0.18.5 thanks to #1689 and associated fixes.

**Comment by janvda** [comment]
Hi,
I am facing the same or similar issue.
FYI here below the output of node-red log file running on my raspberry pi:
```
Starting as a systemd service.
Started Node-RED graphical event wiring tool..
1 May 18:17:43 - [info]
Welcome to Node-RED
===================
1 May 18:17:43 - [info] Node-RED version: v0.18.4
1 May 18:17:43 - [info] Node.js  version: v6.12.3
1 May 18:17:43 - [info] Linux 4.9.35-v7+ arm LE
1 May 18:17:44 - [info] Loading palette nodes
1 May 18:17:50 - [info] Dashboard version 2.9.1 started at /ui
1 May 18:17:52 - [info] Settings file  : /home/pi/.node-red/settings.js
1 May 18:17:52 - [info] User directory : /home/pi/.node-red
1 May 18:17:53 - [info] Server now running at http://127.0.0.1:1880/
1 May 18:17:53 - [info] Active project : node-red-contrib-slack-test
1 May 18:17:53 - [info] Flows file     : /home/pi/.node-red/projects/node-red-contrib-slack-test/flow.json
1 May 18:17:53 - [warn] Error loading flows: Error: Failed to decrypt credentials
1 May 18:20:39 - [info] Setting active project : pi3three
1 May 18:20:39 - [info] Flows file     : /home/pi/.node-red/projects/pi3three/flows_pi3three.json
1 May 18:20:39 - [warn] Error loading flows: Error: Failed to decrypt credentials
```
In my case this problem appeared because for some reason I couldn't stop node-red using the node-red-stop command.  In the end I killed the node-red process but since then I got above issue with the credentials file.

So currently node-red doesn't start my flows.

I am using the "projects" feature.  It is not fully clear to me how I can recover from this issue.
Do I need to delete the credential file ( _cred.json) in the `.node_red/` folder or in the `.node_red/projects/<project_name>/` folder ?  Or is there another (better) way to recover ?

kr
jan.

**Comment by knolleary** [comment]
@janvda rather than comment on a closed issue, I'd recommend you posted to the mailing list in the future.

In this instance, as you have projects enabled you _should_ still be able to open up the editor and follow the prompts it provides to re-enter the credentials key you set when you created the project.

**Comment by janvda** [comment]
I managed to fix it by (re)setting my credential password for the project using the node-red UI.

**Comment by bigdoods** [comment]
Anybody struggling with this, my solution was to remove ```flows_cred.json``` and restart
