### ISSUE TITLE
dynamic color based on value

### ISSUE THREAD

**Issue by aryeharmon** [node-red/node-red#1630]
is it possible to set a dynamic color based on a value?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you had read the issue template you were shown whilst  creating this issue you would have seen contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md).

We prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Your question is also missing a lot of detail for us to understand what you mean. Where do you want to set the dynamic colour?


Thanks!
