### ISSUE TITLE
How add argument to a flow (tab)

### ISSUE THREAD

**Issue by briva** [node-red/node-red#1634]
Hello,

It is possible to add argument to a flow (tab) ?

There is name, status and description. But i like to add other argument.

Thx.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

The issue template you would have seen when you created this issue describes our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md).

You'll see we prefer to handle how-to type questions on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

You'll also need to add a bit more detail to your question for us to understand what you are trying to do. In short, no, you cannot add custom properties to a flow. If you want to explain a bit more about what you want to achieve, there may be alternative approaches available.

Thanks!
