### ISSUE TITLE
Raspberry without HDMI cable

### ISSUE THREAD

**Issue by lucasozorio** [node-red/node-red#1656]
Hey !
I'm developing a program in Raspberry Pi 3 and NodeRed. 
The raspberry pi requires the HDMI cable to see the video output. But the point of my program is to work without any cable (using a free raspberry with bluetooth for the sound, wifi for the internet and a button for the comands).
The problem is that when I remove the HDMI cable, the system in Nodered is disconected and I can't work with it anymore. When I put the cable back, the Nodered is back again.
Does anyone know what I should do to solve this problem and work without the cable?

Thanks in advance,
Lucas.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) or read the issue template  you were  shown, you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
