### ISSUE TITLE
s7-Out, send a Boolean command

### ISSUE THREAD

**Issue by mrsalhaoui** [node-red/node-red#1667]
### Please tell us about your environment:

- [x] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
I assume we can close this issue? Or is there an issue report to come?

**Comment by mrsalhaoui** [comment]
Hello,
I'm trying to send the value true or false to my PLC, using the node S7, but it doesn't work when I put the adress :  DB3.X42.0 or even DB3.BOOL42.0.


![imagen](https://user-images.githubusercontent.com/33464198/37298451-9bc7823a-2620-11e8-9c4b-6ad7e3995636.png)

**Comment by dceejay** [comment]
Hi, thanks for raising an issue.

If you check out our contribution guidelines or read the issue template you were shown, you'll see we prefer to handle this sort of thing on the mailing list, slack team or you could ask a question on Stack Overflow and tag it node-red. That way the whole Node-RED user community can help, rather than rely on the core development team, who don't actually know anything about s7 PLCs.

Thanks!

**Comment by mrsalhaoui** [comment]
Ok Thank you.
