### ISSUE TITLE
json file instead of html file for node localization

### ISSUE THREAD

**Issue by aoighost** [node-red/node-red#1682]
The ability to set localization and tagging for nodes in JSON instead of HTML would be greatly helpful when Node-Red goes headless to allow for non-web UI editors to be able to pull node data.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by aoighost** [comment]
Alright, thanks, much appreciated. Sorry about that, which would you suggest I submit to?

**Comment by knolleary** [comment]
The mailing list is a good place to post a suggestion for discussion.

But it would help if you can expand a bit more on what you're looking for. The localization messages for a node are in a json file - its only the sidebar help text that is in the html file which is only used by the editor so not relevant to a headless runtime.

**Comment by knolleary** [comment]
Closing as this is a feature request/discussion that belongs on the mailing list.
