### ISSUE TITLE
access "global" from HTML file script

### ISSUE THREAD

**Issue by farfromrefug** [node-red/node-red#1688]
Hi,

Is there a way to access the "globlal" from the HTML side?
I want to do ```global.get('mydata')``` but cant find a way to do this.

The idea is that i want to require a node module from the html side (not a native module).

Thanks

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by farfromrefug** [comment]
@knolleary sorry will do!
