### ISSUE TITLE
Node red hangs . - Running in google cloud.

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [node-red/node-red#1703]
We are using node-red and deployed it in Google cloud along with our Java and mongoDB application.

It was working fine now it is hanging quite often but our Java application working without any issue . 

Most of the time our server CPU speed is around 10-20% but CPU speed rise to 60% whenever node-red hangs. 

Node-red  is talking to mongoDB and few http connectors.

I have also updated the node red version. We use v.0.18.4. Please let me know how can i solve this

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

The issue template you were shown, and deleted, describes our preferred contribution process.

You'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

In this instance, you could use some Debug nodes to try to identify where messages are flowing and what may be getting stuck. Do you have any loops in your flow that could be running away? What contrib nodes are you using? All of this is useful information needed to help you identify the problem.

Thanks!

**Comment by Jeyakumarrathnaselvi** [comment]
Below are the node we are using. We don't have any open loop. It was working fine for last 6 months

![image](https://user-images.githubusercontent.com/36895131/38991190-72daf4fe-43fa-11e8-94ff-4e4d568a0764.png)



![image](https://user-images.githubusercontent.com/36895131/38991172-65953ade-43fa-11e8-949d-e6f0b5fdec8b.png)


![image](https://user-images.githubusercontent.com/36895131/38991146-545fb802-43fa-11e8-8d1a-a6842ee7cd7f.png)

**Comment by knolleary** [comment]
Hi, sorry, we can't debug your flow for you. You need to add some debug nodes to understand where NR is hanging.

**Comment by knolleary** [comment]
As this issue sounds like a flow issue rather than a bug in Node-RED, I'm going to close it. If you're still having problems, please follow up on slack or the [node-red forum](https://discourse.nodered.org)
