### ISSUE TITLE
Some declared wiring disappears when importing flow from 0.17.x into 0.18.x

### ISSUE THREAD

**Issue by wnm3** [node-red/node-red#1737]
### What are the steps to reproduce?
We have some custom developed nodes that are linked to Node-RED. Their flow has validly defined links (wires) to pairs of debug and other nodes as shown below.

        "wires": [
            [
                "bb42c272.6aeea",  // debug node
                "7df6bc36.7b1c14" // another custom node
            ],
            [
                "f1e0d2c0.ee76a", // another custom node
                "bbc559ac.d3e3e8" // debug node
            ]
        ]

### What happens?
When we import the flow exported from 0.17.5 Node-RED, all the components are displayed but this particular node does not show any outbound links to other nodes.

If we open the node, and we delete and recreate the outbound ports, they are properly displayed and we can relink the node to other nodes. Our code defines the number of output ports in the HTML configuration of this node.

![image](https://user-images.githubusercontent.com/1359024/40494558-23616a84-5f43-11e8-956d-a2cbd8797556.png)

I can provide the exported flow, but can not provide the actual code for these custom nodes. If there is something more you need or specific parts of the code relating to the output ports, I can likely provide that.

### What do you expect to happen?
The defined links to other nodes should be rendered and operational.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.6 fails but 0.17.5 works
- [ ] node.js version: 8.11.2
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Ubuntu 16.4 or macOS 10.13.4
- [ ] Browser: Chrome or Firefox latest versions

**Comment by knolleary** [comment]
What is the `outputs` property of your custom node set to?

Fixes were made in 0.18 where we were inconsistent in handling a difference in the length of the wires array and the value of the outputs property of the node. It could leave behind phantom wires where there was no output.

In 0.18 the outputs property now takes priority - it is the declared number of outputs the node should have. The wires array will be clipped to match. We also log this has happened in the javascript console.

**Comment by wnm3** [comment]
The nodes outputs variable in the html is set to 0 for this node when we register the node. However, during configuration of the node, we increment the outputs for each "step" that we configure. When the flow is exported, the wires are defined and the number of outputs should be inferred from there, not from the way the node is initialized IMHO.  We can't know ahead of time what outputs should be.

Here are the relevant references to outputs in the html:
````
    (function() {
        RED.nodes.registerType("workFlow", {
            category: "WILD",
            defaults: {
              name: {value: "Cohibas Workflow"},
              debugon: {value: false},
              username: {value: "username"},
              password: {value: "password"},
              flowsteps: {value: ""}
            },
            color: "rgb(200,255,600)",
            width: {value: 5000} ,
            inputs: 1,
            outputs: 0,
            icon: "workFlow.png",
            paletteLabel: "workFlow",
            label: function() {
                return this.name || "workFlow";
            },
            labelStyle: function() {
                return this.name ? "node_label_italic" : "";
            },
            oneditprepare: oneditprepare,
            oneditsave: oneditsave
        });
    })();
````
and when steps are added the counter is incremented. We have one step that can not be deleted (why the +1):
````
<script type="text/javascript">
	var counter = 0;
	var limit = 20;

	var oneditsave = function() {
		this.outputs = counter+1;
		this._outputs = counter+1;
````

![image](https://user-images.githubusercontent.com/1359024/40502639-8dc2201a-5f59-11e8-8a3d-ec5552dd202e.png)

**Comment by knolleary** [comment]
To have a dynamic number of outputs the need needs to define `outputs` in its `defaults` array - so the editor knows to save modified `outputs` property with the node. For example, the Function node does so here: https://github.com/node-red/node-red/blob/master/nodes/core/core/80-function.html#L64

The problem here though is you have nodes deployed without their outputs property set and the node definition explicitly setting output to zero. There's no easy fix here unless we revert the change we made - which then re-breaks the other user's scenario where they have reduced the value of outputs and require the wires array to be clipped accordingly.

**Comment by knolleary** [comment]
Ok, I _think_ I have a fix, but it will need changes for both of us:

1. you need to add `outputs` to your defaults array.
2. we will add a check that if the node declares `outputs` but its value is blank or missing, we'll defer to the wire array length. Otherwise we'll clip the wire array length to the value of outputs.

We'll be doing 0.18.7 tomorrow - will get this included in that.

**Comment by wnm3** [comment]
Great idea. Thank you.
