### ISSUE TITLE
assign custom property to array not working

### ISSUE THREAD

**Issue by smogaurea** [node-red/node-red#1755]
### What are the steps to reproduce?
 function example
```
var a = [4,5,6];
a.asd=2323;

return {s:a};
```

### What happens?
doesnt assign custom property on array

### What do you expect to happen?
its a valid js code if you run it in browser console/node console the output is
```
[4, 5, 6, asd: 2323]
```

### Please tell us about your environment:

- [x] Node-RED version: 0.18.7
- [x] node.js version: 10.2.1
- [x] npm version:5.6.0
- [x] Platform/OS:mac
- [x] Browser:chrome

**Comment by knolleary** [comment]
It depends on how you're trying to access the property in subsequent nodes.

Let's say your function is:

```
var a = [4,5,6];
a.asd=2323;
msg.payload = {s:a};
return msg;
```

If you add a Debug node immediately afterwards then you won't see the `asd` property - this is because the message gets JSON encoded and arrays cannot have properties - so the `asd` property does not get displayed. If anything, _that_ is the issue here - not that the property doesn't get set, but rather the Debug node isn't able to display custom array properties.

If you configure the Debug node to show `msg.payload.s.asd` - ie access the property directly, you'll see it is set and available for referencing.

**Comment by knolleary** [comment]
@smogaurea can you confirm what I describe above works for you? The property is being set, the Debug node isn't able to display it.

I've been digging into how we could enable the Debug node to display them, however there's simply no efficient way of doing it without checking every property key of every array to see if its an integer key or not. That would be a massive performance penalty for all arrays on the off-chance there's an unexpected property attached to it.

**Comment by smogaurea** [comment]
yah it was a json cast issue . thanks  ))

**Comment by knolleary** [comment]
I've come to the conclusion we're not going to 'fix' this. Whilst JavaScript allows arrays to have properties - by virtue of them being Objects - the cost of detecting them and displaying them is too significant.
