### ISSUE TITLE
Dot inside query string not converted to underscore

### ISSUE THREAD

**Issue by hutje** [node-red/node-red#1759]
### What are the steps to reproduce?
When I get a HTTP Request with: https://www.website.nl/webhooks?hub.challenge=0000
This query string consists of hub.challenge. I need to respond with the value of hub.challenge.

### What happens?
I can't respond because the template-node can't handle {{req.query.hub.challenge}}.
When I try to use hub_challenge as parameter inside the query string and change the template node it works.
But unfortunately the Facebook API works with hub.challenge to verify your server.

### What do you expect to happen?
I want to know how to change the msg so I can change the dot to an underscore.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.7
- [ ] node.js version: Newest available 09-06-2018
- [ ] npm version: Newest available 09-06-2018
- [ ] Platform/OS: Raspbian Stretch
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

The mustache syntax used by the Template node does not support properties with dots in their name.

If you want to set `msg.payload` to the value of `msg.req.query["hub.challenge"]` (note the use of the bracket syntax to cope with the dot) then can use a Change node to do that.



Thanks!
