### ISSUE TITLE
"You must be logged in to deploy changes" v0.18.7

### ISSUE THREAD

**Issue by fsamir** [node-red/node-red#1761]
### What are the steps to reproduce?
- Install NR v018.7 
- Embedded Node-red in an expressJS App.
- Do not enable any form of authentication in Node-red.
- My custom NR settings are:
``` var settings = {
        httpAdminRoot: '/red',
        httpNodeRoot: '/api',
        nodesDir: config.nodesDir,
        userDir: config.nodeRedUserDir,
        verbose: true,
        editorTheme: {
            userMenu: false
        },
        functionGlobalContext: {},
        ui: {
            path: 'red/ui'
        }
    };
```

### What happens?
 The message `You must be logged in to deploy changes` is displayed, when I try to deploy any flows.

This started happening after I upgraded NR from 0.14.6 to 0.18.0, so I suspect the bug was introduced by the OAuth authentication.

### What do you expect to happen?
- The deployment to succeed, 

### Please tell us about your environment:

- Node-RED version: v0.18.7
-  node.js version: 8.1.3
- npm version: 5.0.3
- Platform/OS: RaspberryPi 3
- Browser: Chrome

**Comment by knolleary** [comment]
In earlier versions of Node-RED we would ignore what we thought we knew about the user's logged in state and submit the deploy http request regardless.

In 0.18 we added a check to see if the current user has permission to access the route before sending the request.

A request to `/settings` includes information about the current user, including what permissions they have. For example:

`{"httpNodeRoot":"/","version":"0.18.7","user":{"anonymous":true,"permissions":["read","inject.write"]}}`

The fact you have used your own custom authentication rather than the built-in auth system means you probably don't have a `permissions` object being returned here.

The object is automatically populated from the `req.user` object the route handler receives: https://github.com/node-red/node-red/blob/master/red/api/editor/settings.js#L33-L40

So your app needs to be include a `permissions` object on the `req.user` you are creating.

**Comment by fsamir** [comment]
I've tested a couple of other version to narrow the broken one down:

- v0.16.2-  works
- v0.17.2-  works

**Comment by fsamir** [comment]
Hi @knolleary,

I will follow your advice and see if I can apply to my solution ASAP. Thanks.

**Comment by knolleary** [comment]
Closing as this isn't a Node-RED issue. Happy to discuss further it if needs.

**Comment by fsamir** [comment]
@knolleary it worked. Thanks
