### ISSUE TITLE
Node-Red and Brain JS Integration

### ISSUE THREAD

**Issue by cjkini** [node-red/node-red#1829]
Hi guys,

Has anyone here tried Node-Red and Brain JS integration using this Node ?
(https://flows.nodered.org/node/node-red-contrib-neuralnet)

Can u guys share how you are doing it?

Thanks.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md), or the issue template you were shown when you opened this issue, you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
Hi, as per the issue template you have deleted, we prefer general questions questions via the discourse forum or slack channel so the wider community can help rather than rely on the core developers. In this case I know we haven’t had a chance to use that node so you’ll have to ask the wider group so I’m closing this issue
