### ISSUE TITLE
after successful import, no feedback and new flow is not selected

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red#1862]
### What are the steps to reproduce?

Import a flow, e.g., via clipboard.

### What happens?

The flow is imported, but not selected.  No "success" messaging appears.

### What do you expect to happen?

1.  "Success" messaging, e.g., "Your flow was imported as *<Flow Name>*"
2.  The new flow tab is selected.

### Please tell us about your environment:

- [x] Node-RED version: d373105b32d7b04cca6115b891f042c2b21339c2
- [x] node.js version: 10.9.0
- [x] npm version: 6.4.0
- [x] Platform/OS: macOS X
- [x] Browser: Chrome

**Comment by knolleary** [comment]
I realise give the exact commit sha is a precise way to share the version, but it would be handy if you gave a human readable version to save me looking it up. .. ie "latest in git master"

I don't think we've ever had a success message on import - so is this a regression you're reporting or a change in behaviour you'd like?

If you import some nodes they are attached to the mouse for you to place in the current flow.

If the imported nodes includes a tab node, then the tab will be added in the background - is that the behaviour you're talking about? If so, that isn't necessarily intentional behaviour, so yes, it could be improved.

**Comment by boneskull** [comment]
> I realise give the exact commit sha is a precise way to share the version, but it would be handy if you gave a human readable version to save me looking it up. .. ie "latest in git master"

Sorry, thought this would link to the changeset; it won't if you wrap the SHA in backticks, apparently...

> I don't think we've ever had a success message on import - so is this a regression you're reporting or a change in behaviour you'd like?

If it never worked as such, then it's the latter.  

The gist of it is: "I imported a flow and didn't immediately realize it worked."

**Comment by knolleary** [comment]
Fixed in `dev` for 0.20
