### ISSUE TITLE
How Node-RED Start/Stop Flow(s) from command line

### ISSUE THREAD

**Issue by thuylevn** [node-red/node-red#1882]
Hi all, 

Would you like to share How Node-RED Start/Stop Flow(s) from command line?

Thank you so much,
ThuyLe

### Please tell us about your environment:

- [x] Node-RED version:
- [x] node.js version:
- [x] npm version:
- [x] Platform/OS:
- [x] Browser:

**Comment by knolleary** [comment]
Hi @thuylevn 

 Thanks for raising issue.

This issue tracker is for problems with the Node-RED runtime, the editor or the core nodes.

If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change,
  - or problems with 3rd party (`node-red-contrib-`) nodes

please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

You could also consider asking a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

That way the whole Node-RED user community can help, rather than rely on the core development team.
