### ISSUE TITLE
Fix global.get("foo.bar") for functionGlobalContext set values

### ISSUE THREAD

**Issue by openSoftMan** [node-red/node-red#1883]
Hey Nick,
Thanks for the quick response on discourse.

- [v0.19.3] Node-RED version:
- [v8.11.4] node.js version:

I tested the [commit](https://github.com/node-red/node-red/commit/0f4d46671f5cefe00d306eefd3e9f208986ff210) and it does fix the global.get for an object, but something else is going on here.

Import this flow:
`[{"id":"f04a7ee8.bc4dc8","type":"inject","z":"db0d5b42.be5f8","name":"Go","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":"","x":510,"y":200,"wires":[["61d941a9.4cf188"]]},{"id":"61d941a9.4cf188","type":"function","z":"db0d5b42.be5f8","name":"get gVar.counter","func":"msg.payload = global.get(\"gVar.counter\");\nreturn msg;","outputs":1,"noerr":0,"x":670,"y":200,"wires":[["a2d4f073.4edd08"]]},{"id":"a2d4f073.4edd08","type":"debug","z":"db0d5b42.be5f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":850,"y":200,"wires":[]},{"id":"56d40926.e258f","type":"inject","z":"db0d5b42.be5f8","name":"Load Manually","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":540,"y":260,"wires":[["914ad10b.7d9ad8"]]},{"id":"914ad10b.7d9ad8","type":"file in","z":"db0d5b42.be5f8","name":"Reload gVar.js","filename":"/home/pi/.node-red/gVar.js","format":"utf8","x":720,"y":260,"wires":[["a65fbaeb.1fc4d8"]]},{"id":"a65fbaeb.1fc4d8","type":"function","z":"db0d5b42.be5f8","name":"parse","func":"msg.payload = msg.payload.replace('module.exports=','');\nglobal.set(\"gVar\",JSON.parse(msg.payload));\nreturn msg;","outputs":1,"noerr":0,"x":870,"y":260,"wires":[["a2d4f073.4edd08"]]}]`

Create a file "/home/pi/.node-red/gVar.js" and put this in it:
`module.exports={"counter":0,"isHome":true,"isSound":true,"isSoundAway":true,"isLight":true,"isLightAway":true,"button1State":true,"button2State":true,"prevAlarmCnt":1,"lmNodeID":1,"dalNodeID":2,"dht11NodeID":3,"dht22NodeID":4,"pirNodeID":5,"gateNodeID":6,"bmeNodeID":7,"adcNodeID":10,"w1NodeID":11,"w2NodeID":12,"w3NodeID":13}`

I have this at the beginning of my settings.js:

// DG added - Global Vars
	var gVar;
	try {
		gVar = require("/home/pi/.node-red/gVar.js");
	} catch(err) {
		gVar = {};
	}
// DG end - Global Vars

And this is in settings.js under
    functionGlobalContext: {
        // os:require('os'),
        // jfive:require("johnny-five"),
        // j5board:require("johnny-five").Board({repl:false})
        // DG added below this line (**use comma when adding more options):
        fs:require('fs'), // read/write files in function nodes
        gVar:gVar // See start of this file
        // DG added - END (**No comma on last line)
    },

This should set you up for the test case.

Steps:
1) sudo service nodered restart
2) in syslog you'll see [error] [function:get gVar.counter] TypeError: Cannot read property 'counter' of undefined
3) look at new context browser, gVar object was loaded properly.
![gvar](https://user-images.githubusercontent.com/10749849/45269309-dd23cc80-b459-11e8-8ac8-30d12eb44ac2.PNG)
4) Go to the flow and click "Go" (configured inject at start-up).  The result is "TypeError: Cannot read property 'counter' of undefined" as in syslog at startup.
5) Now manually click "Load Manually" inject and gVar can be accessed at will.
6) Click "Go" again and it gets returned.

I know I need to get away from this method of persistence. This method only covers 10% of my persistent variables.  It does allow me to control disk writes during testing.

Thanks again!

**Comment by knolleary** [comment]
Thanks for the detailed issue report - always helpful.

You've hit a subtle case that affects both the in-memory and file-based context stores - both of which are now fixed. Will release 0.19.4 in the next day or so (am on vacation, but will have time to do it tomorrow hopefully).

In case you're interested in the details... we have a utility function to get the value of an object's property based on a string description. So in your case, it is passed in the contents of global context and the string "gVar.counter".

If the value doesn't exist, there are two possible cases.

1. if `gVar` exists, but doesn't have a `counter` property, then it returns `undefined`
2. if `gVar` doesn't exist it throws an error

It was this second case you were hitting. But why, you may ask, does `gVar` not exist when you have set it via `functionGlobalContext`. Well, that's because the code has to first check the in-memory context to see if it has a newer value for `gVar.counter` before it looks at whatever was in `fGC` - and it's this lookup in memory that was hitting the error. It's a valid error to hit - but the memory context store should have accepted it and returned `undefined`.
