### ISSUE TITLE
Document RaspberryPi/Node 0.10 command line args

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#191]
The supposed memory leak with Node 0.10 on Pi doesn't exist and the docs need updating to reflect this fact.

The problem we thought was a leak is that by default Node will try to use up to 512Mb of memory. The change in garbage collection policy between 0.8 and 0.10 means it is more likely to keep requesting memory up to this limit before GC kicks in.

On a Pi, you only have 512Mb memory in total, so the OS kills the process before GC can do its thing.

There is a [command line argument](https://github.com/joyent/node/wiki/FAQ#what-is-the-memory-limit-on-a-node-process) to node to change this limit: `--max-old-space-size`. We need to confirm this 'fixes' the out of memory crash when run with a suitable value - and what value we recommend.

**Comment by TotallyInformation** [comment]
As a Pi2 has 1GB of RAM, is this parameter still required? I've been running 2x NR plus MongoDB and Mosquitto on my Pi 2 without the parameter for some months now with no apparent problem.

pi@pi2 ~ $ free -h
             total       used       free     shared    buffers     cached
Mem:          925M       904M        20M        13M       120M       327M
-/+ buffers/cache:       457M       468M
Swap:         999M         0B       999M

pi@pi2 ~ $ uptime
 20:41:40 up 5 days, 20:31,  2 users,  load average: 0.11, 0.09, 0.06

Only 5d uptime because I was messing with systemd startup scripts last week.

**Comment by knolleary** [comment]
Yes it is. The memory limit at which it might hold off garbage collecting until is still over 1Gb. Can't say why you've not hit issues, but that's the documented best practise for node.js - see http://blog.heroku.com/archives/2015/11/10/node-habits-2016#7-avoid-garbage for example.

**Comment by dceejay** [comment]
Well - it'd up to you. I think the node.js default is 2GB so potentially heavy usage could still cause problems. - You can probably relax it back to 1GB without issue.

and indeed lots of PaaS users want to run on machines with limited memory to keep within the free tier limits... so generally it's a good idea.

PS - we've also been playing with systemd -  https://github.com/node-red/raspbian-deb-package/tree/master/resources

**Comment by TotallyInformation** [comment]
Thanks guys. I'll adjust my startup.

**Comment by TotallyInformation** [comment]
"we've also been playing with systemd " - cool! Good move I think. I'm glad I made the move, a little more complex to get your head around than PM2 but lightweight on resources and reliable as far as I can tell. I also like the ability to make sure other services are up before running. In fact, you might want to add something to the documentation when you get to updating so that people know that they can delay startup until MongoDB/Mosquitto or whatever is ready.
