### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by stherrienaspnet** [node-red/node-red#1919]
Hello, which wonderfull UI library are you using for your nodes and their connections?
Many thanks, I really enjoy red-node!

**Comment by hardillb** [comment]
Please read the template you deleted when you asked this question

**Comment by stherrienaspnet** [comment]
Sorry, how could i read the template again without creating a new issue?
I just wanted to know wich graphical library was used to for drag & drop nodes and connectors or maybe it was all build from scratch. Sorry again :)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!
