### ISSUE TITLE
Node-Red needed help

### ISSUE THREAD

**Issue by 123Franek** [node-red/node-red#1951]
Hello, will anyone help me change it
 https://www.yellownote.nl/blog/index.php/2014/01/18/solarpanel-monitoring-via-rasperry-pi/#comment-522
 to Node-Red

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by 123Franek** [comment]
ok
