### ISSUE TITLE
New Issue Web Request when behind a work proxy 

### ISSUE THREAD

**Issue by stumm101** [node-red/node-red#1963]
Hello,
I'm having a problem similar to the one in this thread.
I have two raspberry pi with raspbian stretch lite, in them is node-network V0.19.4. One raspi I have it in my house, the other one in my work, the one that is in my work I have it behind a web proxy. both are identical except for the latter, the work is after a proxy.
Well, I have a flow inject-> http request-> debug the url of the http node is something like "https://api.telegram.org/bot57:AAElikjZOEMU/sendMessage?chat_id=-2647&text=Test from home"
In the home node-network works perfectly, in the node-network of the work does not work, gives the error: "" Error: tunneling socket could not be established, cause = connect EINVAL 0.0.31.144:80 - Local (0.0.0.0 : 0) ""

I have adjusted the proxy both in the linux system, and in the nodered.service file, but I can not get it to work.
how can I solve that?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
This has been discussed at length and resolved in slack.
