### ISSUE TITLE
failure in required module instanceof Function

### ISSUE THREAD

**Issue by anthonyvercolano** [node-red/node-red#1965]
### What are the steps to reproduce?

Application developer was using the Azure IoT node SDK in their flow.

Inside of a Function node the following code was used:

var require = global.get('require');

var iothub = require('azure-iothub');

var connectionString = " service connection string to an Azure IoT Hub ";

var device =  {   deviceId: "a device name"   };
 
var registry = iothub.Registry.fromConnectionString(connectionString);

registry.get(device.deviceId, function(err, deviceInfo, res) { console.log(deviceInfo);   });
return msg;

### What happens?

The following error occurs when executing the flow

TypeError: Callback has to be a Function

This occurs because of the following test inside the code path for registry.get

        if (!(userCallback instanceof Function)) {
            throw new TypeError('Callback has to be a Function');

### What do you expect to happen?
Well we expect our code (the Azure IoT Node SDK) to not throw here.

Is it possible that the right hand side of the instanceof operator in the if is being interfered with by the "Function" object of node-red?

### Please tell us about your environment:
 Nov 14:28:52 - [info] Node-RED version: v0.19.5
9 Nov 14:28:52 - [info] Node.js  version: v8.11.3
9 Nov 14:28:52 - [info] Windows_NT 10.0.17763 x64 LE

**Comment by knolleary** [comment]
This is a known issue with the `vm` module used by the Function node - https://github.com/nodejs/node-v0.x-archive/issues/1277

The basic problem is the context of the vm sandbox has a different Function object then that outside the sandbox. So `Function(create inside vm sandbox) instanceof `Function(outside vm sandbox)` will always fail.

In general it is safer to use a `typeof` test rather than `instanceof` - as per some of the discussion in that issue.

We _could_ apply a fix that passes in the Function object into the sandbox, but we'd need to be careful to not remove the benefits of using the vm module in the first place.

**Comment by anthonyvercolano** [comment]
Thank you for the reply.  Have adjusted to typeof.
