### ISSUE TITLE
Flow initialization failing, if websocket is defined in a subflow

### ISSUE THREAD

**Issue by ManfredMeise** [node-red/node-red#1974]
### What are the steps to reproduce?
- create a subflow containing 1 input and a websocket out node
- create a simple main flow with an inject node calling the above mentioned subflow

### What happens?
- deploying and initializing this simple flow works fine.
- add another inject node and call to the subflow in your main flow
- deployment works find, but during flow initialization the websocket generates errors "Missing server configuration" and "Error: two instances of WebSocketServer cannot listen on the same http server path"

### What do you expect to happen?
Being able to call a subflow (containing a websocket) as often as the application requieres from different flows and subflows without any configuration issues.

### Please tell us about your environment:

- [ ] Node-RED version: 19.4 or even less? It did work as expected until last week, where I restaged (and updated) my app
- [ ] node.js version: 8.11.2
- [ ] npm version: ?
[websocket-error.zip](https://github.com/node-red/node-red/files/2576691/websocket-error.zip)

- [ ] Platform/OS: Linux and Windows
- [ ] Browser: Firefox

**Comment by knolleary** [comment]
You cannot have two websocket listeners registered on the same path.

When you add a websocket node to a subflow you also configure its websocket-listener configuration node within the subflow.

If you then add two instances of the subflow into your main flows you are asking the runtime to have two listeners on the same path and hence the error.

This is because the `websocket-listener` you've added is contained within the subflow and so gets duplicated with each instance of the subflow you add.

You can make the websocket-listener a global config node which means the one instance of it will be shared by the subflow instances - thereby removing the duplicate listener.

To do that, edit your websocket out node, then click the pencil button next to the path field to edit the listener config node. At the bottom of its edit dialog is a select box. It will probably have the name of your subflow listed - that's the scope of the subflow. Change its value to the one at the top of the list - On All Flows. That will make it global.

**Comment by ManfredMeise** [comment]
first of all thanks, for a quick and helpful response.

I was not aware of this configuration option of the config nodes! Your hint to make the configuration global solves my issue. Is this a configuration node definitiono a new feature which came in recently?
