### ISSUE TITLE
Mosquitto port set with an env var

### ISSUE THREAD

**Issue by paulRenault** [node-red/node-red#1980]
- [ ] Node-RED version: 0.19.5 (docker)
- [ ] node.js version: v8.12.0
- [ ] npm version: 6.4.1
- [ ] Platform/OS: ubuntu 18.04
- [ ] Browser: chromium 70.0.3538.77 (Build officiel) snap (64 bits)

When you set the MQTT port with an env var and you try to deploy, you had the error : "The workspace contains some nodes that are not properly configured" but if you click on the button "Confirm deploy" it's works.

**Comment by knolleary** [comment]
This is because the node is validating the value you provided is a number - an obviously an env var isn't recognisable to the editor as a number.

This raises a broader question for any node that attempts to validate its properties - it cannot know what you've set the env var to, so cannot validate you get it right.

We could update the build-in type validators to accept env var entries as well as whatever type they target.

**Comment by paulRenault** [comment]
Thank you for your fast answer.

The possibility to set the configuration node with an env var is very useful.

> We could update the build-in type validators to accept env var entries as well as whatever type they target.
:+1:

**Comment by knolleary** [comment]
Looks like we already had some logic to handle this via this commit - https://github.com/node-red/node-red/commit/37d4a6b9e20b4465cdbd6d5683b80a036d48c194 - since 0.13.4! However it only handles `$(ENV-VAR)` and not `${ENV-VAR}` ... so a simple change to support both styles.
