### ISSUE TITLE
Function node syntax error on valid syntax (object spread ES6)

### ISSUE THREAD

**Issue by bugs181** [node-red/node-red#1988]
### What are the steps to reproduce?
Input code into a Function node: 

`let mergedObj = { ...obj1, ...obj2 }`

     [{"id":"ce6014db.f6b75","type":"function","z":"af7ead90.843a8","name":"Object spread","func":"const obj1 = { \n    banana: { edible: true }\n}\n\nconst obj2 = {\n    brick: { edible: false }\n}\n\nlet mergedObj = { ...obj1, ...obj2 }\n\nreturn { payload: mergedObj }","outputs":1,"noerr":4,"x":420,"y":280,"wires":[["d6eeca22.6a3ba8"]]},{"id":"d6eeca22.6a3ba8","type":"debug","z":"af7ead90.843a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":600,"y":280,"wires":[]},{"id":"9fdb1aec.cb4678","type":"inject","z":"af7ead90.843a8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":240,"y":280,"wires":[["ce6014db.f6b75"]]}]

More about the Spread syntax:
[MDN Spread Syntax - Stage 4 Proposal (Finished)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals)
[TC39 Proposal](https://github.com/tc39/proposal-object-rest-spread)
[TC39 Process](https://tc39.github.io/process-document/)

### What happens?
Example code produces an error in the editor window and a popup. Although the code runs fine and I'm able to still use it.

![screen shot 2018-11-30 at 4 02 27 am](https://user-images.githubusercontent.com/3699516/49282595-2d0ca100-f455-11e8-8c57-417db07ec0bd.png)
![screen shot 2018-11-30 at 4 02 05 am](https://user-images.githubusercontent.com/3699516/49282611-36960900-f455-11e8-906f-bca71dcd156e.png)
![screen shot 2018-11-30 at 4 03 08 am](https://user-images.githubusercontent.com/3699516/49282621-401f7100-f455-11e8-9b35-9dbdd76ce3e0.png)

### What do you expect to happen?
Nothing. This is valid ES6 syntax.

### Please tell us about your environment:

- [ ] Node-RED version: v0.19.5
- [ ] node.js version: v11.0.0
- [ ] npm version: 6.4.1
- [ ] Platform/OS: MacOS Mojave 10.14
- [ ] Browser: Safari 12.0 (14606.1.36.1.9)

**Comment by knolleary** [comment]
We are limited by the JavaScript linter embedded in the [ace editor](http://ace.c9.io) we use, so don't expect any quick fix here.

Our next release does bring some fixes to how we were handling the linting which was causing some false-positive errors with certain ES6 features. Having now tested the spread syntax with those fixes, it generates warnings rather than errors. That is an improvement as it won't get flagged when you deploy, but obviously not a complete solution.

The long term answer is to update the linter inside ACE, however there have been open issues for that against them for years that have not been touched.

**Comment by bugs181** [comment]
The next release would sure be an improvement. I can handle warnings however as per our forum post on user experience, this is one of those times where the popup is a hinderance causing a bad user experience. Not at all Node-RED's fault in addition to what we want the intended behavior to be.

**Comment by ristomatti** [comment]
There seems to be a PR open to upgrade jshint to 2.11.0 for ace editor: https://github.com/ajaxorg/ace/pull/4240

The issue should be fixed on jshint 2.10.0 according to this thread: https://github.com/jshint/jshint/issues/2991

Hopefully this will eventually result in it being fixed for Node-RED also. This issue is really quite annoying if you've got used to using this syntax for years on JS projects. :slightly_smiling_face:

**Comment by knolleary** [comment]
@ristomatti I spotted that issue the other day when I went looking to see where ACE was with updating their ES6 support. I hope it gets some traction soon.

**Comment by tnrich** [comment]
Yep, also seeing this issue.. Maybe switch out the ace editor for something with more modern js support?

**Comment by knolleary** [comment]
The problem with switching it out is that it is a common component exposed by the Node-RED Editor and available for other nodes to use.

Some work has been done in the community to experiment with replacing it with monaco, whilst maintaining API compatibility with what Node-RED exposes. That hasn't resulted in a PR we can work with yet.

On the plus side, I see ACE has published its 1.4.12 version which includes the PR @ristomatti links to. So we should look at upgrading to that in the short term.

**Comment by knolleary** [comment]
I've now updated the version of ACE to its latest 1.4.12 build and verified the object spread syntax is now correctly parsed.

This will be available in 1.2

**Comment by tnrich** [comment]
@knolleary awesome to hear that! Thanks!
