### ISSUE TITLE
Cannot Subscribe to MQTT topic on api.emitter.io server

### ISSUE THREAD

**Issue by ecolasanto** [node-red/node-red#2018]
### What are the steps to reproduce?

I have created a simple flow which contains two sequences. One to send text to a specific mqtt topic on the mqtt://api.emitter.io:8080 server. Another which subscribes to this topic in either a generic or specific way using the syntax <user key>/Home/#/  or <user key>/Home/MA/Main/Sensor/Temp/ and passes the returned results into the debug node. Note this server requires a topic that has a specific syntax which includes a user key. This works great when sending mqtt messages from node-red to the emitter server but I cannot see any response in the debug area from emitter after I subscribe.

I have setup a mosquitto_sub session in a terminal on the Raspberry Pi via:
mosquitto_sub -d -h api.emitter.io -p 8080 -t 4qvhHk6Atzk2hCkQcfi7n2GuJil9w3bs/Home/MA/Main/Sensor/Temp/

The mosquitto_sub is receiving the mqtt messages just fine.
I also have the MQTTool running on my iPhone and see the temp posted there too.

The flow I am using is:

[{"id":"f1e33237.f33cc","type":"tab","label":"Basic MQTT Test","disabled":false,"info":""},{"id":"e6f61deb.70ad8","type":"mqtt in","z":"f1e33237.f33cc","name":"","topic":"4qvhHk6Atzk2hCkQcfi7n2GuJil9w3bs/Home/MA/Main/Sensor/Temp/","qos":"0","broker":"a3815803.b22de8","x":341,"y":366,"wires":[["7abdc351.a1bf3c"]]},{"id":"7abdc351.a1bf3c","type":"debug","z":"f1e33237.f33cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":681,"y":363,"wires":[]},{"id":"50d3b1e4.64793","type":"inject","z":"f1e33237.f33cc","name":"","topic":"4qvhHk6Atzk2hCkQcfi7n2GuJil9w3bs/Home/MA/Main/Sensor/Temp/","payload":"88.0 Deg F","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":119,"y":108,"wires":[["9d97c3a5.30b45"]]},{"id":"9d97c3a5.30b45","type":"mqtt out","z":"f1e33237.f33cc","name":"","topic":"","qos":"","retain":"","broker":"a3815803.b22de8","x":499,"y":110,"wires":[]},{"id":"a3815803.b22de8","type":"mqtt-broker","z":"","name":"Emitter","broker":"mqtt://api.emitter.io:8080","port":"","clientid":"","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]

Note: I can publish and subscribe just fine to mqtt://iot.eclipse.org:1883 which does not require a topic prefaced by a user key.

### What happens?
No debug message displayed.

### Please tell us about your environment:

- [ ] Node-RED version:
v10.14.2
commit 7b80ae42e1cb38bd9c57e5dc9518ccd499672c48
Author: Nick O'Leary <nick.oleary@gmail.com>
Date:   Thu Dec 6 19:20:43 2018 +0530
- [ ] node.js version:
- [ ] npm version:
6.5.0
- [ ] Platform/OS:
Raspberry Pi 3B+
Raspian
- [ ] Browser:
Chrome

**Comment by knolleary** [comment]
Hi, you've already asked this in the forum, so we're unlikely to provide any different help here. I note you say you are using Node-RED 0.14.2 (which is very old) but the commit is from earlier this month... so which is it?

**Comment by knolleary** [comment]
I've just caught up on the forum and I see where Colin suggested you raise an issue.

Can't say when I'll look at this due to being on holiday. Otherwise, continue in the forum where the community can help.

**Comment by knolleary** [comment]
Ok, so I happened to find 5 minutes to get the laptop out.

The Emitter.io service takes an unusual approach to topics and security. You have to subscribe with a key prepended to the topic you want to subscribe to.

    4qvhHk6Atzk2hCkQcfi7n2GuJil9w3bs/Home/MA/Main/Sensor/Temp/

But when the client receives a message, the topic on the message no longer has the key prepended:

    Home/MA/Main/Sensor/Temp/

This is what prevents the MQTT nodes from 'seeing' the messages. When a message arrives in Node-RED, it looks for any MQTT In nodes that have a matching topic string and passes the message to those nodes. In this instance, because of the prepended key, none of the MQTT In nodes match.

If you add a second MQTT In node subscribed to `Home/MA/Main/Sensor/Temp/` you will see *it* receives the message - however it also emits an message from emitter.io containing an error because there's no key in the topic.

This is a limitation of the MQTT nodes. The protocol doesn't have anyway other than the topic string to associate a message with a subscription. There is no way we can know the `Home/MA/...` message is destined for the `4qvhHk6Atzk2hCkQcfi7n2GuJil9w3bs/Home/MA/..` node.

**Comment by knolleary** [comment]
Given all of the above, there isn't a change we can make to the mqtt nodes to accommodate this unusual behaviour of emitter.io. Going to close this issue.
