### ISSUE TITLE
Cannot find "file in" node on IBM Cloud Node Red

### ISSUE THREAD

**Issue by msdorachua** [node-red/node-red#2027]
Hi

Is this intentional? 

I found this tutorial (https://cookbook.nodered.org/http/serve-a-local-file) which shows how to read inputs from a local file using "File In" node, but I cannot find this node in my IBM Cloud Node-Red app.

Screenshot to show the missing "File In" node
https://snag.gy/fEmkA2.jpg

**Comment by hardillb** [comment]
As stated in the template you deleted and in the Contribution guide, please ask general usage questions like this on the forum, in Slack or on StackOverflow, issues are kept for actual code problems.

Yes this is intentional, as normally you should not normally be using the file system within IBM Cloud apps. The filesystem only includes the code for the app and anything else you try and store there will be lost when ever the platform decides to restage your application on another machine or if you scale to multiple instances each will have a separate independent copy of the app. This is why things like the Node-RED flow are stored in the Cloudant database instance attached to the app.

If you are just serving static files then you can just placed them in the directory in the `httpStatic` property in the bluemix-settings.js file.

If you REALLY need the file-in node you can re-enable it by editing the `nodesExcludes` entry in the bluemix-settings.js file and removing the `50-file.js` entry

**Comment by knolleary** [comment]
Thanks @hardillb.

@msdorachua hope that answers your question. If you have any further questions, please do follow up on the [forum](https://discourse.nodered.org) - there's a large user community who can definitely help!
