### ISSUE TITLE
odd node.status behaviour

### ISSUE THREAD

**Issue by anthrogan** [node-red/node-red#2028]
Not a huge issue but threw me off for a little bit! Also to add awareness if it happens to anyone else comes across it.

node.status text returns object instead of the work 'debug'

> key 'node-red:debug (en-US)' returned an object instead of string

### What are the steps to reproduce?
Add a function node with a node.status change.
```
let stats = {
    fill: "red", 
    shape:"dot", 
    text: "debug"
}

node.status(stats)
return msg;
```

### What happens?
when using the word 'debug' it returns an object
![image](https://user-images.githubusercontent.com/30973884/51191184-cb58a700-18db-11e9-9878-b5a3b46fc652.png)

### What do you expect to happen?
the word debug to be shown in the status text

### Please tell us about your environment:

- [ ] Node-RED version: 19.5
- [ ] node.js version: 8
- [ ] npm version:
- [ ] Platform/OS: linux (container)
- [ ] Browser: chrome

**Comment by knolleary** [comment]
The editor checks to see if the status text is actually an identifier from the message catalog so it can provide text in the appropriate language. There is an edge case where the status text is a valid part of an identifier. `debug` is just such an edge case - https://github.com/node-red/node-red/blob/master/nodes/core/locales/en-US/messages.json#L104

So rather than a valid message, it's returning an object from the message catalog - hence the error that is seen.

This should be handled properly and fallback to the provided text as-is in this case.
