### ISSUE TITLE
"projects" popup opening

### ISSUE THREAD

**Issue by serbasii** [node-red/node-red#2084]
After "projects" enabled as true, when loading page, since I do not create a project, a popup appears. How can i prevent this pop-up?

**Comment by knolleary** [comment]
@serbasii the issue template you were shown when raising this asks for general questions to be asked on the forum or slack. We don't use the issue list for questions. Please keep that in mind for the future.

The pop-up appears because you have enabled projects and don't have an active project.  The pop-up helps you create your first project. 

What do you want the editor to do instead? If you have enabled projects it expects you to want to create a project - no say 'no thanks' and create one later.

**Comment by serbasii** [comment]
actuallly make sense but I would like to use when I need and I have a place where I can do it 
"projects -> new" in menu.

**Comment by knolleary** [comment]
If you have enabled projects, the assumption is you want to use projects. If you don't want to use them right now, disable the feature in your settings file. When you're ready to start using them, turn it back on.
