### ISSUE TITLE
Cntrl + Enter not saving node configuration

### ISSUE THREAD

**Issue by machadotiago** [node-red/node-red#2097]
### What are the steps to reproduce?
-Drop the inject node
-Open the inject node configuration
-Change the payload type to an empty String
-Click "done"
-Open the inject node configuration again
-Type some content in the "payload" field
-Press Cntrl+Enter

### What happens?
-The content typed at the payload field is not saved

### What do you expect to happen?
-The content should be saved like when you hit the "done" button

### Please tell us about your environment:

- [ ] Node-RED version: 20.0
- [ ] node.js version: 10.15.3
- [ ] npm version: 6.4.1
- [ ] Platform/OS:Raspbian
- [ ] Browser:Chrome

**Comment by knolleary** [comment]
Yeah, I'm aware of this one.

The problem occurs when you modify the TypedInput and close the dialog with the keyboard shortcut because the TypedInput never loses focus before it gets removed from the DOM.

Clicking or tabbing to another input in the form before hitting Ctrl-Enter will ensure the value is saved.
