### ISSUE TITLE
Using a process env var as a subflow env var generates an error

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#2099]
### What are the steps to reproduce?
See flow below.
### What happens?
When creating a subflow and defining a subflow env var that is also a process env var (say USER) if I attempt to populate the field with the actual env var USER I get an error. See screenshot and example flow.

### What do you expect to happen?
I expect the subflow to reflect the upstream env var passed.
### Please tell us about your environment:

- [ ] Node-RED version: 0.20.2
- [ ] node.js version: 8.15
- [ ] npm version: 6
- [ ] Platform/OS: Mac OS
- [ ] Browser: Safari

[img](https://www.dropbox.com/s/ld33jut3fci16yr/nr_env_error.png?dl=0)

```
[{"id":"e2207b44.81a8b8","type":"subflow","name":"USER","info":"","category":"","in":[{"x":360,"y":100,"wires":[{"id":"157823d1.23a814"}]}],"out":[{"x":740,"y":100,"wires":[{"id":"157823d1.23a814","port":0}]}],"env":[{"name":"USER","type":"str","value":""}]},{"id":"157823d1.23a814","type":"change","z":"e2207b44.81a8b8","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"USER","tot":"env"}],"action":"","property":"","from":"","to":"","reg":false,"x":520,"y":100,"wires":[[]]},{"id":"39939fbc.9163f8","type":"subflow:e2207b44.81a8b8","z":"c76e8bdc.fefde","name":"","env":[{"name":"USER","type":"env","value":"USER"}],"x":620,"y":240,"wires":[["457912c2.390104"]]},{"id":"23eacf58.8879d8","type":"inject","z":"c76e8bdc.fefde","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":460,"y":240,"wires":[["39939fbc.9163f8"]]},{"id":"457912c2.390104","type":"debug","z":"c76e8bdc.fefde","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":790,"y":240,"wires":[]}]
```

**Comment by knolleary** [comment]
The cause here is you are defining the property `USER` to be the value of the property `USER`. So it looks up what `USER` is defined as in the subflow and finds its the value of `USER`, so it looks up what `USER` is defined as in the subflow and finds its the value of `USER`, so it looks up what `USER` is defined as in the subflow and finds its the value of `USER`, so it looks up what `USER` is defined as in the subflow and finds its the value of `USER`, so it looks up what `USER` is defined as in the subflow and finds its the value of `USER`, so it looks up what `USER` is defined as in the subflow and finds its the value of `USER`,
.... 
RangeError: Maximum call stack size exceeded.

---

There isn't necessarily an obvious or easy fix here.

One option would be, if we find we need to look up the value of a property when setting a property of the same name, we skip straight to the parent object to avoid the loop. That would fix this one case, but we'd get the same problem if you created a config with property A defined as the value of property B which is defined as the value of property A - ie an indirect circular reference.

The tricky part is the code which does the eventual lookup of an env var does not know the name of the property that triggered the lookup - so we'd need to do something higher up the stack to spot it.

There is also the consideration that an `env` value in a TypedInput can be a composite of env vars. For example:

<img width="469" alt="Local_Node-RED" src="https://user-images.githubusercontent.com/51083/54679420-1fac1d00-4aff-11e9-99e6-76275799f5c4.png">

We'd need to detect in each of these cases where `USER` needed to be looked-up in the parent env - and in the last example, know that `FOO` needed to be looked up in the current env. That's a particularly nasty case, because we can't skip straight to the parent - we have to do a mixture of current- and parent-env lookup.

To make that work, at the point in the code that can spot the potential loop, rewrite the value to `${FOO}${$parent.USER}` so the code doing the lookup knows to go straight to the parent for that one property. The choice of `$parent` is for the sake of consistency with parent context access - but we wouldn't necessarily expect end users to specify $parent themselves (although they could).

**Comment by natcl** [comment]
I was expecting this to take longer considering your explanation but that was lightning fast !
Thanks :)
