### ISSUE TITLE
function flow semicolon problem

### ISSUE THREAD

**Issue by mdimai666** [node-red/node-red#2107]
### problem
When there is no **semicolon** at the end, an error occurs
`var require = global.get('require')`
`var app = global.get('app')`

**Error**
`"TypeError: global.get(...) is not a function"`

[screenshot .png](https://1drv.ms/u/s!AiQ0R8AtdeYtg5IUkmYbs6j_FTu2bQ)

When there is a semicolon, there is no error

* old version work correctly v0.19.4

### suggest
I think editor minify the js code.

### environment:

- [ ] Node-RED version: 0.20.3
- [ ] node.js version: 8.11
- [ ] npm version: 6.7.0
- [ ] Platform/OS: windows 10 x64
- [ ] Browser: Chrome 74

**Comment by knolleary** [comment]
The problem is caused by the `async` block you have following the last `global.get` statement.
```
var app = global.get('app')

(async() => { } )();
```

Without the semicolon, node is interpreting that as:
```
var app = global.get('app')(async() => { } )();
```

In other words, the `()` around the async block are being interpreted as a function call to whatever `global.get('app')` returns.

With the semicolon, the interpreter understands they are separate blocks.

This isn't a bug. It's JavaScript and why semicolons are sometimes needed.

**Comment by knolleary** [comment]
Just to add, I've tested the code on both 0.19.4 and 0.20.3 - they both interpret the missing semicolon in the same way and log the error.

**Comment by mdimai666** [comment]
Thanks =)

I’ve been writing for so many years, but I’ve encountered such a problem for the first time. 
Tested, really like this: (async()=>{})()
I thought the problem was Ace editor
