### ISSUE TITLE
HTTP Listener : can not backup /restore msg.res since V20

### ISSUE THREAD

**Issue by Sawnd** [node-red/node-red#2124]
### What are the steps to reproduce?
I'm trying to copy "res" property from my msg on an HTTP Listener I've created a simple Function node which copies the property into an other one. (Pic 1 and 2) 

### What happens?
The copy fails with a TypeError exception : 
"TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'". It worked on  NodeRed V19+ nodejs v8

I've tried with a "move" action from the "change" node but it fails : the property is copied but as soon  as I have a function later in the flow it dissapears (really weird ... ).  

### Please tell us about your environment:

- [X] Node-RED version: V20.3
- [x] node.js version: V10
- [X] npm version: node red official docker image
- [X] Platform/OS: CentOS
- [X] Browser: Chrome

![Pic 1](https://user-images.githubusercontent.com/23497318/55389063-cdbeba80-5534-11e9-88ba-4e947836bb58.PNG)
![Pic 2](https://user-images.githubusercontent.com/23497318/55389062-cdbeba80-5534-11e9-936a-48c892e51ce4.PNG)
![Pic 3](https://user-images.githubusercontent.com/23497318/55389516-b502d480-5535-11e9-8cf5-19324d1069e7.PNG)

**Comment by knolleary** [comment]
The `msg.req` and `msg.res` properties are the raw request/response objects from the http request. We have special code in place to handle them whenever a message has to be cloned - as those objects are cannot be cloned. If you copy/move them to another property, that special code won't work and you'll hit an error when we try to clone the message.

Note this only happens when we clone a message - and we only clone messages when a flow branches. So in your example flow above, you will get the error because the flow branches after the Function node. If you deleted the Debug node, so there was only one path from end to end, we would not clone the message and it would not hit the error.

This has not changed.  When running your flow in 0.19, the error message is slightly different but still there: 

```
TypeError: Cannot set property listening of #<Server> which has only a getter
```
