### ISSUE TITLE
Hide or remove a node

### ISSUE THREAD

**Issue by jdiegosierra** [node-red/node-red#2133]
I'm trying to hide or remove a node in the palette section however I keep seeing it in the editor-client. Maybe is not the correct way to hide a node. How should I do it?

### What are the steps to reproduce?
In ./packages/node_modules/@node-red/editor-client/src/js/red.js
I add:
```
        RED.palette.init();
        RED.palette.hide('switch');
        RED.palette.refresh();
        //or RED.events.emit("registry:node-type-removed","switch");
```

- Node-RED version:  0.20.3

**Comment by knolleary** [comment]
What end result do you want to achieve? Is it to hide certain nodes from the palette? If so, you can prevent the runtime from loading them altogether using the `nodeExcludes` property in your settings file. You can see how that is used with our IBM Cloud image here: https://github.com/ibmets/node-red-bluemix-starter/blob/master/bluemix-settings.js#L47

The code you have won't work because calling `hide('switch')` at that point in time won't do anything because the `switch` node type hasn't been loaded yet.

**Comment by ericzon** [comment]
Thanks @knolleary , btw, the key that works is node**s**Excludes (it was a typo in your comment)
