### ISSUE TITLE
postgres node should have configuration support to accomodate key and certificate

### ISSUE THREAD

**Issue by prasaddp5** [node-red/node-red#2139]
I need to connect to my postgres database with postgres using certificate and key.
Something like this.
psql -U postgres -h 10.x.x.x "sslmode=require sslcert=/test/secure/x509/certs/postgres.cert sslkey=/test/secure/x509/keys/postgres.key.pem"  

I donot know if current postgres node has this capablity? 
How can I achieve this capability using node-red postgres node.
If not, can we get this configuration supported to pass certificate and key values.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. The issue template you have ignored describes our contribution process. This repo is for the core of node-red, not 3rd-party nodes.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
As per the template you have deleted please raise requests and ideas for enhancements via the discourse forum or slack channels (links in the template).

Which node is this referring to ? As it is not one of the nodes in the core of Node-RED this is not the issue list it should be reported on. Please raise the issue on the appropriate git project - or ask on the discourse forum for guidance where that may be.

**Comment by prasaddp5** [comment]
Thanks for the quick response, its referring to node-red.
I am using postgres node to connect to my postgres database using certificate and key.
Nodered version used is v.0.20.5.

**Comment by knolleary** [comment]
Just to be clear - this is not the right place to get support on this issue. Please use the links I provided above.
