### ISSUE TITLE
Status of Design Flow testing

### ISSUE THREAD

**Issue by jbinard** [node-red/node-red#2180]
Hi,

What is the status of the Design Flow Testing page ? (https://github.com/node-red/node-red/wiki/Flow-testing).

Our team is very interested by this feature but it's not listed in the Design Notes page (https://github.com/node-red/node-red/wiki/Design-Notes) or in the designs git repository (https://github.com/node-red/designs)

**Comment by knolleary** [comment]
Please use the issue template. General questions should be directed to the forum or slack.

**Comment by knolleary** [comment]
This design is being looked at by our contributors from Hitachi. I have not had any update from them for some time. Once we've got 1.0 out the way, it will be something I'll be pushing to get progress on

**Comment by knolleary** [comment]
Just one correction, there is a PR to migrate the Flow testing design over to the design repo - https://github.com/node-red/designs/pull/8. It hasn't been merged yet which is why you couldn't see it in there.

The original Flow Testing wiki page had not been reviewed; this PR is awaiting a proper review before we merge it.
