### ISSUE TITLE
Bump mqtt dependency version due to security vulnerability

### ISSUE THREAD

**Issue by Shaquu** [node-red/node-red#2181]
I just got informed about a security vulnerability in mqtt-packet which is used by current version of mqtt used in this project.

[Here is full description.](https://nvd.nist.gov/vuln/detail/CVE-2019-5432)

Solution is to bump mqtt version to newest (3.0.0 just released).

**Comment by knolleary** [comment]
This vulnerability applies to brokers that use this module for parsing packets.

Node-RED does not provide a broker, only a client. It is not vulnerable.

Upgrading to the latest versions of modules is a routine action as part of our release cycle. Given this is not a vulnerability that is applicable to NR and the update will get picked up as business as usual, I'm closing this issue as there's no specific action to take at this point.

**Comment by knolleary** [comment]
I've looked at this in more detail and there is actually nothing for us to do.

- Node-RED 0.20.5 depends on `mqtt@2.18.8`.
- `mqtt@2.18.8` depends on `mqtt-packet` with a range of `^5.6.0` - which will cover the `5.6.1` release that includes the fix for the issue.


Bumping MQTT from 2.18.8 to 3.0.0 is not necessary - and as that is a major version change, will be more work than the routine updating of dependencies we do for minor/fix level changes.
