### ISSUE TITLE
[Feature Request] a function to auto-arrange nodes in the workspace

### ISSUE THREAD

**Issue by nileio** [node-red/node-red#2200]
Hi guys,
It would be great if we get a function to automatically arrange the nodes in the workspace. It gets missy very quickly with all the nodes and wires in a flow. 
I think any type of tidy up arrangements would be great to have.
It is difficult to keep arranging the nodes manually when you get alot of nodes in the flow and workspace.

I know this may be not a biggy but I thought to add the suggestion as I can't see it anywhere..
Thanks,

**Comment by knolleary** [comment]
If you read the issue template you were given, you will know we don't accept feature requests on the issue list. Please use the forum or slack.

**Comment by nileio** [comment]
frankly speaking @knolleary i have no idea what you keep referring to about the issue template! there are many feature requests already in here, and the issue request template does not say no feature requests. When you click a New Issue, you are presented with two options 1: Bug report 2: Anything else. In Anything else, there is no mention that adding feature requests is not welcomed. Please have a look. in all cases, all good thanks for that, I just thought to add an issue for tracking purposes, this way we can "collectively as a community" consider new features etc. thanks for your help as always. Cheers

**Comment by knolleary** [comment]
@nileio the 'Anything else' template says:

> Please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).
> You could also consider asking a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.
> That way the whole Node-RED user community can help, rather than rely on the core development team.

Ok, it doesn't single out feature requests - but it asks you to use the forum.

The 'bug' issue template is more explicit - it says if your issue is a feature request then to use the forum.

Our main contribution guidelines [say this](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md#feature-requests):

> For feature requests, please raise them on the forum.

We do not track feature requests on the issue list. The particular feature you've raised has been discussed quite a few times on the forum - so it is worth search there for what has already been discussed.
