### ISSUE TITLE
When upgrading to module watson-developer-cloud":"4.x"

### ISSUE THREAD

**Issue by dennisnotojr** [node-red/node-red#2209]
When upgrading the npm for IBM watson from watson-developer-cloud 3.x  to 4.x the function in settings : watson:require('/usr/src/node-red/node_modules/watson-developer-cloud') is no longer found and node red aborts.

I have tested NodeRed releases 18.7, 19.6, 20.5 with 3.x and module is found.  When upgrading 4.x in the package.json, nodered no longer finds the module. This also fails for the new watson package ibm-watson 4.x.   

I suppose IBM is doing something different that maybe causing nodered and/or nodejs not to find the module at runtime.  Module installs find via npm install command from the docker container and can be found in the /usr/src/node-red/node_modules directory.

To produce
Put in the package.json and build the node-red docker container:
   watson-developer-cloud":"3.x"
Put in the settings.js 
   watson:require('/usr/src/node-red/node_modules/watson-developer-cloud')

This works!

Change package.json "4.x" and rebuild container

Run will fail with:
 
Error loading settings file: /data/settings.js
Error: Cannot find module '/usr/src/node-red/node_modules/watson-developer-cloud'

**Comment by knolleary** [comment]
Hi - please use the issue template you are shown when raising an issue. It saves time for everyone.

This issue tracker is for the core of node-red, not debugging issues with 3rd party modules. Please use the forum for issues like this in the future.

What version of node.js are you using?

A [quick look at that module](https://github.com/watson-developer-cloud/node-sdk/releases/tag/v4.0.0) shows the major change from 3.x to 4.x was their move to use native promises and they no longer support Node.js 4.x. If your container is still based on Node 4 then that would certainly explain the issue. Also note that Node-RED 0.20 doesn't support Node 4.x either.

I also note that `watson-developer-cloud` has been deprecated and you should be using `ibm-watson`.

**Comment by dennisnotojr** [comment]
Using nodes 9 and tested 10 as well.  The issue is either nodered or Watson npm

Thanks Den

**Comment by knolleary** [comment]
Why are you requiring it with the full path to the module `/usr/src/node-red/node_modules/watson-developer-cloud` and not installing it relative to your settings file as you would normally do and just `require('watson-developer-cloud')`?

**Comment by dennisnotojr** [comment]
Because I fully qualify configs.  I have been using nodered configuration for years without any issues. 

The issue is either nodered or the Watson npm.  

I gave you a way to reproduce. Please test it your self to see that it fails.  It’s really easy to reproduce.

Thanks, Den

**Comment by knolleary** [comment]
This issue list is not for us to debug 3rd party modules. The only thing that has changed here is the version of the watson-developer-cloud module you are trying to use. Node-RED has not changed. The module you are trying to use has changed. This is not a node-red issue.

I can confirm I can reproduce the issue.

But I also just installed `watson-developer-cloud` locally, completely outside of anything to do with node-red and I get the same error when I try to require the module:
```
[/tmp/h]$ npm install watson-developer-cloud
[ ... edited the full install log for brevity ... ]
+ watson-developer-cloud@4.0.1
[/tmp/h]$ node
> require('watson-developer-cloud')
Error: Cannot find module 'watson-developer-cloud'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

> require('/tmp/h/node_modules/watson-developer-cloud')
Error: Cannot find module '/tmp/h/node_modules/watson-developer-cloud'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

I also tried the same with the `ibm-watson` module that replaces `watson-developer-cloud` - and get the same error.

[A quick look at the module's package.json](https://github.com/watson-developer-cloud/node-sdk/blob/master/package.json) file shows it does not define a `main` property - so it cannot be required.

The 3.x version of the module does have a `main` property which is why it can be imported.

So, despite saying we don't debug 3rd party modules, I've now spent 20 minutes to show there is no node-red issue here. The module can no longer be required directly. I assume it intends you to require the different service sdks it contains. But that's for you and the module's documentation to figure out.

**Comment by dennisnotojr** [comment]
Thank you.

**Comment by dennisnotojr** [comment]
Nick,

 

Thanks so much for your help. Actually I did get ibm-watson 4.x to work and this may be helpful for all nodered users.

 

By placing this in the package.json and building the docker container

 

"ibm-watson":"4.x",

 

By specifying in the settings the actual Watson function call(I will use the assistant for example)

 

watson_asst_v2:require('/usr/src/node-red/node_modules/ibm-watson/assistant/v2'),

watson_asst_v1:require('/usr/src/node-red/node_modules/ibm-watson/assistant/v1'),

 

and in a function node:

 

var watson_asst_v1 = global.get('watson_asst_v1');

 

var conversation = new watson_asst_v1({

  username : msg.params.username,

  password : msg.params.password,

  workspace_id : msg.params.workspace_id,

  url : msg.params.endpoint,

  version: '2018-02-16'

});

var conversation = new watson_asst_v1({ ……

 

Working again! 

 

Big fan, of NodeRed.  Been using it for years when I was at IBM, now as CTO of GetSwift, plan on using it in our platform.  Go Broncos, Thanks, Dennis
