### ISSUE TITLE
Upgrading nodered forces nodejs to upgrade too

### ISSUE THREAD

**Issue by gabrielcbe** [node-red/node-red#2230]
### What are the steps to reproduce?
After downgrading node v10 to node v8 (installed from nodesource) on a Raspbian Buster with desktop and recommended software trying to upgrade nodered from 0.20.5 to 0.20.7-1 (apt install nodered) or from the script in https://nodered.org/docs/getting-started/raspberrypi

### What happens?
Upgrading nodered forces nodejs to upgrade from v8.* to v10.*

Further info: I need Nodejs to be on v8 to ensure compatibility with other packages (e.g. Sphero, bbc-microbit ...)

### What do you expect to happen?
Upgrading nodered without it forcing upgrade nodejs to v10.*

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.5
- [ ] node.js version: 8.16.0-1nodesource1
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Raspbian GNU/Linux 10 (buster)
- [ ] Browser: Chromium-browser 74.0.3729.157

**Comment by dceejay** [comment]
if you use apt you will get what buster repo provides. That is Node10. That is what debian/raspbian provide.
You can either go back to stretch. Or not use apt, and manually install nodejs yourself (as you had). Our install script from the docs, would then install Node-RED but leave node8 installed.

In future please use the discourse forum or our slack channel for general help, rather than the issues list - so that the widest audience can help an assist.
