### ISSUE TITLE
Function node does not clone messages

### ISSUE THREAD

**Issue by SynAckFin** [node-red/node-red#2329]
Version >= 1.0
File: [10-function.js](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/function/10-function.js)
The documentation states that:

> The Function node will clone every message object you pass to node.send to ensure there is no unintended modification of message objects that get reused in the function. Before Node-RED 1.0, the Function node would not clone the first message passed to node.send, but would clone the rest.

The function `sendResults` has the following piece of code:
```
                            if (msgCount === 0 && cloneFirstMessage !== false) {
                                msgs[m][n] = RED.util.cloneMessage(msgs[m][n]);
                                msg = msgs[m][n];
                            }
                            msg._msgid = _msgid;
                            msgCount++;

```
The `if` statement means that only the first message can be cloned because `msgCount` will be none zero for the others.
I think the `if` statement should be:
```
                            if (msgCount !== 0 || cloneFirstMessage !== false) {
```

**Comment by knolleary** [comment]
Hi @SynAckFin ,

are you raising this because you have observed some behaviour and have then looked at the code? If so, can you please provide an example flow that demonstrates the issue?

I have to ask because there is nothing wrong with the code you've highlighted here.

The `sendResults` function prepares the messages before passing them to the `Node.send` function. `Node.send` is the function used by all nodes to pass messages. It does not clone the first message it is given, but does clone all of the rest.

So for the Function node to clone all of the messages it is given before sending, the `sendResults` function only needs to clone the first one as all of the others will be dealt with by the `Node.send` function.

**Comment by SynAckFin** [comment]
I was looking at it because I want to rewrite the "File Function" node so that it works exactly the same as the function node.

I didn't realise the message cloning was performed by `Node.send` .

**Comment by dceejay** [comment]
So what is the issue with the file node ?

**Comment by knolleary** [comment]
Ah ok - all good then and I'll close this issue.

If you do have any other questions, do come talk to us in #dev on https://nodered.org/slack

👍

**Comment by SynAckFin** [comment]
The "File Function" doesn't have the context, flow, global, or env functionality. It also doesn't have setTimeout, clearTimeout, setInterval ot clearInterval.
