### ISSUE TITLE
Importing a flow that includes Japanese from the library is garbled (文字化け).

### ISSUE THREAD

**Issue by utaani** [node-red/node-red#2391]
### What are the steps to reproduce?
sample flow
https://gist.github.com/utaani/52966e681e3b7911d0238a191c919299

First load the sample flow from the file. 
(Currently, it is not garbled.)
After that, if you export to the library and import again.

### What happens?
Some nodes are garbled.

![mojibake](https://user-images.githubusercontent.com/17796/69469617-20efc100-0dd5-11ea-88f3-ad4bc10a5f45.png)

### What do you expect to happen?
It is reproduced as it is without being garbled.

### Please tell us about your environment:
- [ ] Node-RED version: 1.0.3
- [ ] Node.js version: 10.16.3
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Debian 9 amd64
- [ ] Browser: Chrome 78.0.3904.108 windows 10 64bits

**Comment by okhiroyuki** [comment]
this is because the library file is read separately and cannot be encoded well.

https://github.com/node-red/node-red/blob/a4c351fd4f4114d11f516b40c5c0d770b7c087e5/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/library.js#L57-L94

After reading the files in a batch, processing them will not cause any problems.
This issue was Pull Requested #2401 

```js
function getFileBody(root,path) {
    var body = "";
    var fn = fspath.join(root,path);
    var data = fs.readFileSync(fn,'utf8');
    var parts = data.split("\n");

    parts.forEach((part) => {
        if (! /^\/\/ \w+: /.test(part)) {
            body += (body.length > 0?"\n":"")+ part;
        }
    });
    return body;
}
```

**Comment by utaani** [comment]
Thank you @okhiroyuki san!  I tried the PR patch and confirmed that there was no garbled character even if the Flow was imported from the library.
