### ISSUE TITLE
Errors in subflows are difficult to trace (still)

### ISSUE THREAD

**Issue by jacomahalatime** [node-red/node-red#2422]
I know this has been addressed in https://github.com/node-red/node-red/issues/1698, however this is still a major issue for large scale API projects. 

To recap, error msgs regarding subflows would show and id  the error. When it is 1 level deep, you will be able to click on the link and you will be navigated to the subflow entry node. This is acceptable, but when it is more than 1 level deep (in other words a subflow within a subflow) you are unable to click on the error.

If you could at least get the first level again, or if you could search the node id displayed it would be a huge step forward.

Thank you !

**Comment by knolleary** [comment]
Hi @jacomahalatime - thanks for raising this issue. Yes this is something we are aware of that needs addressing. We don't yet have a plan for how to tackle it however.

In future, please use the issue template we provide, even if you think you don't need to. It helps to ensure enough information is provided with issues, but also points you at the forum/slack for more general discussion type issues rather than specific issues.

**Comment by jacomahalatime** [comment]
My apologies, will use the template in the future.

Thank you for the reply, as long as you are aware :-)
