### ISSUE TITLE
Debug Node sends when deactivated

### ISSUE THREAD

**Issue by kelke** [node-red/node-red#2432]
### What are the steps to reproduce?
1. Place Debug Node while it is deactivated.
2. Deploy
3. activate Debug Node, **dont** deploy.
4. Ctrl+Z deactivates Debug Node

### What happens?
Debug Node sends incoming msgs to Debug window.

### What do you expect to happen?
No msg to Debug window.
(I love the feature that you can activate a Debug Node without Deploying, makes Debugging on big projects way easier, but when you Ctrl+Z it and still get messages it gets confusing real fast)

### Please tell us about your environment:
Tested on:
Debian GNU/Linux 9.11 (stretch)
Raspbian GNU/Linux 10 (buster)
Windows 10

- [10.0.3] Node-RED version:
- [12.13.1] Node.js version:
- [6.13.1] npm version:
- [Debian/Windows] Platform/OS:
- [Chrome] Browser:

**Comment by knolleary** [comment]
This is one of those lingering issues I've been aware of for a long time, but in absence of a quick fix, have left alone until someone raised it.

The underlying reason for this is that act of clicking the button does two things - it modifies the node's property (which gets put on the undo-history stack) as well as send an HTTP request to the runtime to (de)activate the node.

The undo framework in the editor only knows how to revert a node's properties - it doesn't have anyway to trigger node-specific side-effects such as sending the http request to (de)activate the node.

The fix for this will require some way of attaching custom callback events onto the events that are placed into the history stack (for both undo and redo).

**Comment by knolleary** [comment]
This has now been fixed in the `dev` branch for 1.1.0. It adds the ability for a history event to have a callback that is triggered when the event is undone.
