### ISSUE TITLE
UI freezes with loops in functions

### ISSUE THREAD

**Issue by haniham** [node-red/node-red#2437]
### What are the steps to reproduce?
Make a funtion node with an non stopping while in it. Create an Inject node which continously triggers it within 5 s

### What happens?
The UI can't be accessed wia web anymore, especially to stop the inject, disable anything function, ...
### What do you expect to happen?
The UI should be responsible to be able to stop the crappy code the author firstly has implemented
### Please tell us about your environment:

- [x] Node-RED version: v0.20.7
- [x] Node.js version: v8.16.1
- [x] npm version: 6.4.1
- [x] Platform/OS: Ubuntu Ubuntu 18.04.3 LTS
- [x] Browser: Firefox 72.0.2

My solution was to read the flows_<PCNAME>.json file and set the "repeat" property of the corresponding inject node to "" which disabled it.

**Comment by dceejay** [comment]
If the author was responsible enough to read the basic docs, instead of writing crappy code - they could find out about options like safe mode - eg https://nodered.org/docs/getting-started/local#command-line-usage which would allow them to restart Node-RED without the flow running - allowing them to fix the mistake before re-deploying.

node.js is single threaded - so all the processing of both runtime and the editor is on the same thread. If the user locks it up then the UI itself cant get a look in and has to be stopped externally.

**Comment by knolleary** [comment]
@haniham unfortunately, there are some things that are out of our control. Given the single-threaded nature of node.js there is no way for us to break out of code stuck in a loop. So whilst I completely understand what you mean with the issue, there isn't much we can do about it.

As Dave mentioned, the `--safe` option on the command-line was introduced to help users fix their flows that are stuck in a loop. That's about all we can do.
