### ISSUE TITLE
form autocomplete="disabled" not providing autocomplete="off" behaviour

### ISSUE THREAD

**Issue by ibmrcruicks** [node-red/node-red#2445]
### What are the steps to reproduce?
open any input form for a node with username and/or password, in chrome

### What happens?
if node-red username/password saved for editor, fields will be autocompleted

### What do you expect to happen?
no autocomplete
### Please tell us about your environment:

- [ ] Node-RED version: 
1.0.3
- [ ] Node.js version:
SDK for Node.js(TM) (buildpack-v4.1-20191119-1309)
-----> IBM SDK for Node.js Buildpack v4.1-20191119-1309
              Based on Cloud Foundry Node.js Buildpack 1.7.3
- [ ] npm version:
Using default npm version: 6.12.0
- [ ] Platform/OS:
4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux  (Bluemix)
- [ ] Browser:
Version 79.0.3945.88 (Official Build) (64-bit) (MACOS 10.15.2)

**Comment by knolleary** [comment]
Chrome is notorious for ignoring the standards here and they routinely change behaviour. Since the start of Node-RED, I've had to adapt to their changes at least twice as they try to "improve" the user experience because of course the browser knows better than the author of the form as to when autocomplete is appropriate or not.

**Comment by knolleary** [comment]
Here is the Chrome bug where they are collecting use cases for why autocomplete=off should be honoured - https://bugs.chromium.org/p/chromium/issues/detail?id=587466

480 response over 4 years and yet they still continue to 'know better' then the standards.

**Comment by knolleary** [comment]
From the commit I've just pushed:

Continuing the arms race against Chrome's war on developers getting
to choose if a form should be autocompleted or not.

The honey-pot username/password fields we already had were being
ignored. This is because they were hidden.

This fix does three things:

 - unhides the honey-pot inputs, but moves them offscreen so they won't be seen
 - gives them dummy id's so Chrome thinks they are username/password fields
 - updates our autocomplete setting to be the standards-compliant 'off' for all
  the other browsers who adhere to the standard
