### ISSUE TITLE
Migrate away from request package

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#2481]
The `request` module is now fully deprecated and will no longer receive any fixes.

Its latest published version, 2.88.2, adds a deprecation warning whenever it is npm-installed. On that basis, we'll stick on 2.88.0 for the time being otherwise we'll get needless issues from our end-users.

But it does mean we need a plan to migrate off the request package to something else. I don't yet know what that will be, but this issue gives a good list of potential alternatives: https://github.com/request/request/issues/3143

For more info on the deprecation of request, refer to this issue: https://github.com/request/request/issues/3142

**Comment by dceejay** [comment]
Another comparison list for some of those libs mentioned https://github.com/sindresorhus/got#comparison

**Comment by chughts** [comment]
https://www.npmjs.com/package/axios is currently being used by https://www.npmjs.com/package/ibm-watson

**Comment by johnwalicki** [comment]
I suggest we switch to axios. I ran into some bugs in got on Mac OS X and node.js v10.x 
I switch my nodes to use axios and it seems to be working fine everywhere.
My investigation is posted at
https://github.com/Call-for-Code/node-red-contrib-twc-covid19-tracker/issues/2

**Comment by johnwalicki** [comment]
To scope the migration work, I did a quick scan of the node-red repo:
```
$ grep -r request */package.json
node-red/package.json:        "request": "2.88.0",
```
In the case of node-red core, the migration work is just the HTTP Request node:
```
$ grep -r 'require("request")' | grep .js | more
packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
```

**Comment by boisei0** [comment]
> I suggest we convert to axios. I ran into some bugs in got on Mac OS X and node.js v10.x
> I migrated my nodes to use axios and it seems to be working fine everywhere.
> My investigation is posted at
> [Call-for-Code/node-red-contrib-twc-covid19-tracker#2](https://github.com/Call-for-Code/node-red-contrib-twc-covid19-tracker/issues/2)

It took some deep diving, but I found the source of this issue referenced: https://github.com/TooTallNate/node-agent-base/issues/35
`agent-base`@4.x, a dependency of many a library's dependencies, is monkey patching the `https` core of NodeJS. Any package depending on it is cursed with this behaviour too. It got removed from v5, but is still present in a lot of packages. As a result, all urls using `https` are resolved to 127.0.0.1 and hardcoded to use port 443 of it. Which results in the seen `ECONNREFUSED 127.0.0.1:443`. It's certainly messy because of it. Do note that this is not caused by `got`, but by `agent-base` patching NodeJS. The developer of `agent-base` fixed the issue, but released it as major release rather than a minor/bugfix, which means it's not picked up by libraries depending on it. As a result, using `got` is always a risk in nodes as you won't know if any other nodes have a deeply nested dependency somewhere on `agent-base`@4.x. I agree on moving to axios as much as possible.

**Comment by bartbutenaers** [comment]
Hate it to be a party-stopper, but seems [here](https://github.com/axios/axios/issues/686) that Axios doesn't support Digest Authentication (which is needed for the Http-request node). And it doesn't looks like [axios-digest](https://github.com/rearn/axios-digest/issues/1) will be ever merged into Axios...

**Comment by TotallyInformation** [comment]
Looking at the comparison table here: https://github.com/sindresorhus/got#comparison

Looks like sindresorhus's `got` might be the most compatible option. Anyone have any thoughts about that? If I get some time, I might try and do a hack of the request module.

**Comment by boisei0** [comment]
> Looking at the comparison table here: https://github.com/sindresorhus/got#comparison
> 
> Looks like sindresorhus's `got` might be the most compatible option. Anyone have any thoughts about that? If I get some time, I might try and do a hack of the request module.

Yes, I’ve thoughts about it as I found out the hard way why it was a bad idea. See comment a few messages up (https://github.com/node-red/node-red/issues/2481#issuecomment-627021709)
Specifically, agent-base@4.x monkey patches the https functionality in the core nodejs, meaning that if anywhere in your dependency tree something involving it is present, any code relying on core https functions differently. `got` is amazing, but relies on core https. Which shouldn’t be an issue at all, if TooTallNate didn’t release the fix for the monkey patching as a major change, pushed to agent-base@5.0.0. And agent-base being in millions of packages as a dependency deep down the line makes this problematic. 

As such, like I found out, if you have a contrib node using `got`, and just the core node-red you’re running, it moght work flawless. But if a 3rd part contrib node has a deep dependency on agent-base@4.x, your node stops working. Note here that TooTallNate is a former nodejs core dev, and has been very slow in updating his other libraries to use a later version of agent-base, and all those updates come as major version, rather than semantically bug fix releases as they should have been.

**Comment by TotallyInformation** [comment]
But won't that be a problem for all of the options? As I've seen in the past, anything that monkey-patches core or that faffs around with prototypes of core JS is a nasty thing that needs to be avoided at all costs.

A quick check shows that Node-RED itself contains agent-base but at v6. `got` does not use anything that depends on agent-base.

Maybe I'm being thick - if got doesn't use it, it would not itself cause an issue. We can't stop the development of Node-RED because some other node _might_ use an old version of agent-base in the future can we?

**Comment by boisei0** [comment]
I firmly agree with your last statement, but that means compiling a list of current contrib nodes that will be incompatible because somewhere down the line they rely on agent-base@4.x, as using them will turn your core http node unusable if it is based on `got`. Monkey patching the core should be a very frowned upon thing, it having slipped through so many dependencies makes it a bit of an issue. So you can move to `got`, if you either force those nodes to make the move away from libraries they rely on that use agent-base@4.x somewhere, or outright drop compatibility with them. That kind of choice however would be unsuitable for a semantic minor version, and if such a decision is made would be more suitable for the next major version of node-RED.

**Comment by TotallyInformation** [comment]
Agree that we appear to be forced to stick with the current request library then until a major release. Though that isn't too far away now is it?

In theory, it would be possible to make a post-install script that would check for agent-base@4 in the users existing install. That might go some way to lowering the risk a little?

**Comment by boisei0** [comment]
> In theory, it would be possible to make a post-install script that would check for agent-base@4 in the users existing install. That might go some way to lowering the risk a little?

I do have an idea to kinda figure out the impact, but I’ve no idea how feasible that would be. Going to figure that out first before presenting something that might only be an issue in theory.

**Comment by knolleary** [comment]
The plan is to get off `request` one way or another for the 2.0 release in April. I'm still not settled in my mind which package we'll replace it with. None seem a perfect fit - so it's a question of minimising the work needed to bridge the gap.

If we can get a better sense of the true impact of the agent-base issue, that would be helpful.

I also don't know how up to date the comparison table provided by the GOT module is - it's clearly in their interest to make themselves look better. Certainly a useful starting point, but not necessarily the final say on the matter.

**Comment by boisei0** [comment]
> If we can get a better sense of the true impact of the agent-base issue, that would be helpful.

If my neck will stay cooperative for the rest of the evening, I think I can put together a quick prototype to figure out which/how many nodes would be affected by a move to `got`. My neck is a big if, just like how I haven’t programmed anything beyond a couple lines in JavaScript in months. But this sounds doable.

**Comment by TotallyInformation** [comment]
That had occurred to me as well Nick but sindresorhus is a well respected and prolific developer so it has that going for it. I will admit that when I threw together the Wiser heating module recently, I simply reached for the module that most people seem to talk about which was axios but if it is missing a bunch of features that request had, then that could be a problem.

**Comment by boisei0** [comment]
Prototype worked in theory, not in practice, as the library underneath appears to (also) depend on requests, but most of all can't bulldozer its way through this without socket hangups, DNS failures, and timeouts. It works for doing a couple nodes one by one, not pushing the catalogue file through it like I tried here. Package used is `npm-remote-ls`, but someone else might have a better idea. Downloaded the latest catalogue file as input. 

```
const ls = require('npm-remote-ls').ls;
const catalogue = require('./catalogue.json');

catalogue.modules.forEach(function(elem) {
    ls(elem.id, elem.version, true, function(obj) {
        let deps = obj.filter(s => s.includes('agent-base@'));
        //console.log(deps);
        let deps_checked = deps.filter(s => s.split('@')[1].startsWith('4.'));
        //console.log(deps_checked);
        if (deps_checked.length > 0) {
            // This package will be going to run in trouble with `got`. Log it
            console.log(`[+] ${elem.id}@${elem.version}`);
            console.log(`[*] depends on ${deps_checked.join(', ')}`);
            console.log();
        }
    });
});
```
Some packages that will cause the http-node to fail if it depends on `got` are `node-red-contrib-npm` and `node-red-contrib-chatbot`, as I found out earlier this year and just confirmed. But beyond those I wouldn't have too much of a clue. For those, `node-red-contrib-npm` causes issues because `npm` itself depends on agent-base@4.x.
I'm also spotting `node-red-contrib-google-oauth2`, because of the underlying `googleapis` library that has a dependency somewhere on it. 
But, the idea to get this figured out is the same, do a deep check on the dependencies of a package, check if agent-base is in it, specifically for major version 4 which is doing the monkey patching of the core. I checked a couple manually, and a few do, but most so far appear to be steering clear.

**Comment by TotallyInformation** [comment]
https://www.npmjs.com/package/johnny-dependency seems to be similar to npm-remote-ls but is a little newer.

If this analysis can't be done, I still think that there is little choice but to make the change for the next major Node-RED release, warn people and maybe give a script that will run the `npm ls agent-base` command so that people can easily see if they have a dependency that needs fixing. That could be run as a post-install script on Node-RED install.

**Comment by knolleary** [comment]
Having spent a bit more time on this, with 2.0 looming, there's still no easy option here.

The concerns about agent-base aside,`got` does look like the closest match - but there do remain a number of differences that need coding around.

It won't take much to get the basic function of http requests working. But we also have to get all the behaviour to match with handling redirects, cookies, form-data, authentication, proxy support to name just a few.

We don't have a comprehensive test suite for the node that verifies every possible combination of things the node can do. There is a good chance we'll break some edge case and not know it.

**Comment by dceejay** [comment]
Have the agent-base concerns been mitigated by the passage of time and other updates ?

**Comment by boisei0** [comment]
> Have the agent-base concerns been mitigated by the passage of time and other updates ?

Sadly, no it has not. The way it was fixed through a major release rather than bugfix or minor as it really was, means it’s not picked up in versioning updates as easily for simple reasons. As agent-base is a (nested) child dependency of literal millions of packages, there’s a high chance that it might be somewhere in the codebase of a node-red ecosystem that were to use third party nodes.

With the change not being backported as minor/bugfix release on the agent-base package itself, this will continue to be a problem for the future. A potential solution that’s more of a workaround I thought of earlier would be a function that checks for the presence of agent-base of this version in the node-modules and emits a warning. For example, npm itself has agent-base as nested child dependency, but I don’t know from mind which version that was. 

In practice, using `got` as http library works perfectly as long as there’s nothing else loaded in the same ecosystem that has a deep dependency on that offending version of agent-base, as it monkey patches the core nodeJS. So even if your module works fine on its own as well as the system itself, if you were to install a third party node with that dependency somewhere, it’s introducing the issue for all `got` calls that use https based urls. That is how I first encountered the issue myself. My node ran fine on its own, as well as imported in a clean/core install of Node-RED. But as soon as I installed a third party node with a deep dependency on it, my node stopped working with error messages that were of no use in figuring out what the issue was. I would go as far as stating that agent-base with that version is a danger for any code that relies on the core library to be untampered.

**Comment by knolleary** [comment]
I've got an initial PR for migrating to `got`. It isn't complete yet, but it is fairly close.

Even with the amount of features `got` has, it has still been a few days work to get to this point. Moving to pretty much any other library will require significantly more work. I understand the worries about `agent-base` but we are somewhat stuck between a rock and a hard place. We have to move off request. got is very popular and well maintained. I would hope and expect, with the passage of time, the use of the legacy agent-base will fade away.

**Comment by boisei0** [comment]
I certainly understand. In terms of health, I’m sadly unable to work this out on my own, but would it be an idea to have a post install script or function added to the palette install that checks for the offending agent-base version and warns the user? I believe it was previously suggested by @TotallyInformation  further above in this thread as well. I believe users should be made aware that the presence of this dependency on the node/ecosystem they’re using could cause harm for other nodes including the future core http-request node and the like, in that it becomes unable to connect to any addresses with https protocol.

**Comment by knolleary** [comment]
So we have shipped this and sure enough, had a couple reports of issues thanks to old levels of agent-base.

I am adding some code to the request node that detects the patched module and restores the original code. It then displays this warning:
```
---------------------------------------------------------------------
Patched https.request function detected. Restoring original code.
This is likely caused by the 'agent-base@<5.0.0' module that has
been installed as a dependency of a contrib node.

You can identify what node is at fault by running:
   npm list agent-base
in your Node-RED user directory (/Users/nol/.node-red)
---------------------------------------------------------------------
```

(the user dir is inserted dynamically...)

That should keep the core working and help nail down the modules that need updating.

**Comment by knolleary** [comment]
Closing as I think `request` is firmly in our past at this point.
