### ISSUE TITLE
Failed to install Node.js with Bash Script on Raspberry Pi Zero

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [node-red/node-red#2497]
Running [official the bash script ](https://nodered.org/docs/getting-started/raspberrypi)to install Node-Red on a Raspberry Pi zero I got the following error:

  Stop Node-RED                       ✔
  Remove old version of Node-RED      ✔
  Remove old version of Node.js       -
  Leave existing Node.js              ✘   Failed to install Node.js - Exit
  Clean npm cache
  Install Node-RED core
  Move global nodes to local
  Install extra Pi nodes
  Npm rebuild existing nodes
  Add shortcut commands
  Update systemd script

Any errors will be logged to   /var/log/nodered-install.log

```
cat /var/log/nodered-install.log

Running for user pi at /home/pi
Failed to stop nodered.service: Unit nodered.service not loaded.
Found global nodes:   :

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package 'nodered' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Already have nodejs
Now install nodejs

***************************************

Started : Fri 6 Mar 15:10:11 GMT 2020
Running for user pi at /home/pi
Failed to stop nodered.service: Unit nodered.service not loaded.
Found global nodes:   :

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package 'nodered' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Already have nodejs
Now install nodejs
```

**Comment by dceejay** [comment]
can you type `which nodejs` and then `node -v` and see what they return ?

**Comment by mnadvornik** [comment]
I do have the very same problem when using the install script on Ubuntu 20.04 (aarch64 architecture).
It doesn't matter whether npm is installed from the Ubuntu repositories or not prior to running the installer script.
For me it seems like nodejs gets only partially installed since I can read the version using the `node` command but `/usr/bin/npm` does not exist 

```
$ which node
/usr/bin/node
$ node -v
v10.19.0
$ dpkg -l|grep node
ii  libnode64:arm64                  10.19.0~dfsg-3ubuntu1              arm64        evented I/O for V8 javascript - runtime library
rc  node-duplexer3                   0.1.4-5                            all          Like duplexer but using streams3
ii  nodejs                           10.19.0~dfsg-3ubuntu1              arm64        evented I/O for V8 javascript - runtime executable
ii  nodejs-doc                       10.19.0~dfsg-3ubuntu1              all          API documentation for Node.js, the javascript platform
```

I wonder if this is an issue on specific architectures since not many people seem to have this problem

**Comment by dceejay** [comment]
yes - probably... can you remove the "old" nodejs, then install node.js manually from the instructions on the nodejs.org website to get node v12 LTS and latest npm - and then retry the script ?

**Comment by LTangaF** [comment]
I'm having this issue, too, constructing a Dockerfile that will install node-red on a debian-based image starting with `FROM tensorflow/tensorflow`.  The harder dependency system seems to be on the tensorflow side and I want to use the ML plugin for Node-Red, so that seemed the logical place to start.

I'm going to try your idea of pre-installing Node, @dceejay, even though the Node-Red install script says it takes care of that.

**Comment by LTangaF** [comment]
That didn't work for me, but I think I was having a different problem than the original one here. I was able to solve mine by providing interactive answers to the y/N questions that the installation script asks.

**Comment by knolleary** [comment]
Given the lack of follow-up information on this, I'm going to close the issue.

If you are still have install issues, please use the [forum](https://discourse.nodered.org) for support.
