### ISSUE TITLE
Two events showing instead of one

### ISSUE THREAD

**Issue by akhaliq7** [node-red/node-red#2546]
When i publish json objects to ibm cloud watson iot it displays the events correctly as one event per event published but when i go on the debug tab on Node Red then i deploy and run the device client then two events appear as i have a count i can tell as it says id: 1 twice then id 2 twice

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

The issue template you have deleted explains that we prefer to handle general support questions on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack).

This allows the whole Node-RED user community to help, rather than rely on the core development team.

This issue list is for core issues, not problems with particular 3rd party nodes.

When you post to the forum, you'll need to share your flow and more details.

Thanks!
