### ISSUE TITLE
Bcrypt fails to install

### ISSUE THREAD

**Issue by KrisZane** [node-red/node-red#2557]
### What are the steps to reproduce?
Install node-red via npm on a nodejs instance.

### What happens?
Fails to build bcrypt, because it doesn't exist.
It is trying to download bcrypt 3.0.6v72 for linux, but this version does not exist for linux, which causes a cascading failure.

### What do you expect to happen?
Download the a version of bcrypt that exists, so it compiles without error. Like v67 or even upgrading to a more recent 4.x version.

**Comment by KrisZane** [comment]
![image](https://user-images.githubusercontent.com/12501838/81283785-7a833980-905d-11ea-8a1f-c938426cff9a.png)

**Comment by hardillb** [comment]
This is not a Node-RED issue, at best it's an upstream issue with the bcrypt node, but even then you are missing the build tools (g++) on your machine that are required to build any node that has a native component. The download of a pre-built package is just a way to speed up the install and not build the native component locally.

You also seem to have removed most of the template you were shown when you raised this issue, which includes information about the platform you are using, makes it hard to suggest some basic debug/workarounds.

Assuming you are trying this on a Raspberry Pi, make sure you have the build-essential package installed.

**Comment by KrisZane** [comment]
@hardillb I had somehow completely missed the g++ part, that actually seemed to fix it and divert it to the fallback. I thought bcrypt was required for encrypting the node flows?

I am running it on a fullsize server, sorry for removing the bottom part.

**Comment by knolleary** [comment]
This is why the `bcrypt` module is marked as an optionalDependency - because it is not prebuilt for all combinations of platform, and we don't want to force users to install build tools if they don't want to. You'll note that whilst the bcrypt install failed, the overall install succeeded. This is because we also install bcryptjs which is a pure javascript equivalent, albeit slower than the binary bcrypt module.

If you think the install should have detected the pre-built binary for your platform, then that is, as @hardillb says, an issue for the upstream module maintainers.
