### ISSUE TITLE
NodeRed on Meteor

### ISSUE THREAD

**Issue by prabhatM** [node-red/node-red#256]
Is there any possibility of having NodeRed on the Meteor Platform ?

**Comment by mcahornsirup** [comment]
+1

**Comment by knolleary** [comment]
@mcahornsirup hi, this issue has been closed for 18 months and my comment still stands. As far as I can remember this was never raised on the node-red mailing list, so there has been no discussion on it. If you have anything to add, please send it to the mailing list rather than +1'ing a closed issue.

**Comment by Sampatel009** [comment]
i am very shock,

you are the owner of the node-red and you don't know the limitation of your system weather it fits or not.

**Comment by concept10** [comment]
Not trying to be rude, but it’s not the project maintainers job to determine if all other frameworks are suitable for _your_ use case. Insulting people will not help you.
