### ISSUE TITLE
Add storageModule: require("my-node-red-storage-plugin") in setting.js and npm start faild

### ISSUE THREAD

**Issue by tadada** [node-red/node-red#2667]
### What are the steps to reproduce?
1. Add storageModule: require("my-node-red-storage-plugin") in setting.js
2. npm start

### What happens?
start faild:
Error loading settings file: \Users\******\.node-red\settings.js

### What do you expect to happen?
start normally

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.0
- [ ] Node.js version: v12.14.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Windows10
- [ ] Browser: Chrome 84.0.4147.105  x64

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

In this instance, you have probably forgotten to add a comma after the line you've added so it is not valid JavaScript.

Thanks!
