### ISSUE TITLE
Use External Nodered

### ISSUE THREAD

**Issue by wuast94** [node-red/node-red#2706]
I have running Node Red in an extra Docker instance and would like to keep it. 
It should be an option to use and external Nodered instead of hosting one inside iobroker, i like to keep my services on diffrent containers instead of all in one. 

Is it possible to make a module in Nodered that connects to iobroker? instead of spawning another nodered in the iobroker container :)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md), or the issue template you've deleted, you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by wuast94** [comment]
i´m stupid sry ... was in the wrong repo :D
