### ISSUE TITLE
Please update bcrypt to v5

### ISSUE THREAD

**Issue by recrsn** [node-red/node-red#2857]
bcrypt module maintainer here. 

Please update bcrypt dependency to v5.

3.0.8 is unsupported and has bugs.

**Comment by knolleary** [comment]
Hi @recrsn 

we are very aware we are back-level on bcrypt. However, we still support Node 8 which bcrypt 5 does not. We're know that Node 8 is long out of support, but we can't drop support for a major node version without making a major version release ourselves. That's something our published release plan has scheduled for April when we will drop both Node 8 and 10.

We did look at a few months ago to consider accelerating the major version change so that we could update bcrypt earlier, however that posed a different set of challenges.

This is one of the challenges when modules you depend on drop support for node versions faster than you had planned for - no complaints, just a fact of the npm ecosystem.

**Comment by dceejay** [comment]
Fixed in dev for 2.0 - commit   9882582903e52ffb6d44dfaaf0bb0ea3ae03ca1a
