### ISSUE TITLE
Using sudo service node-red start instead of sudo service node-red-start resets node red with no warning

### ISSUE THREAD

**Issue by 1Ghasthunter1** [node-red/node-red#2939]
This could be taken as a feature request, but I think this is an issue because it has cost me (and others, [click here](https://discourse.nodered.org/t/all-my-nodes-and-flows-gone/1256)) to lose valuable data with a single typo.

Initially, I had just done a simple pi reboot with `sudo shutdown now`. After re-booting, I typed `sudo node-red start`, thinking that would start the node-red service. It did, really well, except that it reset node-red in the process. What I should have typed was `sudo node-red-start`.

Now, writing this, I've lost several flows, functions, etc. About 12 hours worth. Yes, I know, it's [written in several places](https://nodered.org/docs/getting-started/raspberrypi#running-locally) that the start command is `node-red-start`. 

The reason why I think this needs lots of attention is that all it takes is a 1 character difference from a simple start command versus a command that wipes the slate clean. The worst part was, once I logged into the new node-red interface, I tested to see if a node would actually save. After deploying, the pre-existing flows JSON file was overwritten and data was gone.

**Comment by hardillb** [comment]
Firstly nothing should have been lost, you have just changed where Node-RED will save it's data and flows.

By default when running as a service on RaspberyPi OS, Node-RED runs as the `pi` user. This means that the flows will be stored in the `/home/pi/.node-red`directory in a file called `flow_raspberrypi.json` (assuming you haven't changed the hostname).

When you started Node-RED with `sudo node-red start` you caused it to run as the `root` user so the flows would be stored under `/root/.node-red`. You also passed an argument to the command `start` this will have been interpreted as the name of file to use to store the flow, so the flow will have been written to `/root/.node-red/start`

If you stop the currently running instance and start it with the correct command `node-red-start` it should pick up your original flow.

There is no need to use sudo at all to start node-red as a service, since `node-red-start` will use sudo internally to make the required calls to `service`. Also it is a really bad idea to run Node-RED as root as it opens up a lot of potential security problems so it should only be done if you fully understand what you are doing and the risks involved.

If you want Node-RED to always start on boot you can run the following (the only time you need to use sudo)  `sudo systemctl enable nodered.service`

**Comment by dceejay** [comment]
also in both of those directories there is a one level backup of the previous deployment (so yes if you deploy twice it will get overwritten) - they are saved as hidden files starting with a . - so for example `/home/pi/.node-red/.flows_raspberrrypi.json.backup`  or `/root/.node-red/.start.backup`

**Comment by hardillb** [comment]
Can we close this now?
