### ISSUE TITLE
ECONNRESET in the WebSocket node raises Uncaught Exception (causing Node-RED "crash")

### ISSUE THREAD

**Issue by uncle-fed** [node-red/node-red#2956]
### What happens?

When Node-RED acts as a WebSocket server (accepts incoming connections) and the already existing WebSocket connection is terminated by the client using TCP `RST/ACK`, instead of TCP `FIN/ACK`, it causes an uncaught exception in Node-RED and the entire Node-RED process terminates instantly with the following error in the system log:

```
[red] Uncaught Exception:
    Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```

Please note that this issue is not only about "missing exception handler", there is more to it, please read below.

### Conditions to reproduce the issue

In my setup Node-RED is being used as a WebSocket server that accepts connections from the clients on the Internet (web browsers) using the "WebSocket-In / WebSocket-Out" nodes from the Node-RED core.

The Node-RED is not directly exposed to the clients but is hidden behind the HAProxy which handles the client facing connectivity (TLS, security, etc.). So, essentially, the only "client" that talks directly to the Node-RED is HAProxy.

HAProxy does something "special" (compared to the ordinary web browsers and other WebSocket clients) in one particular situation. HAProxy terminates TCP connections that it considers to be "stale" by issuing a TCP `RST/ACK` (hard reset), instead of a more graceful `FIN/ACK`.  According to the information I found, HAProxy does this by design, as it is trying to free-up TCP sockets as fast as possible. HAProxy core design goal is to maintain tens of thousands of concurrent connections and so it tries to prevent "socket starvation" that could be caused by a more lengthy `FIN/ACK` procedure that requires the socket to go through `*_WAIT` state(s). 

What is a "stale" connections in this context? HAProxy considers any (already established) connection to be stale when HAProxy expects to receive a response (demanded by HTTP or TCP protocol) but the response isn't there. In this case HAProxy waits the configured amount of time and if it does not get ANY response at all, it assumes that there is a fatal problem on the other side and such connection has to be terminated and TCP socket recycled.

Where do these stale connections come from in this scenario? It seems that Node-RED implementation of the WebSocket-IN interface is somehow "incomplete". Namely, if a WebSocket client tries to connect to the Node-RED using a URL `Path` that is NOT configured as a "WebSocket-listener" in the Node-RED interface, then instead of returning a `404` response (or closing the connection), Node-RED returns... It actually does not return anything at all... 

Node-RED just sits there silent, keeping the TCP socket connection open (forever?) and not sending back anything. In this situation, HAProxy definitely expects to get a response on behalf of the client's attempt to establish a WebSocket session. So after a configured timeout (usually a few seconds), HAProxy terminates such connection with `RST/ACK`, and this causes entire Node-RED to terminate. 

This basically means that any WebSocket client can crash Node-RED with a single HTTP/Websocket request containing URL path that Node-RED does not expect to handle. Very annoying, to say the least... :-)

### What do you expect to happen?

There are two things to be really addressed here:

1. The code that handles WebSocket client's incoming request (just before the "Connection Upgrade" is done) should always return _something_ to the client. If the WebSocket client sends a request containing non-configured `listener path`, then Node-RED should send back `HTTP 404` response (just like it does with the ordinary HTTP-in node) or at least simply close the socket, instead of doing literally nothing and keeping the connection open without any response.

2. The WebSocket-IN (and probably also -OUT, as well as the the ordinary HTTP-IN,OUT and TCP IN-OUT), should handle `ECONNRESET` exception gracefully, because it is something that can happen in a variety of scenarios (not only with HAProxy). This should not cause the uncaught exceptions and most definitely should not terminate the entire Node-RED application. `ECONNRESET` simply means that the other side has abruptly closed the existing TCP connection and such condition should be handled with a standard warning or error.

Perhaps, it makes sense (if possible) to make the `ECONNRESET` condition handling very generic, because there can be other 3rd party TCP-protocol-based nodes and modules that could be suffering from the same "missing exception handler" but I am not sure what's really possible in this respect globally within the Node-RED architecture.

### Environment details:

- [ ] Node-RED version: 1.3.3
- [ ] Node.js version: 14.16.1
- [ ] npm version: 6.14.12
- [ ] HAProxy version: 1.8.19-1
- [ ] Platform/OS: Raspberry Pi OS (latest) on Raspberry Pi 3 and 4
- [ ] Browser: not applicable (TCP networking issue)

**Comment by knolleary** [comment]
Thanks for the detailed issue report.

One of the challenges here is that there isn't a single place in Node-RED that knows the complete list of valid paths for handling WebSocket connections. And the way node's HTTP server exposes the `upgrade` event doesn't help.

For example, the core runtime listens for the `upgrade` event, it then checks if the request is on the path it cares about (`/comms`) and if so, completes the upgrade, otherwise does nothing as there may be another part of the system who has its own listen on the `upgrade` event and will care about the particular path.

This is the same model used by the WebSocket nodes, the Node-RED Dashboard nodes and so on, plus any other contrib node that uses websockets under the covers.

So I have a fix which is a bit hacky but I think is reasonable:

The core will add its own listener to the `upgrade` event. When it receives the event, it starts a timer for 5 seconds - at which point it checks how many bytes have been written to the socket (ie `socket.bytesWritten`). If nothing has handled the upgrade, then `0` bytes will have been written and we can declare the connection as invalid and close it.

The 5 second timeout will be configurable via a new setting in the user's settings file - `inboundWebSocketTimeout`. I think 5 seconds is a reasonable default in the general scheme of things.

That solves one of the issues.

For the uncaughtException, I think it makes sense for us, in the same upgrade handler, to add a default handler for the error event. If the request does get handled, it will get additional error handlers in the normal course of processing the upgrade. But if nothing does the upgrade, we can't have the socket without an error handler.

**Comment by uncle-fed** [comment]
Thanks a lot for the fix!

It did read a bit hackish at first but now that you've explained how things work under the hood (in particular, the lack of a single "registry" of all registered `upgrade` event listeners), I guess this should be OK. I am eager to test now how it plays in combination with HAProxy now. 

Just another idea... if there is a piece of code that handles the subscription to the 'upgrade' event, couldn't it be extended to keep track of all subscribers/paths globally? Or is this some code that comes from a 3rd party module (Express, etc.) that cannot be modified?

**Comment by knolleary** [comment]
To handle websocket connections, code has to register a handler for the `upgrade` event on the HTTP server object - which comes straight from the core node.js `http` module.

You don't register for a particular path - everyone will receive every upgrade request, they then have to decide whether the path in the request matches one they care about. It isn't particularly elegant - but there is no equivalent to the Express model of registering handlers for particular routes.

**Comment by uncle-fed** [comment]
https://github.com/nodejs/node/issues/6339
