### ISSUE TITLE
Function node documentation does not explain the tabs properly

### ISSUE THREAD

**Issue by tve** [node-red/node-red#2978]
The help text and documentation for the function node does not explain the Setup and OnStart tabs. For example, https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/locales/en-US/function/10-function.html#L24-L25 says "The Setup tab contains code that will be run whenever the node is started." ~So setup and start are the same but there are two tabs?~ After clicking around some more I see that the Setup tab has been repurposed for something different. Also, it mentions the Close tab, which no longer exists. It would be great to clean up the help text so one isn't totally confused.... (There a bit more text on Setup further down the page.)

The documentation is also outdated. Specifically, https://nodered.org/docs/user-guide/writing-functions#running-code-on-start doesn't explain Setup. It would be nice to be more explicit and mention the tab name switcharoo, i.e. that Setup is something different. (Side note: the tab is called "On Stop" but the event is called "close"? )

It would also be helpful to explain a bit more about what can and cannot be done in the On Start tab. Specifically, is context initialized?

- [ ] Node-RED version: the links above refer to master as of 2021/05/07

**Comment by knolleary** [comment]
The tabs got relabelled in 1.3 to be a bit more self-describing, but the docs were overlooked and didn't get updated to match. Sorry about that. We will of course fix that.

We debated whether it should be On Close or On Stop and went with Stop because end users aren't necessarily aware of the underlying event names and Stop is better understood than Close.

You can set things in context from within the Start tab.
