### ISSUE TITLE
Can I change the 127.0.0.1:1880 address to another address? And how?

### ISSUE THREAD

**Issue by jlian168** [node-red/node-red#3029]
Dear All : 

Like title, Can someone tell me how to change?

Thank u very much.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!
