### ISSUE TITLE
Unable to type into monaco editor

### ISSUE THREAD

**Issue by nstadigs** [node-red/node-red#3078]
### Current Behavior

When typing into the monaco editor in a function node nothing happens. I cant cut or paste from context menu either. The editor on https://microsoft.github.io/monaco-editor/ works as expected.

EDIT:
I get this error in the console:
```
Uncaught Error: e[Symbol.iterator] is not a function

4780/</e.first@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:1:395595
getCommand@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:2530044
executeCommand@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:967349
type@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:410055
type@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:162065
Ge/<@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:155324
fire@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:1:375996
f/<@http://192.168.0.186:1880/vendor/monaco/dist/editor.js:5:78560
    unexpectedErrorHandler http://192.168.0.186:1880/vendor/monaco/dist/editor.js:1
editor.js:1:370468
    unexpectedErrorHandler http://192.168.0.186:1880/vendor/monaco/dist/editor.js:1
```

### Expected Behavior

I can type into the editor

### Steps To Reproduce

Here's my `codeEditor` value:

```
{
            /** Select the text editor component used by the editor.
             * Defaults to "ace", but can be set to "ace" or "monaco"
             */
            lib: "monaco",
            options: {
                /** The follow options only apply if the editor is set to "monaco"
                 *
                 * theme - must match the file name of a theme in
                 * packages/node_modules/@node-red/editor-client/src/vendor/monaco/dist/theme
                 * e.g. "tomorrow-night", "upstream-sunburst", "github", "my-theme"
                 */
                theme: "vs",
                /** other overrides can be set e.g. fontSize, fontFamily, fontLigatures etc.
                 * for the full list, see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html
                 */
                //fontSize: 14,
                //fontFamily: "Fira Code, Consolas, 'Courier New', monospace",
                //fontLigatures: true,
            }
        }
```

If I change `lib` from `"monaco"` to `"ace"` I get the old editor and it works as expected. 

### Environment

- Node-RED version: 2.0.1 (official docker image)
- Node.js version: Whatever is in the docker image
- npm version: Whatever is in the docker image
- Platform/OS:
  - Server: Official docker image
  - Client: Wayland on Arch Linux 
- Browser: Latest Chrome and Firefox

**Comment by knolleary** [comment]
We have identified an issue with some nodes that include an old version of the jQuery `multiple-select` plugin - this causes conflicts with monaco.

The following nodes have been identified as including the offending version. Issues have been raised and some have since been resolved.

* [node-red-contrib-deconz-test-zehir](https://www.npmjs.com/package/node-red-contrib-deconz-test-zehir) - [issue raised](https://github.com/deconz-community/node-red-contrib-deconz/issues/140) 
* [node-red-contrib-defaro](https://www.npmjs.com/package/node-red-contrib-defaro) - [issue raised](https://github.com/bkorda/node-red-contrib-defaro/issues/1)
* [node-red-contrib-zigbee2mqtt](https://www.npmjs.com/package/node-red-contrib-zigbee2mqtt) - [issue raised](https://github.com/andreypopov/node-red-contrib-zigbee2mqtt/issues/41)
* [node-red-contrib-wirenboard](https://www.npmjs.com/package/node-red-contrib-wirenboard) - [issue raised](https://github.com/andreypopov/node-red-contrib-wirenboard/issues/2)
* [node-red-contrib-deconz](https://www.npmjs.com/package/node-red-contrib-deconz) - [Issue raised](https://github.com/deconz-community/node-red-contrib-deconz/issues/140) - author is working on it :)
* [node-red-contrib-zway](https://www.npmjs.com/package/node-red-contrib-zway) - [Issue raised](https://github.com/bkorda/node-red-contrib-zway/issues/9)
* [node-red-contrib-spruthub](https://www.npmjs.com/package/node-red-contrib-spruthub) - [Issue raised](https://github.com/andreypopov/node-red-contrib-spruthub/issues/3)

If you don't have any of these nodes installed, it would be helpful to identify what other contrib nodes you do have - particular any that have 'custom' edit dialog behaviours.

**Comment by nstadigs** [comment]
Updating node-red-contrib-zigbee2mqtt solved the issue! Thanks a lot!

**Comment by DavidKarlas** [comment]
Hi all,

just wanted to say how awesome internet is... I had this problem, had no idea what to do, installed another browser... Then looked at error messages and search internet for "e[Symbol.iterator] is not a function monaco" second result was this issue, noticed deconz, went to node-red, clicked update button, and now it works.

With all bad in the world, it's good to be reminded how far we have come as civilization.

Best regards,
David

**Comment by Semmu** [comment]
I just had the same issue (using kinda outdated stuff as I didn't have the need to upgrade anything, "don't fix what's not broken")

Anyways in my case it was the same issue, `node-red-contrib-zigbee2mqtt`, but I also had to update everything else (mostly addition dashboard widget plugins) because there were conflicting dependencies between them. So I had to figure out a proper order of updating them and clicking on the update buttons one-by-one.

So my question is (and I tried to Google): is there a quick way to upgrade _all the plugins_ at once to the latest versions possible (without them depending on conflicting libraries)?

Thanks in advance!
