### ISSUE TITLE
Feature: Dynamic link-call

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#3441]
## Preamble
Following up on the [actionflows issue](https://discourse.nodered.org/t/problem-with-node-red-contrib-actionflows-since-upgrade-to-2-2-0/57368/40) and how it used global context to provide "dynamic subroutine calls" capabilities.

## Description
* Add ability to perform link-call dynamically
* Update documentation

## Considerations / questions
* Should we add a mode selector "Static", "Dynamic" where "Static" mode operates as it does now and "Dynamic" mode would hide the "node selection tree"  
* Would the dynamic call be made by `name` or `id` (or both)?
* What property of `msg` would be used?  
  * `msg.link` ? `msg.linkId` ?   `msg.linkName` ?

## Slack discussion 
https://node-red.slack.com/archives/C9RSU6S56/p1644844378969309

**Comment by Steve-Mcl** [comment]
@knolleary @dceejay 

Some thoughts on implementing this feature...

* In `link call` node ...
  *   Should we permit `msg.link` to simply override the selected destination link node? (no UI changes)
  \- **OR** -
  * Add a UI element to switch the node between normal and "dynamic" mode (e.g. like the MQTT-IN node can be set to "single subscription" or "dynamic subscription"
    * This mode selector would hide the links choice tree when set to "dynamic mode"

**Comment by dceejay** [comment]
My opinion is option 2
I think the UI should be explicit - If in normal mode then ui as now with all the link nodes listed... if in dynamic mode then no need for the large list to be visible at all (as you suggest).  But then again - if in dynamic mode do we need a default if msg.link is not set... - though that is not the way most nodes work - ie if you leave options blank then the user must supply the option.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/5375409/154800637-16682ed8-2603-4146-8334-5b2da8f3a9d5.png">

While not relevant to this feature... I note that currently if the link call node is not named it picks up the name from where it calls to. - maybe that should be "call - {the name}" rather than just the bare name ?   And likewise when in dynamic mode maybe the node.status could show the name of the link that was called... ?

**Comment by dceejay** [comment]
1) - or indeed `msg.call` as it is about the link call node :-) .. or indeed `msg.linkcall` maybe to be more explicit ?
2) - i) no - you currently can't wire a link call node to two links - so no. 
    ii) thus also no
3) i) absolutely - name would be my preference...  
  a) hmm maybe not  - insensitive would be my pref.
    2) DON'T - just search over them both - the node would presumably create a list of possible link in nodes.ids and names at deploy time to iterate over. - searching ids first (as they are more specific) then names.
 b) if more than one then raise an error - (as can't call more than 1 (see 2-i) 
 c) that is a Nick question :-)

**Comment by dceejay** [comment]
well it may be slightly restrictive - but If you start duplicating flows the ids can change and it will break all your flows... so "trust me - it's for your own good!"

re no connection... no - I think that is a job for a new flow linter rule.

**Comment by knolleary** [comment]
I appreciate this echos some of Dave's comments, but my thoughts are:

1. I'd be fine with `msg.target` as it is more functional

2. no - stick with single target to be consistent with what you can configure in the node

3. By name is going to be far more useful than by id. It will survive flows being imported (and having their id's change)

We don't need to over specify the functionality. For now, it can search both `id` and `name`. If there are multiple matches, for now, then we can error. We can leave room in the future to support calling multiple functions - but that is not a requirement today.

> Run through .eachNode and locally Cache in a lookup meaning 1st link call would be O(n) and subsequent call O(1)

I would add a global to `60-link.js` that the `link in` nodes register/unregister themselves from when they are created/closed. The `link call` node can then use that to do the look up rather than have to use `RED.nodes.getNode()` at all.

**Comment by Steve-Mcl** [comment]
Thanks everyone.

So I pretty much finished this earlier today (bar some tidy ups) & luckily aligns with most of what you guys suggest.

But - when it comes to naming "Link In" nodes and raising an error because two "Link In" nodes (on different flows) have the same name, it became obvious extra consideration for "copy/paste-ability" was needed because this is a common design pattern.  i.e. Not permitting same named "Link In" nodes on different TABS would mean a flow would have to be edited when a flow is duplicated onto a separate TAB - both inconvenient and preventing common design patterns

So instead of raising an error, I added the ability to scope the target to "local" and "global" using a `C++` like scope resolution operator syntax (scope::target) thereby by permitting the "Link Call" to target a "Link in" on the same flow simply by specifying the `"link name"` only syntax & for targeting links on another flow, via a fully qualified name `"flow name::link name"` syntax 

Note: Before I added the scoped string syntax, I first made the scoping work via an object...
```
msg.target = {flowName: "the ::main:: API", linkName: "my_link" }
```
A happy side effect of this is that it permits calling a "Link In" node someone has called "my::subroutine" on a flow named "my::main::API" 😄  




#### Example...

msg.target | "Link Call" node on flow | Calls...
-- | :--: | --
"Link 1" | Flow 1 | Link 1 on Flow 1
"Link 1" | Flow 2 | Link 1 on Flow 2
"Link 1" | Flow 3 | Link 1 on Flow 3
 &nbsp; |  &nbsp;  | &nbsp; 
"Flow 1::Link 1" | Flow 1 | Link 1 on Flow 1
"Flow 1::Link 1" | Flow 2 | Link 1 on Flow 1
"Flow 1::Link 1" | Flow 3 | Link 1 on Flow 1
 &nbsp; |  &nbsp;  | &nbsp; 
"Flow 2::Link 1" | Flow 1 | Link 2 on Flow 1
"Flow 2::Link 1" | Flow 2 | Link 2 on Flow 1
"Flow 2::Link 1" | Flow 3 | Link 2 on Flow 1
 &nbsp; |  &nbsp;  | &nbsp; 
"Flow 3::Link 1" | Flow 1 | Link 3 on Flow 1
"Flow 3::Link 1" | Flow 2 | Link 3 on Flow 1
"Flow 3::Link 1" | Flow 3 | Link 3 on Flow 1


#### Difficulties
1. When a flow name is changed the "Link In" nodes need to rebuild their cache entry so I had to subscribe to the `flows-started` event to essentially tell every `Link in` to "re-register" in the (local) global cache.


#### Questions
1. The Fully Qualified a `C++` like scope syntax for calling a Link In on a different flow is currently `"flow name::link name"` - does anyone have a preference?  I did consider `/` and `//` and others, but when I thunk back to my C++ days, I stopped at `::` - open to suggestions :)
2. For now, both the simple string AND the object syntax can be used to call the remote "Link in" node. Should I remove the Object call type (leaving the string syntax only)?

**Comment by knolleary** [comment]
I think the rules should be, given `msg.target` set to `FOO`:

1. if there is exactly one node called `FOO`, call it
2. if there are more than one matching node
    1. if there is exactly one matching node on the same flow as the Link Call node, then call it.
    2. otherwise do nothing/log a warning (tbd)

Supporting a 'fully qualified' name is a nice idea - but I'm slightly hesitant. How likely is it a user will want multiple identically named Link In nodes on different flows and be able to call out to a different one (rather than modify the name to ensure uniqueness)?

If we do choose to support it, I would stick with just a string type property, and I would use `/` as the separator. That's familiar and consistent with file paths, MQTT topics, npm package names - I don't feel the need to mixing C++ style syntax that isn't as familiar to the JavaScript world.

**Comment by Steve-Mcl** [comment]
> Supporting a 'fully qualified' name is a nice idea - but I'm slightly hesitant. How likely is it a user will want multiple identically named Link In nodes on different flows and be able to call out to a different one (rather than modify the name to ensure uniqueness)?

I do have use cases (like if flow TABs were named according to a location for example, I would automate the Link Calls `target` to ``` msg.target = `${location}/standard_function`; ```) but also, I would not want to accidentally call something on another flow TAB should I misspell the name (or the automation specified a wrong name). By scoping we limit "damage" to the local flow tab.  Lastly, having to rename the other flow "Link In" nodes because we dont support scoped calling would mean, in some automation cases, having to create a lookup or use a switch node when a common pattern design was desired.

I would like the scoping part to make the cut so will finish up and raise PR for review - we can thrash it out there 😉

**Comment by dceejay** [comment]
Really ? that sounds very fragile if you add another location - you then need to add another call to match - would you not just pass in the location as a variable in the msg ?  In the simple case where I have (say) a tab where I keep all my call flows - can I just call it from another page with just its simple name (as per when I click on the list of nodes today) ? or do I now have to use the long name ?

**Comment by knolleary** [comment]
@dceejay  not sure which comment your "really?" is refering to.

> can I just call it from another page with just its simple name (as per when I click on the list of nodes today) ?

Yes. Point 1 in my list is exactly that. If there is precisely one node named FOO (wherever it may be) then it is called.

**Comment by Steve-Mcl** [comment]
Ok, as you 2 ganged up on me I have reneged 😆 

* I have removed calling a target by object (string only now)
  * While I think this could be useful, it can safely be added later in a compatible manor
* Targeting rules...
   * I have removed the scoping - only call by name & call by node.id are supported.
   * If link-in "FOO" exists once, it is called ✅
   * if link-in "FOO" exists on 2 regular flows, but one of them is the same flow tab as the Link-Call, the local Link-in is called. ✅
   * if link-in "FOO" exists on twice on the same flow, an error is raised ❌ (dynamic mode only)
   * if link-in "FOO" exists on 2 different flows an error is raised ❌(dynamic mode only)
   * if the target does not exist, an error is raised ❌(dynamic mode only)
   * if the `target` is a node.id, that is called, regardless of which flow tab it exists. ✅

On top of that, i had fun figuring out how to get this to work in a subflow. 
I have found that in a regular flow, the `n.links` prop is an array. In a subflow, it is a string.  
I did try to track this down but it went deep into the bowels of the runtime and flow diffs.
For now, I simply do a test...
```
const staticTarget = typeof n.links === "string" ? n.links : n.links[0];
```
... If either of you guys have an idea, we can fix this (or just continue to handle it)
NOTE: The export of a subflow with link nodes actually exports the `links` prop as an array of string!

Lastly, I have added tests...
* should call link-in node by name and get response
* should timeout waiting for link return
* should raise error due to multiple targets on different tabs
* should raise error due to multiple targets on same tabs

The branch is here: https://github.com/Steve-Mcl/node-red/tree/dynamic-link-call 

If there is anything I've missed, let me know.

I will push PR Monday.

**Comment by knolleary** [comment]
1. You cannot use link nodes going **in** to a subflow
2. You should be able to use a link call node calling **out** of a subflow

> I have found that in a regular flow, the n.links prop is an array. In a subflow, it is a string.

That doesn't sound right. There should be no difference. We will need to investigate what's happening there rather than work around anything.

I think there's an open issue around link nodes and subflows, but I don't recall the specifics (not in a position to go searching)

**Comment by Steve-Mcl** [comment]
@dceejay 

> Re Q2 - not sure I understand - surely the link call node already does call link in nodes ? What else can it call ?

I should have been more explicit lol.  To paraphrase...
Should a subflow instance be able to call out of itself to a link in node that lives in the regular flows.  I'm torn. It goes against PURE  principles but others might think it is unnecessarily restrictive if we prevent it.

**Comment by Steve-Mcl** [comment]
@knolleary could you please link this to PR #3463

**Comment by SandeepAgarwal13** [comment]
Hi - I did not know this is in development. So Thank You for that. This allows me to put some plan to phase out action flows.
Plus brings it into the fold of core development - rather than custom nodes which as we see may not be maintained.
My team has been bugging me for some time now to look for alternatives in view of 2.2 issues with action flows.

And apologies for butting in - please feel free to ignore. 

My 2 cents :- 

I am assuming You are doing GUI changes to make this explicit. If not you may ignore the #1.

#1)

If i understand the above discussion correctly - in case of dynamic Link Call - the proposal is to set msg.target and then call the link in with value (name/id) set in msg. target ?
If so, wouldn't it be better for user to allow to set name of attribute from msg which can be used to get Link IN node name. 
Else you have multiple sequential calls to different Link IN nodes - before each call , a set node for msg.target would be needed to set to the correct name. Rather i would simply say when calling Link Call node - use attribute msg.x for this call or attribute msg.y on other.

Example :- 
inject---> Link Call (msg.a) ----> function node ---> Link Call (msg.b) ---> and so son.

So i set msg.a and msg.b when defining the flow. And how to set those is my handls which i may do in inject node or as part of my process initialization.

If i have msg. target - it means before each Link Call - we need a Set node - thereby increasing the number of nodes. Not sure if it really helps. Once the user goes for dynamic option exists with user - its his responsibility.

-----
#2)
I saw a comment :- 
if the target does not exist, an error is raised ❌(dynamic mode only) --> Wouldnt making  it pass through i.e the msg simply passes to the next node .... make it more flexible.

Maybe add a warning . This way user knows.

This way if user wants to have dynamic flows - it allows him to do so. Giving an error means even when the node should be a dummy call - he needs to create dummy flow so as things will not fail. i.e un-necessary clutter when can be avoided.

If you really think you want to make it - error - give the option to the user if he wants it to error.

Once again Thank You for above.
