### ISSUE TITLE
Trouble installing node-red on Ubuntu 18.04

### ISSUE THREAD

**Issue by Jordan-Liwag** [node-red/node-red#3489]
Hi im in a class where we need to make install a lamp stack, Virtual Hosts, SSL Certificate, Nodejs, Node Red. We are using digital ocean and putty. I got to the part of installing nodejs but I'm having trouble with an error to run node-red.
Any help would be appreciated
![nodered error](https://user-images.githubusercontent.com/58646855/158051485-be9c756c-e884-42b5-8594-531e89675767.PNG)
thank you in advance

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!
