### ISSUE TITLE
The Server Won't Start At Version `> 1.2.0 && < 2.2.2` Without `NODE_RED_HOME` Variable Set

### ISSUE THREAD

**Issue by manuth** [node-red/node-red#3508]
### Current Behavior

If the environment variable `NODE_RED_HOME` isn't set, the node red server won't start with the following error:
```
The "path" argument must be of type string. Received undefined
```

The root cause is these portions of code:
https://github.com/node-red/node-red/blob/e34f4acb220eff70272b27a4ff80fdedda1ccbd0/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/index.js#L31-L33
https://github.com/node-red/node-red/blob/e34f4acb220eff70272b27a4ff80fdedda1ccbd0/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/index.js#L40-L42

Take note, that `process.env.NODE_RED_HOME` is passed to `fspath.join` without checking whether `process.env.NODE_RED_HOME` equals `null`. This causes the error mentioned before whenever `process.env.NODE_RED_HOME` isn't set.

### Expected Behavior

The other fallbacks as seen in the code should be executed if `process.env.NODE_RED_HOME` isn't set:
https://github.com/node-red/node-red/blob/e34f4acb220eff70272b27a4ff80fdedda1ccbd0/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/index.js#L43-L47

### Steps To Reproduce

Try to start the server with both the `userDir`-setting and `process.env.NODE_RED_HOME` unset.

### Example flow

```ts
import * as http from "http";
import * as express from "express";
import * as RED from "node-red";

(async () => {
    const app = express();
    app.use("/", express.static("public"));
    const server = http.createServer(app);

    RED.init(
        server,
        {
            httpAdminRoot: "/red",
            httpNodeRoot: "/api",
            functionGlobalContext: {},
            uiHost: "127.0.0.1",
            uiPort: 8080
        });

    server.listen(8080);
    await RED.start();
})();
```

### Environment

- Node-RED version: `1.2.0-beta.1`, `1.2.0`, `1.2.1`, `1.2.2`, `1.2.3`, `1.2.4`, `1.2.5`, `1.2.6`, `1.2.7`, `1.2.8`, `1.2.9`, `1.3.0-beta.1`, `1.3.0`, `1.3.1`, `1.3.2`, `1.3.3`, `1.3.4`, `1.3.5`, `1.3.6`, `1.3.7`, `2.0.0-beta.1`, `2.0.0-beta.2`, `2.0.0`, `2.0.1`, `2.0.2`, `2.0.3`, `2.0.4`, `2.0.5`, `2.0.6`, `2.1.0-beta.1`, `2.1.0-beta.2`, `2.1.0`, `2.1.1`, `2.1.2`, `2.1.3`, `2.1.4`, `2.1.5`, `2.1.6`, `2.2.0-beta.1`, `2.2.0`, `2.2.1`, `2.2.2`
- Node.js version: `v17.6.0`
- npm version: `8.5.5`
- Platform/OS: Windows 11
- Browser: n/a

**Comment by hardillb** [comment]
I'm going to say this is working as expected. When you embed Node-RED into another application (which is basically what you've done with your example code) it is up to you to ensure that a `userDir` value is passed in the `settings` object.

Since Node-RED would be running as part of your application it **should not** be using the standalone Node-RED location, but it should be using a location specific to your application.

The embedding Node-RED guide (https://nodered.org/docs/user-guide/runtime/embedding) shows a `userDir` entry in the settings (I will concede it probably shouldn't be `.nodered` to make things clearer, but it is different from the default `.node-red`).

And the default launcher also makes sure a suitable value is passed in:

https://github.com/node-red/node-red/blob/c8dc2327a32f4772645b0e5af0b630a5f48b32b6/packages/node_modules/node-red/red.js#L115

https://github.com/node-red/node-red/blob/c8dc2327a32f4772645b0e5af0b630a5f48b32b6/packages/node_modules/node-red/red.js#L316

**Comment by manuth** [comment]
> I'm going to say this is working as expected. When you embed Node-RED into another application (which is basically what you've done with your example code) it is up to you to ensure that a `userDir` value is passed in the `settings` object.
> 
> Since Node-RED would be running as part of your application it **should not** be using the standalone Node-RED location, but it should be using a location specific to your application.
> 
> The embedding Node-RED guide (https://nodered.org/docs/user-guide/runtime/embedding) shows a `userDir` entry in the settings (I will concede it probably shouldn't be `.nodered` to make things clearer, but it is different from the default `.node-red`).
> 
> And the default launcher also makes sure a suitable value is passed in:
> 
> https://github.com/node-red/node-red/blob/c8dc2327a32f4772645b0e5af0b630a5f48b32b6/packages/node_modules/node-red/red.js#L115
> 
> https://github.com/node-red/node-red/blob/c8dc2327a32f4772645b0e5af0b630a5f48b32b6/packages/node_modules/node-red/red.js#L316

Oh that's fair
I was already wondering how this could slip by all this time 😂

Thanks for the explanation, I'll take this into account 😄
