### ISSUE TITLE
WebSocket "Connect to" nodes display "disconnected" while being connected

### ISSUE THREAD

**Issue by fungiboletus** [node-red/node-red#3527]
### Current Behavior

I created two websocket nodes with the type "Connect to". One `websocket in` and one `websocket out`. They are both connected to the same WebSocket server that use the new Subprotocol feature (since release `2.2.0`).

They connect successfully as I can both send and receive messages. However both nodes are marked as `disconnected` with a red mark. Restarting the flow shows them as `connected` very briefly.

### Expected Behavior

Connected websocket nodes should have a `connected` status instead of a `disconnected` status.

### Steps To Reproduce

 - Create a websocket in/out node to a websocket server and deploy.

### Environment

- Node-RED version: `2.2.2`
- Node.js version: `14.18.2`
- npm version: `6.14.15`
- Platform/OS: `Docker/Linux`
- Browser: `Safari and Edge`

**Comment by Steve-Mcl** [comment]
Hi, thank you for raising an issue.

Please provide a demonstration flow so we can replicate your setup. 

\```
paste exported flow between 3 back ticks
\```

**Comment by fungiboletus** [comment]
[I uploaded the flow in a gist](https://gist.github.com/fungiboletus/becefa16e0ee7635bb7a4bb83c2a253a)

This is how it looks: you can click on `inject` and you will start to receive messages. Notice also that the status node sends a `connected` event.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/45740/162958313-6701228f-a367-4001-a9ab-69021b5bbd5f.png">

**Comment by fungiboletus** [comment]
Interesting, can you restart the flow to see what happens ?

I ran the container using containerd in Kubernetes in a very different environment and I had the same behaviour. I could try to reproduce the issue outside Docker if you don't see the bug when you restart the flow.

**Comment by Steve-Mcl** [comment]
> Interesting, can you restart the flow to see what happens ?

In what way?  Restart node-red?  Press the inject again?  Use the deploy button menu "restart flows"?

**Comment by fungiboletus** [comment]
The deploy button menu "restart flows", sometimes the first deploy works but the following deploys are inconsistents.

**Comment by Steve-Mcl** [comment]
@fungiboletus 

I have managed to re-create this and it happens fairly regularly (enough to debug it).  

I have added a 2nd output so I can monitor the internal `readyState` of the socket (**temporary for debugging** - this will NOT be in the update).  As you can see, the WS nodes `status` is jumping quickly past connected to disconnected BUT the 2nd output (which is basically a 200ms interval monitoring socket.readyState) shows the internal state of the socket.  also, nodte how the output of the status says "connected"

![chrome_i2GPcRyAeo](https://user-images.githubusercontent.com/44235289/163364213-d5911de8-043c-444c-9087-1e0050e5f37d.gif)


As you can see, this issue is *mostly a visual problem. (some internal state is modified by the old sockets disconnect event)

I can see _why_ this happens ...
* restarting flows re-creates the node
* the newly created websocket is opened - causing the CONNECTED status
* then the previous websocket reports it has closed  - causing the DISCONNECTED status

but I am so far struggling with the best approach. 

@knolleary @dceejay 
Is there any reason we cannot move to `ws` v8 (currently NR is on V7.5.6, latest `ws` is V8.5.0
Of course I would expect this update  is targeted to the next NR major release.
Please let me know your thoughts, either way? ASAP would be good so I can either begin work on the upgrade to ws v8 or work on some kind of workaround for delayed `close` events.

**Comment by dceejay** [comment]
would be a sensible v3 thought.
Re delayed close... should it/can it just not call done() until closed ?

**Comment by Steve-Mcl** [comment]
> Re delayed close... should it/can it just not call done() until closed ?

I've looked at the we.close method - there is no callback in ws v7 on the `close` function. 

Of course we could somehow hook the `closed` event to call done but I have already seen the `ws` node has internal state to prevent the `opened`, `closed` `connecting` events triggering more than once - I suspect we would end up, at some point with the node-red editor "waiting on the ws close event until the internal node-red close timeout" (long deploys)

**Comment by dceejay** [comment]
callback ...... and in v8 ?
or could go for the good old just add a 25mS timeout and call done :-)

**Comment by Steve-Mcl** [comment]
> or could go for the good old just add a 25mS timeout and call done :-)

That would probably work TBF

> callback ...... and in v8 ?

not looked yet (_off I go for a look see_)

**Comment by dceejay** [comment]
so indeed they also just have a timeout (30s) .. But hey for this issue I would say we just try 50mS and see as isn't the actual close all being done locally ?

**Comment by Steve-Mcl** [comment]
I'll try that & if it looks ok, I'll raise a PR against master.

**Comment by Steve-Mcl** [comment]
@dceejay so, after some trials, I see the `ws` close event is taking between 280 ~ 490ms (for this particular ws connection) to complete the `close` handshake. 

Would it be acceptable to monitor the `readyState` using a 10ms interval & calling `done()` once  `readyState == closed` OR  a MAX of 1000ms (whichever comes first)?

e.g...

```js
        node.on("close", function(done) {
            node.closing = true;
            node.server.close();
            //wait 100*10 (1000ms max) for ws to close
            const closeMonitorInterval = 10;
            let closeMonitorCount = 100;
            let si = setInterval(() => {
                if(node.server.readyState === ws.CLOSED || closeMonitorCount <= 0) {
                    clearInterval(si);
                    return done();
                }
                closeMonitorCount--;
            }, closeMonitorInterval);
        }
```

**Comment by dceejay** [comment]
Looks very sensible to me. Maybe 20ms. No need to rush. But hey.
