### ISSUE TITLE
Admin api is not available

### ISSUE THREAD

**Issue by ronny35** [node-red/node-red#3806]
### Current Behavior

I want to use admin api to export a list of nodes, for example /nodes.
When I try this url, I have error in console like this :

Uncaught TypeError: RED.nodes is undefined
    <anonymous> http://XXX/nodes:15427

### Expected Behavior

Must return result

### Environment

- Node-RED version: 3.0.1
- Browser: Firefox

**Comment by knolleary** [comment]
As described in the [API documentation](https://nodered.org/docs/api/admin/methods/get/nodes/), to get the list of nodes, you need to set the `Accept` header to `application/json`.

If it is set to `text/html` (which is what the browser will be using), the api returns all of the node html to be loaded into the editor - which is what you're getting here. The browser is then trying to evaluate that HTML and hitting errors because it is intended to be loaded into the editor.
