### ISSUE TITLE
Node Red crashing with sendEvent.destination.node.receive

### ISSUE THREAD

**Issue by vajonam** [node-red/node-red#3848]
### Current Behavior

```

19 Aug 09:18:58 - [red] Uncaught Exception:
19 Aug 09:18:58 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:152:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[09:18:58] WARNING: Node-RED crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

### Expected Behavior

Not crash? nothing has changed other than the node-red version which I updated to 3.0.2

### Steps To Reproduce

I cant tell which flow is crashing so debugging is not very easy, I dont know where to start.

### Example flow

Dont have one yet.

### Environment

- Node-RED version: 3.0,2
- Node.js version: v16.16.0
- npm version: npm@8.10.0
- Platform/OS: Home Assistant (Debian 11.3)
- Browser: Chrome

**Comment by vajonam** [comment]
a forum user is reporting this to be related to duplicate port labels.

https://discourse.nodered.org/t/node-red-crashing-sendevent-destination-node-receive-is-not-a-function/66674/5?u=vajonam

**Comment by Steve-Mcl** [comment]
@vajonam I seen that post. It is highly unlikely the output labels have any effect on this part of the code.  In fact, for fun, I tested this & it made no difference.

The only common link I see is you are both using home assistant. 

What I will say is that I have seen something similar when a contrib node calls `send` or `done` directly in a promise callback (cannot find the info now) but essentially, it made the `node` object into "not a real node red-node" object & therefore calling the expected node functions failed.  In this case it is the `receive` function that is not present in the `node` object here [on line 831](https://github.com/node-red/node-red/blob/9540cfe74931720aa34f1b0e8dbbef566cb91c8b/packages/node_modules/@node-red/runtime/lib/flows/Flow.js#L831)

IIRC, something like ...
```
mypromise.then(send).catch(done)
```

instead of ...
```
mypromise.then((m) => send(m)).catch(err => done(err))
```

can caused the issue I seen.

So this makes me think something specific to the nodes installed by Home Assistant since I cannot re-create this outside of Home Assistant (and I don't use HA sorry)

**Comment by Steve-Mcl** [comment]
Discussed here: https://discourse.nodered.org/t/node-red-crashing-sendevent-destination-node-receive-is-not-a-function/66674?u=vajonam and here: [supervisor doesn't restart node-red · Issue #3812 · home-assistant/supervisor · GitHub](https://github.com/home-assistant/supervisor/issues/3812)

**Comment by vajonam** [comment]
> So this makes me think something specific to the nodes installed by Home Assistant since I cannot re-create this outside of Home Assistant (and I don't use HA sorry)

I will poke around the home assistant nodes to see if I can find / narrow down the offending node.

**Comment by vajonam** [comment]
I am now leaning toward the contrib-kodi nodes which are now 3 years old. I have removed those for my flows. they have web socket listeners the kodi-in node which could be the problem. disabling them has prevented a crash so far.. will keep you posted. 

found another kodi crash that brought down node-red https://github.com/estbeetoo/node-red-contrib-kodi/issues/16

**Comment by Peruvien** [comment]
Hi ! 
Concerning the message : 

> a forum user is reporting this to be related to duplicate port labels.

I had the same issue, not sure when it happened, i suspect during merge conflict, but two subflow object got the same "in" node, by that, i mean the same "id".

When launching node-red, it doesn't crash, but if one of those flow is triggered, node-red then crash
