### ISSUE TITLE
Unexpected Node Error on node-red-contrib-play-soundfile

### ISSUE THREAD

**Issue by nop112233** [node-red/node-red#3850]
### Current Behavior

********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: test
    at log_helper (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:512:20)
    at Play_audio_file.Node.log (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:531:5)
    at new Play_audio_file (/data/node_modules/node-red-contrib-play-audio-file/play_audio_file.js:4:14)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/util.js:90:27)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/index.js:394:33)

Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/
********************************************************************

### Steps To Reproduce

- install node-red-contrib-audio
- drag mp3-node into board
- fill in a mp3
- compile

you get an error

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Thanks for raising.

This will eventually need to be reported against node-red-contrib-play-soundfile itself to get fixed. The error asks for it to be raised here first so we can take a look to see what that node is doing to cause this error.

Will update when we have a chance to look properly.

**Comment by hardillb** [comment]
Actual node is [node-red-contrib-play-audio-file](https://flows.nodered.org/node/node-red-contrib-play-audio-file) which doesn't actually have a project on github at the URL in the package.json

**Comment by hardillb** [comment]
This node was:

 - published 6 years ago
 - never updated
 - the github URL is broken so no way to report errors (after a bit of npm digging into the publisher I found a project [here]((It may have been moved to https://github.com/LeanBI/node-red-contrib-play-audiofile) but still it's not been touched since originally published) 
 - will always fail as it's first line of useful code is trying to call `this.log` before the node has been initialised with `RED.nodes.createNode(this,config);`

I suggest we remove it from the catalog and the OP should uninstall the node as it is unlikely to ever be fixed.

**Comment by hardillb** [comment]
PR raised against upstream project. Suggest if not merged/published in 2 weeks(?) remove from catalogue.
