### ISSUE TITLE
Change Node Autofill wants capital letters

### ISSUE THREAD

**Issue by danbru1989** [node-red/node-red#3883]
When using a change node to modify a value, the autofill feature was giving me grief. It wanted responseURL rather than responseUrl. The capital letters would not work.
![Screen Shot 2022-09-14 at 1 12 53 PM](https://user-images.githubusercontent.com/33128459/190219943-f0c61998-4133-49d3-8d16-7a78de7499da.png)

**Comment by knolleary** [comment]
Hi @danbru1989 

we provide an issue template that we ask people to use when reporting problems as it ensures enough information is captured when raising an issue. It's also the default option when you click 'new issue'. Please make use of that in the future.

The auto-complete suggestions are based on well-known properties of the core nodes. The HTTP Request node sends a message with the property `responseURL` - which is why it is in the list. You don't have to use the suggestions - you can enter whatever you want.

In this instance, I can see your change node is immediately after an HTTP Request node - so the property you want is `responseURL`. Why do you want to use `responseUrl`?

**Comment by danbru1989** [comment]
Thank you for your posting instructions.

I found that using 'responseURL' would not work set the 'page_url' property. Only 'responseUrl' worked.

**Comment by danbru1989** [comment]
Thank you!
