### ISSUE TITLE
MQTT dynamic subscribe failed with TLS connection

### ISSUE THREAD

**Issue by KannadukiAoi** [node-red/node-red#3955]
### Current Behavior

Use build-in mqtt subscribe node to subscribe a topic on AWS IoT Core.
Setup dynamic subscribe
<img width="490" alt="image" src="https://user-images.githubusercontent.com/42786642/202826026-605b4061-bf45-4668-ab0f-6a8580582bde.png">
Setup a inject to dynamic subscribe
<img width="548" alt="image" src="https://user-images.githubusercontent.com/42786642/202825832-a4b5b145-0e4e-4660-8562-61f3b2c39673.png">
Before click the subscribe inject
<img width="566" alt="image" src="https://user-images.githubusercontent.com/42786642/202825879-cb3aa519-32d7-4b65-9fb1-4cf705ef3aca.png">
After click the subscribe inject
<img width="538" alt="image" src="https://user-images.githubusercontent.com/42786642/202825900-54096a6c-003f-40e8-a0e5-371534d7d6ab.png">

### Expected Behavior

Correctly subscribe the topic

### Steps To Reproduce

Setup aws mqtt connection
<img width="885" alt="image" src="https://user-images.githubusercontent.com/42786642/202826166-7086c676-451e-48e9-8109-c9ee9e6812b4.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/42786642/202826202-1b8361c5-6ff8-4ca9-bb2d-a9d1e085285d.png">

Then setup dynamic mqtt connection as my current behavior. It will never get the mqtt connection back until I deploy flow again.

### Environment

- Node-RED version:3.0.2
- Node.js version: 16.13.1
- npm version: 8.1.2
- Platform/OS: Windows
- Browser: Chrome 107.0.5304.107

### External information
Mqtt dynamic subscribe work well if the targe broker is local mosquitto broker without any security setting.
Mqtt "subscribe to single topic" works well with my aws setting.
Dynamic publish works fine.
node-red-contrib-mqtt-dynamicsub works fine on AWS mqtt broker with same setting.

**Comment by Steve-Mcl** [comment]
Often, the reason for disconnection when subscribing is an invalid topic (not necessarily wrongly written but rather that the broker doesnt permit or allow a specific topic due to ACLs or something else)


Questions...
1. If you use the regular MQTT-IN node with a fixed topic of `test/123` does the connection remain stable?
    1. Do you get values when when publishing to `test/123` from another client
2. If you dynamically subscribe to the same topic `test/123` using `node-red-contrib-mqtt-dynamicsub` do you get values when another client publishes to `test/123`


Lastly...
Would you be able to share the necessary certs and credentials (privately) to me so that I can test/debug/fix?
You can PM me (`@Steve-Mcl`) on the [node-red forum](https://discourse.nodered.org/new-message?username=Steve-Mcl&title=MQTT%20Dynamic%20Subscription)

**Comment by KannadukiAoi** [comment]
@Steve-Mcl
To answer your question:
>If you use the regular MQTT-IN node with a fixed topic of test/123 does the connection remain stable?
Yes, it remain stable with fixed topic. Our project use fixed topic to connect to AWS IoT core for more than half year without any issue.

>Do you get values when when publishing to test/123 from another client
Yes, use fixed topic works without any issue, the MQTT-IN node able to receive message from any other client.

>If you dynamically subscribe to the same topic test/123 using node-red-contrib-mqtt-dynamicsub do you get values when another client publishes to test/123
Yes, this one works fine. This is the workaround of our current project.

>Would you be able to share the necessary certs and credentials (privately) to me so that I can test/debug/fix?
Sure!  I will share the credential later via node-red forum.

**Comment by KannadukiAoi** [comment]
@Steve-Mcl I tried to PM you on node-red forum. But it show error message said I cannot send person message to you.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/42786642/203690113-0186525d-966d-4f33-ad5c-039d5cd06702.png">
I guess because I am a new user that not able to use PM function.

**Comment by Steve-Mcl** [comment]
@KannadukiAoi I have replied to you on the forum (includes sensitive info) - essentially, I cannot achieve a stable connection using the certs and aws hostname provided even when using static (non dynamic) MQTT-in / MQTT-out nodes.

**Comment by KannadukiAoi** [comment]
Thanks for your supporting. So the issue is because if I didn't specify qos, it will automatily use qos 2 and that why cause the disconnecting issue.

**Comment by dceejay** [comment]
Hmmm yes I guess it has... I guess in the old days (pre v5) they just not have been able to report the specific error :-) and may have failed silently.  
Ok - going off piste - is this failure mode worthy of a special case - ie status message to say QoSS2 not supported ?

**Comment by Steve-Mcl** [comment]
> is this failure mode worthy of a special case - ie status message to say QoS2 not supported

It is only really relevant for V5 connections due to the richer failure info...
https://www.emqx.com/en/blog/mqtt5-new-features-reason-code-and-ack

For example, the above issue resulted in a reason code of 155 - which is actually "QoS not supported" but I believe the actual text is defined/customised by the broker implementation.  That makes it difficult to "pick out" what & why specifically like QoS 2 not supported.

NOTE: we do see the reason code and reason text in the console (added in NR v3.0.0 & v2.2.0 I think) so it does surface but not in the editor. Not certain how we could surface this to the editor - but we probably should - especially when the disconnection is initiated by the broker (v5 has that ability & is what was happening here).

**Comment by dceejay** [comment]
I don't think we need to know why the QoS isn't supported... but "QoS not supported" would be a great Status message - or indeed "Disconnected - QoS not supported" - or if there is a list of error codes that could be linked to then maybe just add the error code ?
