### ISSUE TITLE
File context store with dir property not working and corrupting other storage

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#3975]
### Current Behavior

Please see https://discourse.nodered.org/t/multiple-localfilesystems/71617/48

All details there.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 16.18.1
- npm version:
- Platform/OS: Windows 10/WSL2/Debian - `Linux 5.15.74.2-microsoft-standard-WSL2 x64 LE`
- Browser: Edge 107.0.1418.62 (Official build) (64-bit)

**Comment by knolleary** [comment]
Turns out I had given bad advice in that thread in how to properly configure multiple stores.

I failed to remember the store config needs to be nested under a `config` property - as described in the docs [here](https://nodered.org/docs/api/context/store/localfilesystem#configuration).

So instead of 
```
contextStorage: {
   default: "memoryOnly",
   memoryOnly: { module: 'memory' },
   file: { module: 'localfilesystem', dir: '/home/user/.node-red/context1' },
   file2: { module: 'localfilesystem', dir: '/home/user/.node-red/context2' },
   file3: { module: 'localfilesystem', dir: '/home/user/.node-red/context3' }
},
```

it should have been:
```
contextStorage: {
   default: "memoryOnly",
   memoryOnly: { module: 'memory' },
   file: {
      module: 'localfilesystem',
      config: {
         dir: '/home/user/.node-red/context1'
      }
   },
   file2: {
      module: 'localfilesystem',
      config: {
         dir: '/home/user/.node-red/context2'
      }
   }
},
```
