### ISSUE TITLE
Feature: Group UX improvements

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#4067]
Based on user feedback in the forum, there are a number of UX improvements around groups we want to look at.

We need to think through the consequences of these proposed changes, as there are lots of micro-interactions around groups that would be affected. The following list are the main points of feedback around interaction with groups. There are other comments around limitations of the labels and group appearance, but I want to focus on the interaction side at this point.

#### Selecting a node inside a group

Currently you click once on a node to select the group, click again to 'enter' the group and click again to select/edit the node. This makes it inconvenient to work with nodes inside groups.

The general feedback preferred an approach where you can interact with nodes directly regardless of whether they are in a group.

We currently have a concept of the 'active' group (where the group is drawn with a dotted border). This may not be needed anymore if nodes can be interacted with directly - if so, should be removed. But there are likely to be some edge case logic around this that will need to be reworked.

#### Selecting a group

Currently you select a group by clicking on its border or any of its contents. This would be changed so that a group is only selected if you click on its border. What if the border style is transparent so there is no visible border to click?

#### Moving a group

Once selected, a group is moved by dragging on its border.

#### Adding multiple nodes to an existing group

Currently you can only drag an individual node into an existing group to add it. It is a reasonable expectation to be able to select multiple nodes (and groups) and drag them all into an existing group. This wasn't originally done to avoid potential edge cases around overlapping groups and unintended adding... but we should just make it work properly

#### Moving a node into a nested group

If a node is already inside a group (A) and that group contains another group (B), it is reasonable to expect to be able to drag the node into group B... ie drag it deeper into the nested group hierarchy.

It remains a different UX problem on how to remove a node from a group via mouse interaction alone. We have the actions for that and 3.1 brings them much closer to the user via the context menu. But it would still be good to have a mouse interaction for it. Perhaps Shift-drag should move the node around as if it isn't in any group, allowing it to be 'rehomed' into any other group (or outside of the group).

**Comment by drmibell** [comment]
On **Selecting a group**, you could consider a border area that shows up when the mouse hovers over it. Not sure how this would work on touch screens, however.

**Comment by rmwiseman** [comment]
I like the idea of holding down shift (or whatever) to allow a node to be dragged from one group to another.  I would suggest that if group A contains group B, then you should be able to drag nodes from group A to group B without holding shift, since the node won't be leaving group A as such; but I would expect you'd need to hold shift to move from group B to group A.  That makes sense in my head, but I'm not sure how normal I am.

There could be a contextual menu option to move a node/selection _from_ a specific group, possibly including the group's ancestors as destination choices (along with "no group" which would be the same as removing from a group altogether).  This would, I suppose, only make sense for nodes that are actually in the same group.  (That said, it probably wouldn't do any _harm_ to allow the selection to include nodes that aren't in the group...)

I'd also like to see a "merge" contextual menu item for where nodes and/or groups are selected.  I initially thought that it might be difficult to decide _how_ (logically) to merge different selections, but thinking about it, it seems obvious:

- a selection including only nodes would be merged to form a new group.
- a selection including only groups (irrespective of the groups' contents) would be result in those groups being merged into a single group.
- a selection including both groups and nodes would result in the groups being merged and the nodes being added to the merged group.

The contents of the groups, as I've suggested, probably doesn't matter, but "inner groups" would be unaffected when merging.  (Possibly a "flatten" option would be useful too, to result in one group containing the nodes from all groups selected, but I probably wouldn't use that much myself.)

I love the idea of doing away with the "active group" concept too, as this often makes me swear at Node-RED when I haven't clicked enough times to move/delete a particular node in the group.  I think its removal would make for much more intuitive and relaxing interaction.

**Comment by knolleary** [comment]
Thanks for the additional comments @rmwiseman 

> then you should be able to drag nodes from group A to group B without holding shift,

Yes, that is what I was trying to describe when I talked about dragging deeper into the hierarchy.

> There could be a contextual menu option to move a node/selection from a specific group

> I'd also like to see a "merge" contextual menu item for where nodes and/or groups are selected. I initially thought that it might be difficult to decide how (logically) to merge different selections, but thinking about it, it seems obvious:

We already have actions for both of these - `Remove from group` and `Merge Selection To Group`. You can access them via the main menu:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/51083/221142553-667804d1-7f40-4b20-8115-906e9392b581.png">

Or the find them in the Action List (Shift-Ctrl-P).

They haven't been added to the new context menu in 3.1, but should be... will make sure that happens regardless of what happens with all of these other proposed changes.

In the case of 'remove from group', it pops the node out of the group its in, into whatever the 'parent' is. So if buried in a hierarchy of groups, it moves it up one level.

**Comment by rmwiseman** [comment]
> We already have actions for both of these - `Remove from group` and `Merge Selection To Group`. You can access them via the main menu

Excellent, I didn't know there _were_ things like that in the menu!  I wouldn't even think to look there for that kind of thing: it always feels like a high-level management menu to me.  That should definitely be in the context menu, I think.  Very useful to know, though, thanks.

> So if buried in a hierarchy of groups, it moves it up one level.

Perfect! :-)

**Comment by rmwiseman** [comment]
I've just noticed another thing about groups that isn't intuitive.  (Sorry!)

If you press Ctrl+a to select everything, then deselect a group (which must contain connected nodes) by Ctrl-clicking its border, then drag another node/group, the deselected group still moves with everything else!  This is because Ctrl+a selects connections, but deselecting the group doesn't deselect them, so anything in the group that's got connections moves too (even things in sub-groups).

**Comment by rmwiseman** [comment]
And another one I've just noticed...

I had a few groups that I wanted to place inside another group to show their relationship to each other.  This I did without any trouble, but when I then changed the background colour of the (new) outer group, I could no longer see the borders or backgrounds of the inner groups.  I tried sending the outer group to the back and bringing the inner groups to the front (via "Arrange" in the menu) but this had no effect.  All I could do was ungroup and each inner group and re-group its nodes.

**Comment by tve** [comment]
A thought: what if groups had _no_ effect on the UI interactions, except to select all contained nodes if the group outline is clicked? I.e. there would be nothing different at all between nodes in groups and nodes outside of groups from a UI interaction point of view.
In order to operate on a group, one would click (double-click?) the outline and that would select all nodes in the group. To move the group it's then no different from moving a bunch of nodes one has selected, for example.
To me, this would be the most intuitive and convenient, then the group acts mostly as just a visual grouping with comments. I don't quite know what problems or missing features this approach would create.

**Comment by knolleary** [comment]
> A thought: what if groups had no effect on the UI interactions, except to select all contained nodes if the group outline is clicked? I.e. there would be nothing different at all between nodes in groups and nodes outside of groups from a UI interaction point of view.

I think that is pretty much what is proposed for this issue in what I wrote above - and I have already got it mostly working locally.
