### ISSUE TITLE
Node Palette fails to load on Safari

### ISSUE THREAD

**Issue by vergissberlin** [node-red/node-red#413]
currently in master all nodes are unavailable.
The list on the left is empty an all existing node on board are labeled with "unknown: unknown"

**I tried to fix it:**
- check file rights
- reinstall node packages
- remove my flow json

**But**
Checkout an older version solved my problemt.
I have used 400f51d921e47e841d2509d0ad057a39f1f71ab5 but the problem I got since yesterday after a git pull. Maybe it would be nice to use a development branch and the master for more stable code?

Thank you!
André

**Comment by scargill** [comment]
Hi
I'm making a brand new installation - starting with NOOB - (Raspbian), adding webmin, mosquitto - all is well (16gig card)... and then I came to install Node-Red. I installed node-red on my other Pi and as you know all is well there.

On this one - node-red-pi -v --max-old-space-size=128 runs - but says it cannot find 'arduino-firmata', 'redis' or 'mongodb'.   I tried npm update and tried installing them manually - same names - looked like something was happening but when I run node-red-pi same issue (it runs otherwise).  Here's the think - in my first installation - node-red is sitting in /PI directory - I can't see it this time... yet if I do a winSCP search for .config.jason -( from the base of the file system) the search says it is in .home/pi/.node-red/  and yet I cannot see that directory - nor in the pi itself can I navigate to that directory from the pi home - ls says it is not there... 

Thoughts?

**Comment by hardillb** [comment]
@scargill Did you mean to append this to the end of this issue or open a new one? The description you've given doesn't seam to match the rest of the issue.

**Comment by scargill** [comment]
Sorry I'd noticed the conversation included missing modules... and assumed I should add this on the end.  Possibly should have been a new issue. As you can see I'm having immense issues with the "new" instructions for Pi2 (didn't ever see anything called node-red-pi when I did my first install on another Pi2). Want me to move this to another new thread?

**Comment by hardillb** [comment]
I think it would be better in a new issue

**Comment by jvasquezwork** [comment]
![image](https://user-images.githubusercontent.com/21188032/27210827-6dc7d5ac-5212-11e7-9c85-58fb2ba64782.png)

I have this issue with Arduino library, what Can I do? I have tryed many things but nothing

**Comment by knolleary** [comment]
@jvasquezwork this is a closed issue unrelated to your problem. Please ask your question on the Node-RED mailing list - link at bottom of nodered.org
