### ISSUE TITLE
Node red does not show newest version for `node-red-contrib-bme280`

### ISSUE THREAD

**Issue by hasenradball** [node-red/node-red#4210]
### Current Behavior

When using node-red and added the following pallette item (**node-red-contrib-bme280**) the item only shows the version v1.0.0 for installation.
But in the npm the newest version is the v1.1.0.

**Why does node-red not show the newest version and dangles at v1.0.0?**
see:
 a) [https://flows.nodered.org/node/node-red-contrib-bme280](https://flows.nodered.org/node/node-red-contrib-bme280)
and
b) [https://www.npmjs.com/package/node-red-contrib-bme280](https://www.npmjs.com/package/node-red-contrib-bme280)

What to do to solve this?

### Expected Behavior

Node-red shows the v1.1.0 for installation.

### Steps To Reproduce

Just go to palette and install bme280...

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 
- Node.js version:
- npm version:
- Platform/OS: raspberian
- Browser:

**Comment by knolleary** [comment]
This is because the author of the module never requested its entry on the Flow Library to be updated to the latest version.

When logged into the Flow Library there is a 'check for updates' button in the sidebar of every page. I have just clicked that button and the entry has been updated to the latest release.

The Palette Manager catalog will be updated by an automated process in the next hour.

**Comment by hasenradball** [comment]
Thanks very much
