### ISSUE TITLE
Crash with environment variable called `length`

### ISSUE THREAD

**Issue by ThePython10110** [node-red/node-red#4213]
### Current Behavior

# Problem/Motivation

Running a subflow with an environment variable called `length` seems to crash Node Red completely. My guess is that it has something to do with JavaScript's `length` functions... but I know almost nothing about how Node Red actually works, so that could be entirely wrong.

## Expected behavior

The subflow runs correctly and does not crash Node Red.

### Steps To Reproduce

1. Create a subflow with an environment variable called `length`.
2. Run it.
3. Node Red crashes.

### Example flow

Subflow:
```
[{"id":"521a056e5cb26d03","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":50,"y":30,"wires":[]}],"out":[],"env":[{"name":"length","type":"str","value":""}],"meta":{},"color":"#DDAA99"}]
```
Flow:
```
[{"id":"521a056e5cb26d03","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":50,"y":30,"wires":[]}],"out":[],"env":[{"name":"length","type":"str","value":""}],"meta":{},"color":"#DDAA99"},{"id":"eecddba75d36c6cd","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"fee33b9772de56b8","type":"subflow:521a056e5cb26d03","z":"eecddba75d36c6cd","name":"","x":240,"y":80,"wires":[]},{"id":"c401b220dba27f8f","type":"inject","z":"eecddba75d36c6cd","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":60,"y":80,"wires":[["fee33b9772de56b8"]]}]
```

### Environment

- Node-RED version: 3.0.2 (Add-on version: 14.2.2)
- Node.js version: 18.16.0
- npm version: ?????
- Platform/OS: Home Assistant
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
I have confirmed this on 3.0.2 as an issue.

On 3.1.0-beta the issue still exists but it does not crash node-red.

The issue is 2 fold:
1. Calling a function on a non object (Not guarding / not type checking)
   * https://github.com/node-red/node-red/blob/5d698d66d0857e65b08be41b212b7bcafe5f8261/packages/node_modules/%40node-red/runtime/lib/flows/Flow.js#L822 
   * See (2) below: The `node` property is actually a boolean not a `Node` object & therefore calling `.receive()` throws.
   * In 3.0.2 this is uncaught
2. Failing to create a sub node (https://github.com/node-red/node-red/blob/5d698d66d0857e65b08be41b212b7bcafe5f8261/packages/node_modules/%40node-red/runtime/lib/flows/Flow.js#L217) and leaving `this.subflowInstanceNodes[id]` set to the value `true` 
   * with `this.subflowInstanceNodes[id]` having a value of `true`, `getNode()` returns a boolean instead of a `Node` object and inadequate logic tests assume the `sendEvent.destination.node` is an `Node` (when it is in-fact a boolean) and proceeds to call `receive()` resulting in an error (3.1.0) or crash (3.0.2).

However the root cause is due to incorrect declaration of the object in https://github.com/node-red/node-red/blob/5d698d66d0857e65b08be41b212b7bcafe5f8261/packages/node_modules/%40node-red/runtime/lib/flows/Subflow.js#L122 
* This should be `env = {}` NOT `env  = []`
* currently, since an array is an object, it works however when you attempt to set an env var to `length:string` it throws an error since the `.length` property of an array object is checked and throws an error when not a valid array size number.

Fix incoming.
