### ISSUE TITLE
Incorrect autocompletion

### ISSUE THREAD

**Issue by DmitrySidorow** [node-red/node-red#4226]
### Current Behavior

![bug](https://github.com/node-red/node-red/assets/43705385/ed4ca95b-42d3-48ff-a4f9-30000d474a23)

### Steps To Reproduce

all on attached gif

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.0 beta 3
- Platform/OS: windows
- Browser: chrome

**Comment by DmitrySidorow** [comment]
also 
![bug2](https://github.com/node-red/node-red/assets/43705385/0324ef56-11cd-439f-8b69-6147928f03b2)

**Comment by Steve-Mcl** [comment]
> also
> ![bug2](https://user-images.githubusercontent.com/43705385/247096421-0324ef56-11cd-439f-8b69-6147928f03b2.gif)

This one is expected behaviour.  `global` object is providing standard completions where as the "set (global context)" and "get (global context)" entries are snippets (aka macros)

![image](https://github.com/node-red/node-red/assets/44235289/0ec1e0a9-0456-4944-9ce8-ac23d6728b91)




> ![bug](https://user-images.githubusercontent.com/43705385/247094715-ed4ca95b-42d3-48ff-a4f9-30000d474a23.gif)

This doe look odd - but it is difficult to tell from the gif what you are doing (do you click an entry? press TAB? or enter? move the dropdown menu selection etc).  Please list out exact steps so I can recreate and check this  out.

**Comment by Steve-Mcl** [comment]
Lastly, I cannot recreate this in 3.1.0-beta.3 without some deliberate _misoperation_


### V3.1.0-beta.2 - normal usage
https://github.com/node-red/node-red/assets/44235289/19f91adb-44d7-4e97-88ab-801e90c2f8d5

### V3.1.0-beta3 - normal usage
https://github.com/node-red/node-red/assets/44235289/b71a4778-b1dc-4474-ac00-3eb2388c5e54

### Tricking it through _incorrect usage_
https://github.com/node-red/node-red/assets/44235289/da0ee71e-2432-477b-ae2e-69c5916522fd


### VSCode (Monaco is the editor powering Node-RED and VSCode Function Node)
In fact, what I did above is possible in VSCode too.  

https://github.com/node-red/node-red/assets/44235289/f23f6ee6-eebd-449d-8ec7-c9a3440542cc


---

Unless you can provide exact repeatable steps, I cannot advise nor fix this I'm afraid.

**Comment by Steve-Mcl** [comment]
Closing due to lack of response. Feel free to reopen if you can provide the requested info.
