### ISSUE TITLE
 node module "fs/promises" not working as expected in "function"

### ISSUE THREAD

**Issue by fullmooooon** [node-red/node-red#4446]
### Current Behavior

23 Nov 17:30:05 - [red] Uncaught Exception:
23 Nov 17:30:05 - [error] TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at makeCallback (node:fs:187:3)
    at Object.access (node:fs:231:14)
    at Function node:58e807d6661f2188 [function 109]:3:16
    at Function node:58e807d6661f2188 [function 109]:4:3
    at Function node:58e807d6661f2188 [function 109]:8:3
    at Script.runInContext (node:vm:134:12)
    at processMessage (C:\Users\mUesr\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\nodes\core\function\10-function.js:419:33)
    at FunctionNode._inputCallback (C:\Users\mUesr\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\nodes\core\function\10-function.js:342:17)
    at C:\Users\mUesr\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:210:26
    at Object.trigger (C:\Users\mUesr\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\util\lib\hooks.js:166:13)

### Example flow

```
[{"id":"174c107e029d1b65","type":"inject","z":"47e4ae2f2eb72fa7","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":350,"y":1400,"wires":[["58e807d6661f2188"]]},{"id":"58e807d6661f2188","type":"function","z":"47e4ae2f2eb72fa7","name":"function 109","func":";(async ()=>{\n    fsPromises.access(\"c:/\")\n})()\n\nmsg.payload = 1\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"fsPromises","module":"fs/promises"}],"x":590,"y":1400,"wires":[[]]}]
```

### Environment

- Node-RED version: 3.1.0
- Node.js version: v20.8.0
- npm version: 
- Platform/OS: win 11
- Browser:

**Comment by fullmooooon** [comment]
not crash. But it's not the expected result.
```
fsPromises.access('c:/')

msg.payload = 1
return msg;
```

2023/11/23 17:52:08[node: function 109   http://127.0.0.1:1880/#)
function : (error)
"TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined"

node-red  crash
```
;(async ()=>{
    fsPromises.access("c:/")
})()

msg.payload = 1
return msg;
```

**Comment by hardillb** [comment]
This looks like the function node is returning the `fs` object not the `fs/promises` object so the sync versions should work as workaround.

Looks like we might need to look at how the function node loads modules with ` /` in them

**Comment by fullmooooon** [comment]
To solve the problem , using function on `fs.promises` 
`await fs.promises.access(filePath)`  work OK

The downside is that `fs.promises.` Missing type prompt in the node-red editor

**Comment by Steve-Mcl** [comment]
@hardillb The issue is around `parseModuleName` in file `packages/node_modules/@node-red/registry/lib/externalModules.js` 

It returns a `parsedModule` with `module` = "fs" & instructs the import to use that instead of `fs/promises` (which is in the `spec` property.

![image](https://github.com/node-red/node-red/assets/44235289/020787b7-4ad4-4b3b-bf59-17f7ec1be97f)


As a quick test, I forced the core to use `fs/promises` and it imported fine (and the editor VM was happy)

I am not certain at this point what the correct resolution is at this moment but we have a starting point to look.

Tagging this as a bug.

<br>


@fullmooooon 

> To solve the problem , using function on fs.promises
> await fs.promises.access(filePath) work OK
> 
> The downside is that fs.promises. Missing type prompt in the node-red editor

You can use typedoc to tell the editor what the object is

![image](https://github.com/node-red/node-red/assets/44235289/e2d0046b-a713-43f7-adad-7d4e44208f67)
