### ISSUE TITLE
Hidden scope dropdown in config node editor

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#4497]
### Current Behavior

On some config nodes (both core and contrib) the config node window is missing the scope dropdown (All Flows/individual subflow) at the bottom right.  Enlarging the window allows the dropdown to appear.  See [this thread](https://discourse.nodered.org/t/missing-actually-hidden-context-pop-up-in-config-node-editor/83999/3) in the forum for an example of the problem in the http tls config node. The problem can also be seen in node-red-contrib-influxdb, for example.

### Expected Behavior

The scope dropdown should be visible on initial opening.  Perhaps it would be better if the 'nodes use this config' text was truncated if the window is too narrow rather than losing the dropdown completely.

### Steps To Reproduce

See the forum thread.

### Environment

- Node-RED version: 3.1.3
- Node.js version: 20.5.1
- npm version:
- Platform/OS: Laptop/Ubuntu 22.04
- Browser: Edge

**Comment by GogoVega** [comment]
Caused by the `red-ui-editor-config-user-count` length which varies depending on language and count.
Should make its length flexible and combine it with `text-overflow: ellipsis;` so that all footer elements are aligned and the text is hidden in case of overflow.

PS: not good enough in css to make a pr 😅
