### ISSUE TITLE
Cannot enable disabled nodes in a group

### ISSUE THREAD

**Issue by structure7** [node-red/node-red#4827]
### Current Behavior

With a group of disabled nodes selected, _Enable selected nodes_ cannot be clicked.

<img width="582" alt="image" src="https://github.com/node-red/node-red/assets/17578192/14dd33c6-2fe1-4da6-9667-badc4c3e8fc0">

### Expected Behavior

Right-clicking on a group of disabled nodes, clicking _Nodes_, then _Enable selected nodes_, should enable all nodes in the group.

### Steps To Reproduce

1. Select a group of nodes, right-click, click _Nodes_, click _Disable selected nodes_. All nodes in the group disable as expected.
2. Deploy (or not).
3. Right click the disabled group, click _Nodes_. _Enable selected nodes_ cannot be clicked.

Individual nodes **can** be selected and enabled.

### Environment

- Node-RED version: 4.0.2
- Node.js version: 18.20.3
- npm version: 10.7.0
- Platform/OS: Ubuntu 20.04 LTS
- Browser: Chrome 126.0.6478.127 (Official Build) (arm64)

**Comment by GogoVega** [comment]
This is a direct consequence of no longer selecting all nodes inside the group when clicking on the group.

It's possible to disable selection because the group does not have `d` property but enable selection is not possible because the group will never have `d` property.

We must therefore find that it's a group and search in its nodes.
