### ISSUE TITLE
Weird behavior after adding a node using the context menu

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4881]
### Current Behavior

If you right-click in the workspace, select Insert > Node from the context menu, and then select a node in the quick-add dialog, that node will be added to the workspace with a wire automatically connected to its port. But the only way to use that wire is to either connect it to another node (if you already have one in that flow) or right-click again and select Insert > Node to add another node.

~Also, there is no way to "cancel" that wire.~

EDIT: The wire can be removed if you hit the `ctrl` key.

### Expected Behavior

The quick-add should appear at the other end of the wire ~, and it should be possible to remove that wire without having to connect it to another node first~.

EDIT 2: Actually, the node should be added without a wire automatically connected to its port, just like when we add a node by dragging it from the palette or using the quick-add dialog.

### Environment

- Node-RED version: 4.0.2
- Node.js version: v20.17.0
- npm version: 10.8.2
- Platform/OS: macOS Sonoma 14.6.1
- Browser: Safari, Chrome, Firefox

**Comment by GogoVega** [comment]
> Actually, the node should be added without a wire automatically connected to its port

No, I would say the problem is that clicking on the canvas does not trigger the QuickAddDialog. In addition there is a missing handler on the escape key to hide the drag line.

For now the ctrl (or cmd) key destroys the wire but I think it is a coincidence.

I also notice that the QuickAddDialog is triggered without simultaneously pressing ctrl (if I pull a wire from the output of a node to nowhere), is this normal? I don't use it often so I don't know if this is its intended behavior.
