### ISSUE TITLE
Lock icon disappear when deploying

### ISSUE THREAD

**Issue by 78wesley** [node-red/node-red#4888]
### Current Behavior

When I lock a flow from the information sidebar and I click on deploy (it doesn't matter which one) the lock icon of the flow disappear and comes back when I fully reload the site.

### Expected Behavior

Flow locked Icon should still be visible when clicking on Deploy.

### Steps To Reproduce

1. Click on the lock icon of a flow from the information tab.
2. Click on Deploy (doesn't matter which one).
Now lock icon disappeared from the flow that needs to be locked.

### Environment

- Node-RED version: 4.0.2
- Node.js version: 20.17.0
- npm version: 20 I guess
- Platform/OS: FlowFuse
- Browser: Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)

**Comment by GogoVega** [comment]
The `ensureUnlocked` function creates a conflict because when the event is triggered the `locked` property is false and then the loop below locks the workspace.

https://github.com/node-red/node-red/blob/a3c5b75368efcbdac690e4d3e2d0b54ece117c74/packages/node_modules/%40node-red/editor-client/src/js/ui/deploy.js#L651-L661

**Comment by GogoVega** [comment]
I'm preparing a fix 😉
