### ISSUE TITLE
Dynamic Info Tab 

### ISSUE THREAD

**Issue by cpedrinaci** [node-red/node-red#492]
In some cases it may be interesting to provide some detailed documentation about a node that may depend on its actual configuration (and therefore can't be entirely pre-defined on the node).

For those cases it would be interesting to offer means for updating the information that would go on the info tab easily. 

This would notably be interesting for showing how a node is expected to behave given its current configuration without having to go an edit it. Just selecting it would show the relevant information on the info tab.

This could possibly be implemented through an 'onnodeselect' event.

**Comment by gillerman** [comment]
I have a related issue.  I want to create a dynamic info tab or add my own custom tab.  The functionality I am providing is similar to a tree control that allows a user to browse for specific item.  Instead of requiring the user to enter a filename in a node property manually, I want to enable the user to browse the local files and select the one they want.  This is just a simple example, in general, I need to run a GUI in the sidebar and allow a item selected in the GUI be used to populate a node property.

Thank you,
John

**Comment by mikakaraila** [comment]
I just tested info tab and I did not get drag&drop working. This could be really fast way to populate flow with good parameters. Config tab does not allow drag&drop / copy either.

**Comment by gillerman** [comment]
Mika, I very much agree.  This would make Node Red much easier to configure.

**Comment by knolleary** [comment]
@mikakaraila so I'm not misunderstanding, could you confirm what you mean by Config tab? Do you mean the Info tab in the sidebar?

The edit dialog is modal, so you cannot interact with other UI elements whilst it is open. So any UI related to configuring a node needs to be contained within the edit dialog.

I am (painfuly) aware that you cannot copy text out of the side bar, as Ctrl-C is grabbed to copy the selected nodes in the workspace. This is on my todo list to fix.

**Comment by mikakaraila** [comment]
Info tab / sidebar & config are acting in the same way, I tested copy as one alternative to build up new flow quickly. My idea was to use it as list to insert new node with good parameters. If you solve copy problem, I could perhaps build up list so copy action will use json that contains those parameters...

**Comment by mikakaraila** [comment]
This specific problem what I had is already solved, but as you get copy working send me a note. Thanks!
