### ISSUE TITLE
Since 4.0.6 and also with 4.0.7 update, all dashboard (v2) ui_tabs are marked as unused

### ISSUE THREAD

**Issue by m-schaeffler** [node-red/node-red#4999]
### Current Behavior

I have the issue from https://github.com/node-red/node-red/issues/4994 still with nodered 4.0.7!

node red editor shows all the dashboard 2 items as unused at deploy.

### Expected Behavior

no nodes shown as unused

### Steps To Reproduce

do a deploy

### Environment

- Node-RED version: 4.0.7
- Node.js version: 20.18.1
- npm version:
- Platform/OS: Raspbery Os
- Browser: Firefox 133.0.3, Win10

**Comment by hardillb** [comment]
I'm not seeing this with a fresh install of 4.0.7 and Dashboard V2.

Just to been 100% clear, you have done a full reload of the editor before testing (shift-f5)?

**Comment by m-schaeffler** [comment]
Yes, will try later on another Computer with Ubuntu

**Comment by m-schaeffler** [comment]
Yes, I have still this issue also on a 2nd Computer.
I have only updated node-red with npm -g update

**Comment by hardillb** [comment]
Please provide step by step instructions to reproduce it from an empty flow

**Comment by m-schaeffler** [comment]
Also after reboot of the node Red machine

**Comment by knolleary** [comment]
I can recreate.

Starting with 4.0.5:

1. Install `@flowfuse/node-red-dashboard`
2. Drag on a button node - it automatically creates the various tab/group/page config nodes. Deploy and reload the editor
3. Open config node sidebar. It shows the user count of all the dashboard config nodes:
    <img width="135" alt="image" src="https://github.com/user-attachments/assets/235c15f2-fb2e-4344-b08e-bcc0e3b0d3ac" />
4. Restart on 4.0.6 (that had the original bug). Reload the editor. Observe the user counts are `0`. This is what we thought 4.0.7 fixed.
    <img width="135" alt="image" src="https://github.com/user-attachments/assets/bfffa3e1-8454-4524-8cea-d026eafe4b79" />
5. Restart on 4.0.7. Reload the editor. Note the `ui-page` config node still shows 0 users
    <img width="136" alt="image" src="https://github.com/user-attachments/assets/44c22112-4e8a-46c0-830c-1b20b6e462f7" />

**Comment by knolleary** [comment]
I think the issue is related to this part of the previous fix: https://github.com/node-red/node-red/pull/4995/files#diff-8dd97189c96d498a6a650efdc08f100e4ebe018a3ebbb92b1fd5fb7de2095262R2199-R2210

This code sorting the config nodes so that when a user of a config node is added, the config node already exists to have its users count updated. It's the right idea, but the sort logic is flawed as it just bases it on how many config node references a node contains - it doesn't consider the actual directed graph of relationships between the nodes.

I'll work on a fix tomorrow and we'll have 4.0.8 to kick-off the weekend.
