### ISSUE TITLE
CoAP support

### ISSUE THREAD

**Issue by reederz** [node-red/node-red#529]
Hello Everybody

We, at [gatesense](http://gatesense.com), are working on CoAP support for Node-RED. Would you be interested in PR into core?

You can find the code [here](https://github.com/gatesense/node-red-contrib-coap).

**Comment by knolleary** [comment]
Hi, thanks for this.

We already have issue #248 for exactly this.

Rather than pull these into the core of node-red, I suggest you self-publish them to the npm repository where anyone will be able to install into their node-red runtime should their want CoAP support.

I suggest you also publicise this on the node-red mailing list as I'm sure there will be interested people on that list who don't follow the day-to-day issues over here.

Nick

**Comment by reederz** [comment]
Hi Nick,

I've done that. Here's the [mailing list link](https://groups.google.com/forum/#!topic/node-red/YwDKVIT8TmQ) for reference. 

/Justas

**Comment by mcollina** [comment]
@knolleary just for clarity, if a CoAP node is better located in its own module, then we can close #248. The actual outcome there was 'can someone do it?', because it is done, and if wanted @reederz can submit that PR.

A module in 'core' has much more visibility than a module in NPM, as these are not listed on the website and in the README. How about making more public (maybe in README and in the web page) the fact that there are community modules on npm by adding a link to the [npm search](https://www.npmjs.com/browse/keyword/node-red) page? The last sentence in a blog post is not enough. Another option is curating a wiki page: for LevelUp we have a list of all modules: https://github.com/rvagg/node-levelup/wiki/Modules

**Comment by knolleary** [comment]
@mcollina yes, #248 can be closed as they have published their node to npm

We have added links to the npm search page in a couple places, but I agree we need to make it more obvious.

At some point we will add the ability to search/install nodes into the editor itself. The underlying  runtime APIs are in place, just needs the editor UI work to be done.
