### ISSUE TITLE
keyboard shortcuts not working when first loaded into iframe.

### ISSUE THREAD

**Issue by evelynsha** [node-red/node-red#540]
I have a problem using node-red in iframe. When first loaded into iframe, the keyboard shortcuts don't work, but, if I open an edit dialog and then close it, the shortcuts would be fine. Seems that the opening and closing activates something related to shortcuts.

**Comment by evelynsha** [comment]
Fixed, call $("#iframe").focus(); solved the problem.

**Comment by knolleary** [comment]
@evelynsha given your fix, I'm not sure there is an actual issue here. You have to give the iframe focus before it'll receive keyboard events. Clicking to open an edit dialog gives the iframe focus - hence why the shortcuts then worked.

Unless you think there is still something for us to look at, I'm going to close this issue.
