### ISSUE TITLE
Ability to detach Debug tab to new window

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#545]
The debug tab has a number of restrictions:
- it crops the output to avoid flooding the sidebar
- it can get a bit cramped

It would be useful to be able to detach the debug tab to a separate window. With the additional space, we can provide options to better format the output for legibility, display complete messages etc. Should consider the functionality of the Chrome developer tools console for exploring messages.

Something to consider - does it make sense to support detaching any tab into its own window, of which this would be one use?

**Comment by TotallyInformation** [comment]
Personally, I think the most critical issue of the debug sidebar is the ability to clearly see formatted JSON output since NR has such a dependency on it and it can be very confusing for non-programmers in particular.

So something like the standard output from the debug node to the sidebar but with a link that pops out a secondary window containing a JSON pretty-printed version of the output. Perhaps that could be further enhanced with detection for strings containing backslash characters (\n, \t, \r, etc) and formatting those too. If you wanted to be really clever, it could also detect HTML and have a switch to go between the raw text and a preview but really, it is the JSON bit that is important as that is so bloomin hard to read as a string.

Not sure about the other tabs:
- Debug tab - certainly makes sense, even if the above suggestion is adopted. I find myself with an SSH window open as well showing a tail of the out.log from the server (I use forever in daemon form to run NR at the moment).
- Config not really used it much though I can see it would suffer from the same problem if stuffed with JSON.
- The node template list - well, this is already crowded! Probably more sensible to make that variable width however and scrunch the icons into multiple columns when space allows. That will help enormously as the number of node types increases as it surely will.
- The workspaces - Hmm, interesting thought. Could be useful when you get to really complex layouts with many hundreds of nodes. I'm guessing not really a priority though, at least at present.

**Comment by maiorfi** [comment]
I think reworking debug tab would be really great, while workspaces
a..."nice-to-have".

Thanks.

**Comment by knolleary** [comment]
@TotallyInformation  Just to clarify, and to get terminology aligned, by 'node template list' I assume you mean the 'node palette' down the left side? (I've seen you use this term in a couple mails and I couldn't determine exactly what you meant from the context there )

Right now, I'm only thinking about sidebar tabs - and really, only the debug tab. The others were purely a musing over how much of this code should be specific to debug, or generic in a tab code.

I think making the workspace tabs separable into their own windows adds a bunch of usability issues - does each one get its own palette instance, what if you haven't detached the debug pane - does each get its own debug panel... where is the deploy button all of this time. Lots of questions, I'm sure they are answerable, but I just don't want to spend an cycles on it right now.

**Comment by TotallyInformation** [comment]
Sorry, bad habit. Yes, the node palette. I'll try to use the correct terminology. The made up name came from the way I think about how you have "templates" for "node instances". Seems a logical terminology because I note that many people overload the term "node" to mean all of: the code used to control the node, the template in the palette and an actual instance of the node on a workspace. Apologies for the confusion.

I agree that dealing with the workspaces would be hard. And with little immediate benefit. I was just thinking through the whole interface.

**Comment by emiloberg** [comment]
Not to overly simplify things, but why not just use the browser console? All browsers have them and showing debug messages is kind of their area of expertise.

How about: Leave in the 'debug tab' option for the not-at-all-techies, rename the 'console' option to 'server console' and add a 'browser console' which `console.dir` / `console.info` / `console.warning` / `console.error` / `console.table` / `console.whatever`.

Might want to check out https://github.com/icodeforlove/Console.js

**Comment by knolleary** [comment]
That certainly is an option for just making it easier to view the messages. But it would lack the close integration with node-red - highlighting the relevant node on hover etc.

We haven't fleshed it out yet, but it feels like there are other debug capabilities we could add in if the tab had more room - which we wouldn't be able to do in the browser console.

Need to think what use cases the debug tab is there to satisfy - and whether directing users to the browser console is the right answer as soon as they want to do something a little bit more involved.

**Comment by TotallyInformation** [comment]
The browser console is very developer oriented and not at all friendly to non-developers. It can also get quite busy and could get messages about the UI instead of those from the nodes so may get very confusing. 
I really like the idea of a visible debug window for node output, allowing it to display in its own window would give plenty of room and help folks like myself who generally use multiple monitors.
A pretty-print capability for JS objects and JSON - including collapsable heirarchy allowing drilling into the structure of the object would be fabulous. JS objects get complex real quick! Very hard for non-programmers to understand. I know I've seen a library that does this browser-side and I've used it in the past before the browser consoles got better - sadly, I can't remember the name of it.

**Comment by Belphemur** [comment]
About the cropping of the message, it would be nice to be able to click on an item on the debug list and having a modal opening with the full message. That way you do keep the interface clear, and if the user need more detail, he just need to click the message.

**Comment by TotallyInformation** [comment]
@Belphemur - hopefully NOT a modal box as this would prevent access to the UI while it was open. Just another non-modal window.

**Comment by Belphemur** [comment]
@TotallyInformation Right. I was thinking using the dialog of JQuery UI : http://api.jqueryui.com/dialog/#entry-examples

Since it's already in the dependencies of the UI. Also linking the clean debug to close all the opened dialogs.

**Comment by knolleary** [comment]
Right now, the plan is to enable the debug tab to be separated to its own Window - not dialog - and that messages are fully explorable within that window without resorting to dialogs.

**Comment by scargill** [comment]
A separate sidebar debug window would be GREAT - and as mentioned elsewhere the abililty to see formatted json where appropriate would help.  I just looked at a weather node - sent the data to the debug window - firstly there was too much info for the debug - I've since increased the default size markedly - but secondly - such info is often presented in a bit of a mess - some formatting would help immensely - after all - the purpose is to debug so the clearer the debugging information, the better.

**Comment by TotallyInformation** [comment]
I know it isn't as good, but my example debug flow allows you to push any msg to a web page dynamically. It's a workaround I use a lot. You need to set a topic because the page will show all data by topic so that you can leave it running and always see the latest output.

There are also a couple of plugins for Chrome if you use that as a browser. They auto-format and can check for errors in JSON. So there is definitely code out there that will do what we would like. In the past, I also used a library that output a JS object as a full expandable structure the same as the browsers console view of a JS object.

**Comment by scargill** [comment]
Example debug flow? I'm not seeing any flow above??

**Comment by TotallyInformation** [comment]
Sorry Peter, it is in the flows library: http://flows.nodered.org/flow/b0fcb7b72fc05a30e55b

**Comment by scargill** [comment]
Ok I’m both excited and frustrated.  I have Mosquitto with websockets..

 

I added in your subflow and the main flow…  I used an inject node to send the time and topic “stuff”.

 

I started Node-Red and sure enough at 192.168.0.20:1880/debug there is a page that say “Node-Red Debug” – but when I press the inject… nothing changes..

 

What bit am I missing?

**Comment by knolleary** [comment]
Please take this to the mailing list - it is not adding anything to the issue.

**Comment by nkolban** [comment]
As per this forum post:  https://groups.google.com/forum/#!topic/node-red/IevLOSzimyI

I'd like to suggest that the debug area be able to be paused with a visual indicator (a button for example) to allow me to read the data.  This should suspend scrolling.  Data should continue to be collected.  After being paused, auto scrolling should be allowed to be resumed.

**Comment by scargill** [comment]
Seems reasonable to me?

**Comment by gregeva** [comment]
1. In addition to @nkolban 's suggestion for a play/pause button for auto-scroll, I do like @dceejay 's idea of pausing auto-scroll when you scroll up a bit in the window.  This isn't always desired however, as sometimes you want the debug window to jerk your attention back to it when a new message arrives.... sort of depends on verbosity and type of message you may be expecting.

1. I would also suggest a horizontal bottom of window type approach as an option.  I greatly prefer this way when you are trying to read the data contained within a message as you can see most of it and each line does not take up too much vertical space, whereas in a vertical side-bar approach each entry takes up more [precious] vertical space and message clipping will happen after a limited amount of data is displayed.

1. I also really like the idea of being able to filter what is being displayed.  Presently when working on something I will uncomment console.log lines in certain function nodes and enable certain debug log nodes in order to provide a clear picture of many things for the specific functionality I am working on, and will later disable and re-comment them once finished debugging.  Being able to have a sort of functionality tag which I could apply to debug nodes, as well as to console messages, would enable selecting these tags/categories in the actual debug console.  This would be pretty great because you could control debug verbosity by only selecting parts of your flows.

**Comment by chevdor** [comment]
isn´t that now in?
![image](https://user-images.githubusercontent.com/738724/31058690-f96469ec-a6f7-11e7-940a-5401b785950c.png)

**Comment by knolleary** [comment]
Good point - yes!

**Comment by scargill** [comment]
Will you look at that!!! I didn't know you could open a separate debug window... you learn something new every day...

**Comment by aniston** [comment]
Using node-red v0.17.5 in Windows 7 x64 and nodejs v6.11.2  in a Firefox ESR 52.04.0.
First, lovely work on the floating Debug window, actually missed my attention until this issue, however..

Opened the Deubg in a new window then deactivated the "View > Show Sidebar" option and rightfully have the new FF Debug window with 'all nodes' Debug information, but setting the Debug filter to show 'current flow' does not obey the Filter, is this by design (works in the Debug sidebar though) or a flaw?

+ The issue of showing JSON atleast as a pretty print will be very helpful as stated by @scargill to help Debugging.

I found that the only way to call a closed floating Debug window was by reactivating the "View > Show Sidebar" option , is there a possible hot-key setting else the option has to be set and unset incase of accidental closure 8not a problem but just asking).

Another observation , is there a way to keep the floating Debug FF window pinned down like in a 'alwalys on Top' option or is that only FF/Browser related ?

regards,
aniston

**Comment by rsuraparaju** [comment]
Picking up on this old issue, is it possible to add a feature to stream debug data to different targets for each flow ? 
For example, if I have two flows running, Flow A, Flow B, I want to capture the debug data for Flow A in flowA.log file and debug data for Flow B in flowB.log file.
This will help in inspecting the logs separately for each flow, making it easier to understand/debug.
If this already exists, I have missed it - someone please point me to it.
regards
Rajesh

**Comment by knolleary** [comment]
@rsuraparaju adding a comment to an issue that has been closed for almost a year isn't the ideal way to propose a new feature that's tangentially related to the issue.

Please use the node-red forum, linked to from the bottom of nodered.org
