### ISSUE TITLE
JQuery Support In UI

### ISSUE THREAD

**Issue by mboldisc** [node-red/node-red#547]
I'm having trouble getting simple tabs working in a custom node.  Here's the example I pasted into my ".html" file:
http://jqueryui.com/tabs/

Is there support for using JQuery in the UI?  If not, it would be a nice enhancement.  Maybe JQuery operations would have to be done on classes instead of IDs since there could be multiple nodes with the same IDs in the flow?

**Comment by knolleary** [comment]
Hi,

we use jQuery extensively in the UI, including the edit dialog - but have never tried using tabs in the edit dialog.

What actual problems are you hitting?

**Comment by mboldisc** [comment]
I am trying to fit lots of fields into a small node dialog.  Tabs would really be useful to organize the input fields.

**Comment by mboldisc** [comment]
Or, are you asking what the problem is with the code?

**Comment by knolleary** [comment]
You say you have having trouble... that doesn't give me a lot to go on :) It could be user error, it could be a bug, it could be something else entirely.

Can you provide any concrete details of what you have tried and what results you are getting.

**Comment by mboldisc** [comment]
The JQuery call doesn't execute when I put it in the script tag.  I've also tried removing the function wrapper, but it also didn't work.  I can tell it's not running because none of the example tab HTML receives JQuery classes and formatting.
<script type="text/javascript">
$(function() {
    $( "#tabs" ).tabs();
  });
</script>

**Comment by knolleary** [comment]
You cannot nest a script tag within the script tag the contains the node edit template.

You must defined an 'oneditprepare' function on the node definition that gets called when the node's edit dialog is being constructed. That can contain the jquery calls you want to make. You should also try to use namespaced ids for your form elements - otherwise you do risk clashing.

Here are the docs that talk about customising the edit dialog - http://nodered.org/docs/creating-nodes/properties.html

Here's an example of a node that creates some  jquery ui elements in its edit dialog: https://github.com/node-red/node-red/blob/master/nodes/core/core/80-function.html#L70

**Comment by mboldisc** [comment]
Wow.  Great example!  That should work perfect for my simple tabs.

**Comment by knolleary** [comment]
Great - going to close this issue then. If you have any general questions, you can use the [mailing list](https://groups.google.com/forum/#!forum/node-red).
