### ISSUE TITLE
Inject module v0.10.1 generates wrong crontab lines? 

### ISSUE THREAD

**Issue by ThierryP** [node-red/node-red#564]
### Inject modules in v.0.10.1
in 'interval between times' mode it generates crontab lines with 4 arguments instead of 5, eg for 5 minutes and 60 minutes intervals it generates:
```
crontab = */5  * * *
crontab = 0  * * *
```
(note extra space between arguments) which gives strange effects on timing.
'repeat' and 'at a specific time' mode seem to work OK.
Importing flows with Inject modules from v.0.9.1 also worked OK in v0.10.1 as long as they're not changed in settings in v0.10.1:
```
crontab = */5 * * * *
crontab = 0 * * * *
```
Thierry

**Comment by knolleary** [comment]
This was broken when the days select box was replaced with individual checkboxes. Whereas the default option was 'every day', the default selection is now nothing selected - which is invalid and results in a blank day argument in the crontab.

Updating the node so that it defaults to all days selected, plus some better error handling to handle invalid choices.
