### ISSUE TITLE
Node v0.12 Support

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#565]
Issue to track adding support for node 0.12 within node-red.

Added 0.12 to the travis config in a branch [here](https://github.com/knolleary/node-red/tree/node12). As of today, it fails [thus](https://travis-ci.org/knolleary/node-red/jobs/49884890).

Adding 0.12 support will require an extensive regression test of our nodes to ensure we hit as many code paths as possible - as we don't have comprehensive unit test coverage of all nodes yet.

If/where we discover 3rd party node modules that require an update, we should add a comment here to track the dependency.

**Comment by Frozenfire92** [comment]
+1

**Comment by Glavin001** [comment]
+1

**Comment by cainjonm** [comment]
I highly suspect the error "Fatal error: argument entity must be string, Buffer, or fs.Stats" is caused by https://github.com/isaacs/node-graceful-fs/issues/35 - assuming graceful-fs is somewhere in your node_modules.

(I was running node-red with 0.12 without realising, and i eventually found the cause of this error to be a dependency of a dependency requiring this module...)

**Comment by vielmetti** [comment]
node-graceful-fs is pulled in by node-fs-extra as noted by @cainjonm . There's a bug reported at https://github.com/jprichardson/node-fs-extra/issues/120 with a workaround involving shallow cloning.

**Comment by vielmetti** [comment]
Note that it's not currently possible to find an 0.10.x release of node.js for Arch Linux ARM, which I ran into tonight trying to build a Docker image of Node-RED for my Raspberry Pi. That open issue is https://github.com/nieleyde/rpi-nodered/issues/1 .

I think that the long-outstanding first failure in the Travis CI gets fixed by https://github.com/node-red/node-red/pull/657 (and I'm going to wedge that into my Docker build).

**Comment by aditanase** [comment]
If it helps, I've been running 0.10.6 on a raspberry pi 2 with node 0.12.0 for over a week now, no issues.

Only issue I encountered was with a npm module (netping) that was relying on rawserial that does not work with 0.12 yet.

Otherwise using mqtt (20-30 topics), http in/request, pushover, udp, tcp, and it's stable - no restarts in the last week.

**Comment by vielmetti** [comment]
As of this build 7 days ago

https://travis-ci.org/knolleary/node-red/builds/69656937

Node-RED's "knolleary/node-red:node12" branch passes its tests for node 0.12.6. Yay!

**Comment by knolleary** [comment]
@vielmetti and all those changes were merged under #697 - so this repo passes on 0.12 as well - https://travis-ci.org/node-red/node-red

**Comment by dceejay** [comment]
which is actually now 0.12.7....  though at some point we will have to fix/pin it...

**Comment by vielmetti** [comment]
Ah, 0.12.7 is a bug fix because of (yet another) openssl issue, that would be a good revision to pick up.

**Comment by knolleary** [comment]
We have no reason to pin to a specific version of 0.12 - we didn't do that with 0.8 or 0.10. In fact, the existence of 0.12.7 with its critical openssl issue is exactly why we shouldn't pin the version.

**Comment by vielmetti** [comment]
Thanks @knolleary - I guess that whenever Travis updates something that it will automatically pick up 0.12.7 as the new test environment just as a matter of course?

(And I see that there's also an "iojs" target on Travis but I don't want to open up another epic issue)

**Comment by dceejay** [comment]
Hopefully io.js and node.js will re-merge in the 0.14 timeframe...

**Comment by vielmetti** [comment]
For grins I added an "iojs" target to Travis in a branch. It passed a whole bunch of tests but then gave out in the "89-trigger.js" node. The build detail is here

https://travis-ci.org/vielmetti/node-red/builds/70741592

and the error is

```
Fatal error: Cannot assign to read only property '_onTimeout' of infinite
```

I don't understand the internals of what it's doing there well enough to know if it's a simple fix, but here's what looks like the offending line:  https://github.com/node-red/node-red/blob/master/nodes/core/core/89-trigger.js#L67

**Comment by knolleary** [comment]
Interesting - thanks for that. Good to know we're close.

**Comment by vielmetti** [comment]
It looks like the next release of node.js is 4.0.0, here:

https://github.com/nodejs/node/releases/tag/v4.0.0

If that numbering looks weird, it's because as far as I can tell from reading release notes, this reflects a merge of the io.js and node.js branches under the surviving node.js name.

**Comment by knolleary** [comment]
Yes, we're following that. As soon as Travis add it to the list of available runtimes, we'll be adding it the list we test.

Oh, and we added 0.12 support in the last release, so we can close this issue.
