### ISSUE TITLE
Nore-red in clustering model

### ISSUE THREAD

**Issue by github4f** [node-red/node-red#580]
I have used the twitter.js social module in one of my project which involves a server. Now due to large number of users (each user needs its own twitter polling), I need to perform clustering to divide the jobs between different servers (different physical machines). 

I already read about the "cluster" module, but, from what i understood, it seems to scale only on multiprocessors on the same machine.

My question: is there any suitable distributed module available in Node.js for my work? What about Apache mesos? I have heard that mesos can abstract multiple physical machines into a single server? is it correct? If yes, it is possible to use the node.js cluster module on top of the mesos, since now we have only one virtual server? 

Thanks

**Comment by hardillb** [comment]
I don't see what this has to do with Node-RED

**Comment by github4f** [comment]
Assume, I need to run the nore-red in a cluster. I think, now the nore-red only uses one core! My question is that how I can modify the node-red to use all the cores of the cluster (my cluster consists of different physical machine and each machine consists of various processing cores). Thanks

**Comment by hardillb** [comment]
This is not a Node-RED issue, you may get some useful input from the mailing list, but this is not the venue for this sort of discussion.

Node.js is single threaded by design, as such Node-RED running on top of it will also run in a single thread.

**Comment by github4f** [comment]
I respect your point of view. However, I believe it is a major issue of node-red, since it cannot be scaled!

**Comment by knolleary** [comment]
@github4f  thanks for raising this.

There may be something to look at with the cluster module and whether we can meaningfully automatically distribute node instances across cluster instances. But that is a pretty major change to the architecture of node-red and not something we'd consider lightly.

From what you describe, our recommended approach is to run separate node-red instances for each user. That ensures proper resource isolation between the users - otherwise one user's flows could starve another user's flows.

As per our contributing guidelines, we prefer to keep the issue list as specific bugs that need fixing, or features we have in the plan. We prefer to have this sort of discussion on the mailing list where we can discuss it with the wider community.
