### ISSUE TITLE
Bcrypt vs Bcryptjs

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#585]
as noted in the google group - https://groups.google.com/forum/#!topic/node-red/V7_aFjtpEVE - the performance of bcryptjs on Pi is not exactly stellar.... we should optionally include the bcrypt library that needs compiling for platforms hat support gyp easily and fall back to bcrypt for those that don't (windows).

As the API is the same it should just be a case of adding bcrypt as an optionalDepedencies in package.json and adding a try catch around the require in red/api/auth/users.js with require bcryptjs in the catch.

Only downside is yet another 500kB of stuff to install...

**Comment by Hardware-Hacks** [comment]
Dave,

I've seen a few comments on other forums/issues around the bcrypt / bcryptjs issues. I think there is some work being done to try and create a "single package for all" instead of needing the try catch. I can't find the link from my phone but theres a few packages floating around such as https://www.npmjs.com/package/bcrypt-nodejs

Might be worth just having a check to see if anything has been produced since early last year when I first looked in to this (due to the ghost login issues on pi) that may result in an easier fix. I'll post some links when home

**Comment by dceejay** [comment]
Added bcrypt as an optional dependency with a try catch where we require it in user.js. So this should compile and be faster on Pi and other Linux, but drop back to the JS version for windows users so they don't need to install complete compile toolset.

**Comment by vielmetti** [comment]
Thank you for doing this! I didn't measure it precisely, but it looks like the login process on the Pi is about 10x as fast, fast enough not to be a noticeable delay.
