### ISSUE TITLE
Websocket node: add support for "reconnecting" to external WS

### ISSUE THREAD

**Issue by Jbossalini** [node-red/node-red#643]
When a Websocket node is configured to "Connect to" an outside Websocket server, it will lose connection when the other server closes or goes offline and will throw an `[websocket-client:e500d964.de83b] ws:undefined : Error: not opened` error until you restart/redeploy the flow.  

Please implement a "reconnect" option/timeout so that the node will automatically retry the connection after being closed.  Perhaps something like https://github.com/joewalnes/reconnecting-websocket or https://groups.google.com/forum/#!topic/node-red/i9Wx56JonG0

Thanks!

**Comment by Jbossalini** [comment]
Works great.  Thanks!

**Comment by beccsjb** [comment]
I cant see this as being fixed? Is there a certain way to apply this?

**Comment by hardillb** [comment]
The fix for this issue was checked in back in 2015, so it is in any even remotely recent build. There is nothing you need to do. If you thing you are seeing a similar problem then discuss it either in Slack or on the Discourse forum with details of how you are hitting the problem and if it turns out to be regression then you can open a new issue.
