### ISSUE TITLE
payload not being rendered properly in the debug panel

### ISSUE THREAD

**Issue by CmdLnInt** [node-red/node-red#690]
I am trying to use the node module bignum in a function. In testing all I get in the debug panel is
```[msg.payload] : object```
``` {}```

Please see this flow for an example

```[{"id":"4559ab0b.848204","type":"function","name":"","func":"var bignum = context.global.bignum;\n\nvar b = bignum('782910138827292261791972728324982')\n    .sub('182373273283402171237474774728373')\n    .div(8);\n\nmsg.payload = b;\n\nconsole.log(\"%j\", msg.payload);\nconsole.log(\"%j\", b);\nconsole.log(b);\nconsole.log(\"%j\", msg);\n\nreturn msg;","outputs":1,"noerr":0,"x":413,"y":186,"z":"6dffe97f.085fd8","wires":[["152e806f.249de8"]]},{"id":"28153711.bd78f","type":"inject","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":203,"y":140,"z":"6dffe97f.085fd8","wires":[["4559ab0b.848204"]]},{"id":"62001fd9.03c0c8","type":"debug","name":"","active":true,"console":"false","complete":"false","x":712,"y":191,"z":"6dffe97f.085fd8","wires":[]},{"id":"152e806f.249de8","type":"function","name":"","func":"console.log(\"2\");\nconsole.log(msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":543,"y":256,"z":"6dffe97f.085fd8","wires":[["62001fd9.03c0c8"]]}]```

**Comment by hardillb** [comment]
It looks like I just missed you when I updated the Stackoverflow answer (http://stackoverflow.com/questions/31133144/using-node-module-bignum-in-a-node-red-flow)

This is because bignum doesn't implement toString so Node-RED doesn't know how to render it. The best way to get this fixed would be to actually raise the bug with bignum to add a toString method.

**Comment by knolleary** [comment]
Hi,

We encode anything that reports its type as `object` to JSON to represent it in the debug panel. Whilst that makes sense for 'normal' objects, in the case of a custom object like bignum, it doesn't make sense.

A bignum object does have a custom toString function that we should be using. So I think we need to check for a custom toString function and use that if it exists, before resorting to JSON.stringify.

Something like:

    if (msg.payload.toString !== Object.prototype.toString) {
        // use the object's own toString function
    } else {
        // use JSON.stringify
    }

**Comment by philippe-gregoire** [comment]
Actually, what would be even nicer (and more useful), would be a active widget in the debug log with the ability to inspect objects.
this could be an option on the debug node, i.e. have a check for `inspect` rather than `dump` objects.
Also, it would be nice if the debug node could be configured with a max length. Some payloads are long and get truncated before getting to the good part.
Also, a optional `Beautify` checkbox on debug nodes could prove useful too, IMHO...

**Comment by knolleary** [comment]
@philippe-gregoire thanks for the comments. This issue is for a specific scenario on the debug tab. We have issue #545 to cover a broader set of improvements for the debug node/tab.

**Comment by dceejay** [comment]
Philippe,
there is also the global setting in settings.js that may be useful
    // The maximum length, in characters, of any message sent to the debug sidebar tab
    debugMaxLength: 1000,

**Comment by philippe-gregoire** [comment]
Ok, thanks for the tip.
Would be nice to have some way to change the settings right from the NR UI, though, especially in a bmix setup.
Thanks!
