### ISSUE TITLE
`No response object` when HTTP responding after a TCP request

### ISSUE THREAD

**Issue by marvinroger** [node-red/node-red#714]
I just created `HTTP Request` -> `TCP Request` -> `HTTP Response`, and this flow fails with a `No response object` debug message. Removing the `TCP Request` solves the problem.

Flow:

```json
[{"id":"e22fc07d.2bcd4","type":"http in","name":"GET /test","url":"/test","method":"get","swaggerDoc":"","x":647.1428833007812,"y":461.4285888671875,"z":"14ce5b27.eb31a5","wires":[["2946263d.dc77e2"]]},{"id":"3ce9b556.a97bc2","type":"http response","name":"HTTP Response","x":1174.8571472167969,"y":459.5713891983032,"z":"14ce5b27.eb31a5","wires":[]},{"id":"2838d5ca.11276a","type":"change","name":"Set payload","rules":[{"t":"set","p":"payload","to":"test"}],"x":989.1427764892578,"y":459.99995613098145,"z":"14ce5b27.eb31a5","wires":[["3ce9b556.a97bc2"]]},{"id":"2946263d.dc77e2","type":"tcp request","server":"192.168.0.3","port":"5003","out":"sit","splitc":"0","name":"Send to gateway","x":807.142936706543,"y":460.00004386901855,"z":"14ce5b27.eb31a5","wires":[["2838d5ca.11276a"]]}]
```

Thanks!

**Comment by knolleary** [comment]
Hi,

you have the TCP Request node set to block until data arrives. That means the messages emitted by the TCP node are done as and when any data arrives - and the messages are unrelated to the message that triggered the request node. This means the original http request has been lost, so cannot be responded to.

What behaviour do you want? Are you expected a response from the TCP request, or are you just writing data to the destination with no response expected? If the latter, pick one of the other 'return' options as suitable.

**Comment by marvinroger** [comment]
Oh, I see.
I want to write data to the TCP stream, and I don't expect a response. I thought `never - keep connection open` was only about TCP disconnection, and that it would continue to the next nodes. My bad!
Anyway, the other return options don't seem to be suitable... The info says:

```
It can either count a number of returned characters into a fixed buffer, match a specified character before returning, wait a fixed timeout from first reply and then return, or just sit and wait for data.
```
From what I understand, the four options still expect a response.
However, I am not sure about the `wait a fixed timeout from first reply and then return`, and that might be because of my limited skills in english. Does it mean:
* Wait for a reply and then wait the fixed timeout before returning?
* Or wait for a reply during the fixed timeout, and if the timeout expires then return? This way, I would set it to 0ms and it would only send the data without waiting for a response? If so, it might be judicious to add a 5th option "Immediately", it is less ambiguous than putting a timeout of 0.

**Comment by dceejay** [comment]
Hi,

try just using the tcp out node rather than the tcp request one...

eg

[{"id":"4b6d0d23.b492f4","type":"http in","name":"GET /test","url":"/test","method":"get","swaggerDoc":"","x":206,"y":582,"z":"ef78dde5.10872","wires":[["6172131b.9e8dec","e66bc2fd.19944"]]},{"id":"6aef37e2.9510c8","type":"http response","name":"HTTP Response","x":706.7142333984375,"y":579.142822265625,"z":"ef78dde5.10872","wires":[]},{"id":"6172131b.9e8dec","type":"change","name":"Set payload","rules":[{"t":"set","p":"payload","to":"test"}],"x":473.9999084472656,"y":579.5713500976562,"z":"ef78dde5.10872","wires":[["6aef37e2.9510c8"]]},{"id":"e66bc2fd.19944","type":"tcp out","host":"192.168.0.3","port":"5003","beserver":"client","base64":false,"end":false,"name":"","x":504,"y":533,"z":"ef78dde5.10872","wires":[]}]

**Comment by marvinroger** [comment]
I did at first but I thought it would end the flow. To be honest, I didn't know that it was possible to connect a point to multiple points! I feel a little dumb right now.

Thanks for your help.

**Comment by sundarns** [comment]
What if there is a scenario where I need to wait for the response from the TCP node or say a database node then how does one handle such a scenario? I have a "Crate" DB node to fetch data from a database and then I want to return the results of the same in the HTTP Response node. My flow is as below. In such a scenario I am getting "No response object".

Http in --> Crate DB Node -- > Function Node --> Http response

**Comment by hardillb** [comment]
That should be fine as the DB node will pass through the required msg properties. What may be a problem is your function node. You need to make sure you are passing on the incoming message not creating a new one.

Questions like this are better asked on the mailing list (https://groups.google.com/forum/#!forum/node-red)

**Comment by dceejay** [comment]
well - as long as the "Crate"DB node does actually pass on the existing res object - then yes.

**Comment by hardillb** [comment]
OK, @dceejay is right, the Crate node needs to be fixed to pass on the orginal message not create a new one. 

@sundarns I suggest you raise an issue against the node on it's repo (https://github.com/okeeffe/node-red-contrib-crate). The problem is around line 74-75 of [node-red-contrib-crate.js](https://github.com/okeeffe/node-red-contrib-crate/blob/master/crate/node-red-contrib-crate.js)
