### ISSUE TITLE
Export to existing file fails silently

### ISSUE THREAD

**Issue by rdarden** [node-red/node-red#716]
If I select some nodes in the node-red web-based GUI and select the menu item "Export > Library" and specify the name of a file that already exists in the destination, the export will not happen and I can find no mention of an error in either the output or error logs.

For example file ~/.node-red/lib/flows/locations exists, and I specify "locations" as the export filename. The old file will be unchanged but I see no errors in the GUI or logs. If I specify "locations2" as the export filename then a new file ~/.node-red/lib/flows/locations2 is created.

**Comment by knolleary** [comment]
Odd, I cannot reproduce this; exporting to an existing file replaces the existing contents for me.

What OS, node.js version and node-red version are you using? When you export to a new file, what file permissions does that files get? Are you running as a regular user, or as root (via sudo or otherwise)?

**Comment by rdarden** [comment]
I can't reproduce this any more either, I'll close this.
