### ISSUE TITLE
http input node w/ no options

### ISSUE THREAD

**Issue by citizenrich** [node-red/node-red#717]
Don't know if I'm using the app correctly, but installed from npm. When I add an http input node there are no options, which assumes I'm supposed to create all info as url-encoded. Is the correct? User error likely cause...

**Comment by knolleary** [comment]
Hi,

when you say 'no options', you should at least see the following:

![node-red](https://cloud.githubusercontent.com/assets/51083/9442226/ae73756a-4a72-11e5-9172-e0ddb2767812.png)

where you pick the http method it listen for, and the url it listens on. You don't configure anything about what the actual content of the request is. The sidebar help explains how to access the data passed in the request.

For general questions, rather than actual bugs, please use the community mailing list: https://groups.google.com/forum/#!forum/node-red

**Comment by citizenrich** [comment]
Okay, no worries. Thanks!

—
india: +91 8130 670884
skype: richardlstanley, twitter.com/rstanleyio

On Aug 24, 2015, at 7:45 PM, knolleary <notifications@github.com> wrote:

Hi,

when you say 'no options', you should at least see the following:



where you pick the http method it listen for, and the url it listens on. You don't configure anything about what the actual content of the request is. The sidebar help explains how to access the data passed in the request.

For general questions, rather than actual bugs, please use the community mailing list: https://groups.google.com/forum/#!forum/node-red
