### ISSUE TITLE
an instance of the app crashed: app instance exited      exit status: 1, CRASHED

### ISSUE THREAD

**Issue by mjrobinson** [node-red/node-red#785]
I am relatively new to Node-red but have an application which uses Cloudant, DashDB and Node-red and I get the error message above about every hour (along with another out of memory message occasionally) appearing on the dashboard under Activity Log.  I have tried looking at the logs (for the application) but they don't seem to be very helpful.  Please can somebody advise where I should be looking to get more explanation as to why the errors are occurring

**Comment by knolleary** [comment]
Hi,

so I assume you are running in Bluemix rather than locally?

To provide any help we'd need to see the actual error messages you are seeing.

As this issue list is for tracking bugs with node-red rather than general support, please follow up on the mailing list - https://groups.google.com/forum/#!forum/node-red

Thanks,
Nick
