### ISSUE TITLE
this._ is not a function

### ISSUE THREAD

**Issue by Links2004** [node-red/node-red#810]
version: 0.13.3

i update my node-red installation from 0.10.6 to 0.13.3 but now when i access it with the browser i get:
```
Uncaught TypeError: this._ is not a function
```
![image](https://cloud.githubusercontent.com/assets/974709/13373508/eaa4ab82-dd69-11e5-916c-0c884bc4926d.png)

the error happens here:
https://github.com/node-red/node-red/blob/7f6915eb599c74b2bd54c50043fe0389b72a9b14/nodes/core/core/58-debug.html#L138
![image](https://cloud.githubusercontent.com/assets/974709/13373518/1bf5f592-dd6a-11e5-8286-0747152a81f0.png)

is there anything i need to do by updating (except of npm install)?

**Comment by knolleary** [comment]
I see from the screenshot you're running a git clone rather than having installed from npm.

We introduced a build step a while ago that must be run before a git clone of the repo can be run. I suspect youve not run the build so are still using 0.10 levels of the editor code.

We recommend installing via npm rather than clones of the repo. But if you really want to, then you must run `grunt build` to create the editor assets.

**Comment by Links2004** [comment]
yes, work thanks.
the UI looks much cleaner now :+1:
