### ISSUE TITLE
Status documentation misleading 

### ISSUE THREAD

**Issue by andig** [node-red/node-red#826]
http://nodered.org/docs/creating-nodes/status says status is shown via `this.status()`. However, it seems to be `node.status()` that is required?

**Comment by knolleary** [comment]
Yes and no. I can see why you think that, so I agree the documentation should be clearer.

In a Function node, you would use `node.status()` as documented on the 'Writing Functions' page - http://nodered.org/docs/writing-functions#adding-status

In a node runtime implementation (which is what the docs you link to are for), you would use `this.status()`. Although a common pattern is to have a line like `var node = this;` in there, because often in a callback the value of `this` may now be something different, so it allows you to use `node.status()` in the callback.

**Comment by andig** [comment]
> In a node runtime implementation

I see. I was actually using this inside a function but was stuck in the creating nodes chapter. Thank you!

**Comment by pearson** [comment]
Sorry to dig up an old ticket, but The Google brought me to this ticket and to the `node.status(...)` solution to my problem.

I have to admit, as a new user of Node-RED and JavaScript, I was caught by this. I saw the `this.status(...)` function and thought "oh, cool", but got the error. 

This is Node-RED 0.18.4, just in case anyone is curious. :-)

**Comment by niemyjski** [comment]
This is confusing. I just read the docs and it doesn't mention anything about `node.status` only `this.status`.

**Comment by dceejay** [comment]
maybe the writing function docs ? https://nodered.org/docs/writing-functions#adding-status

**Comment by knolleary** [comment]
@dceejay I thought the same, but that doc links to the Node Status page as a reference, and *that* page uses `this.status` as it's in the context of writing nodes. I can see how that switch would be confusing to someone not familiar with the difference.
