### ISSUE TITLE
ESC to cancel node edit is dangerous

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#84]
If you type a load of code into a function node, then accidentally hit ESC, it's all lost.
Maybe ESC (and cancel button, for consistency) should prompt "lose changes?" If there has been a change to the content of the node.
ESC to close an unmodified node that you've just looked at, is perfectly fine.

**Comment by 99TonyStark99** [comment]
Please revert this.  The ESC key should activate the cancel button, **just like in every other app/web page ever made**.  It is very frustrating to open a node to look at it, and then hit ESC to close it, only to have it remain open.  This happens at least 50 times per day for me!  40 year old programming habits are nearly impossible to break.

If reversion is not possible, perhaps you could point me to the appropriate section of code so I can "fix" it myself.

**Comment by 99TonyStark99** [comment]
Thanks for the quick response!

I see that the default is ctrl-escape, and it works! However, I cannot
press ESC to choose the key, (since it cancels the settings window!) and
have to edit the keybind manually.
After changing the key to escape, it no longer works for either ESC or
CTRL-ESC.
I tried rebooting the server, and refreshing the browser page, to no avail.

Should I file a new bug report for this?

**Comment by knolleary** [comment]
>  However, I cannot
press ESC to choose the key, (since it cancels the settings window!) and
have to edit the keybind manually.

The UI doesn't support capturing keystrokes to record the shortcut - you have to manually edit its description.

That said, `escape` is a bit of a funny one because it can be captured by other elements out of our control. A quick test locally shows I can reproduce that.

Please do raise a new issue.
