### ISSUE TITLE
Crashing of Node-Red with high volume of input

### ISSUE THREAD

**Issue by benrondeau** [node-red/node-red#855]
I see that this has already been raised in different prior issues, but Node Red seems to have a serious issues handling input of any decent volume. Sometimes sending ~100 input messages per second would be enough to crash the Node Red instance (just lightweight MQTT messages of maybe 1kb, not massive files). This should not be crashing the server, or even close.

Unfortunately I don't have logs from my own crashes, but this is an example:

https://stackoverflow.com/questions/36362726/node-red-app-in-bluemix-crashes-when-performance-testing

Has this been addressed and how can this be solved? I assume this is a memory overload issue and needs to be addressed in how it is being managed.

Thanks

**Comment by knolleary** [comment]
Node-RED does have its limits, and 100s of messages a second will be nearing them - but it will depend a lot on what you're actually doing.

Can you provide more details of you flow? Without precise details of what you're flow is doing its impossible to say what's happening here.

Are you running in Bluemix? If so, how much memory have you allocated your application?

**Comment by benrondeau** [comment]
What are Node Red's limits? Are they documented?

My app: http://bb8mindcontrol1.mybluemix.net/red/

Memory I believe is 256mb.

The only way I could get it to stop crashing was limiting message input to a maximum of 10/sec, which is pathetic.

Thanks

**Comment by hardillb** [comment]
It sounds like you can reproduce the failure relatively easily by turning the message rate up above 10msg/s. If so getting hold of some logs should be pretty simple.

From the command line run the following:

    cf logs [app name] > log.txt

Where [app name] is probably `bb8mindcontrol1`

This will tail the logs to a file, from there we should be able see why the app is falling over

**Comment by benrondeau** [comment]
Unfortunately I don't have access to the log files. The app is not in my space.

This question was meant generally though, not to my specific situation. It keeps coming up in conversations with users and places like stack overflow.

**Comment by dceejay** [comment]
The default startup for Node-RED on Bluemix is defined in the manifest.yml file - typically 
   node --max-old-space-size=384 ....
This sets the amount of memory to use before calling the Garbage Collector - in this case 384MB. Note this is not a "hard" number - as you can go over this before the GC notices - and you need to allow for the actual OS to have space as well.
If you are really running with 256MB machine then I'm amazed it's not blown it's memory completely... If not (default tends to be 512MB machine) then with a lot of traffic as per your examples there will potentially be a lot of in memory objects - they will remain active until the end to end pipe is finished - and then they hang around until garbage collected.
The other thing to bear in mind is that the function node uses the node.js sandbox - which does have a penalty - even though we re-use them for multiple calls. 1-2mS is not untypical. So if possible use native nodes rather than the function node if performance is what you need.

**Comment by knolleary** [comment]
As @dceejay says, if you're running with 256Mb, you'll need to change the max-old-space-size value in the start command to a value less than 256. Node.js does not start garbage collecting until this value is hit, so you'll be prone to running out of memory eventually.

**Comment by knolleary** [comment]
@benrondeau any more insight on this? You say it keeps coming up on places like Stack Overflow, but it doesn't really - we monitor the node-red tag on there quite closely. The SO question you link to is sounding more like an issue with the MQLight library than node-red. 

The couple times something similar has come up has been down to the memory limits of the app vs what has been passed in over `max-old-space-size`.
