### ISSUE TITLE
Runtime API available in 0.13 ?

### ISSUE THREAD

**Issue by stomita** [node-red/node-red#859]
The document says there are several API methods in `RED.nodes` object.

http://nodered.org/docs/api/runtime/api

But in 0.13 it seems some of these methods (e.g. `RED.nodes.getNodeList()`) are not available and not accessible from custom applications. Are they still opened or has been deprecated ?

**Comment by knolleary** [comment]
Hi,

This api is what is provided by the object returned by `require('node-red')` when you are embedding node-red into your own node.js application.

I am guessing you are using the `RED` object we pass nodes when they are loaded. That has a subset of the full runtime api - something we really need to get documented.

For this sort of question, rather than an issue, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red).

Thanks, Nick
