### ISSUE TITLE
Escaped quotes in MQTT payloads

### ISSUE THREAD

**Issue by patricktokeeffe** [node-red/node-red#869]
Does the MQTT receiving node do quote escaping on payload data? I'm using the [iot-datasource node](https://github.com/IBM-IoT/node-red-contrib-graphs) to plot data but their examples fail once I send the message through a (localhost) Mosquitto instance. You can see the contents of `msg.payload` get double-quote-escaped, which then causes the graph to not recognize the data source.

*Example:*
```
{ "topic": "", "payload": { "tstamp": 1460608903283, "data": { "x": 423, "y": 9.461915759697556 } }, "_msgid": "bc28666.f43d798" }
```

*Example+MQTT:*
```
{ "topic": "nodered/test1", "payload": "{\"tstamp\":1460608922515,\"data\":{\"x\":416,\"y\":10.109945317592471}}", "qos": 0, "retain": false, "_topic": "nodered/test1", "_msgid": "9cc9eb2a.633618" }
```

It doesn't appear to be something added by Mosquitto -- I monitored using `mosquitto_sub`:

```
{"tstamp":1460608903283,"data":{"x":423,"y":9.461915759697556}}
{"tstamp":1460608922515,"data":{"x":416,"y":10.109945317592471}}
```

Is this normal? If so, is there a straight-forward way to undo it?

Using nodered 0.13.3, node 0.10.29, mosquitto 1.3.4-2, RPi 3

**Comment by knolleary** [comment]
Hi @patricktokeeffe 

If `msg.payload` is a string that contains double quotes, then when you view the complete message object it has to escape those quotes in order to present a valid object representation of the message. That is a presentational thing. If you look at msg.payload directly, you'd see it doesn't actually contain those quotes.

If you were to pass that message through a JSON node, it will replace `msg.payload` with a parsed version of that JSON string so you can start reference the values within it directly - ie `msg.payload.data.x`.

**Comment by patricktokeeffe** [comment]
I just came back to close this. Wish I'd seen your reply first sorry. Yes, I wound up using `JSON.parse()` on the payload. Thank you
