### ISSUE TITLE
Conditional node validation

### ISSUE THREAD

**Issue by rafaelamorim** [node-red/node-red#909]
Hello guys,
first i'd like to thank to you guys for this amazing tool, you guys rock!

I'm developing a set of nodes and came across 3 validation cases for it, and i can't figure out an easy way to do it:

Case 1:
An _output-only_ node that **can only be used once per _flow_**. So, if someone used one in a _flow_ it should be hidden in the pallet, or give a validation warning if a second is present in the same _flow_.

Case 2:
An _node_ that is **only available for flows**, and **not available for sub-flows**. And the same thing reverse, **only available for sub-flows**, and **not available for flows**.

Case 3:
A _node_ that is **only valid if its wired to it's _dependent node_**, no need to be directly wired, but it has to be connected somehow.

I was able to do these but in a very messy way, not cool at all :(
Can you guys help me figure these out?

Best,
Rafa

**Comment by knolleary** [comment]
Hi,

to be frank, there is no easy way to do any of these.

There are a number of other possible constraints a node may want to enforce - such as how many wires can be connected to any port etc. I think it's an area that needs to be thought about as a whole rather than start adding random individual pieces.

I think for all three cases we'd want to understand the scenario a bit more fully. Certainly Case 3 would be beneficial to the HTTP In/HTTP Response nodes.

FYI, for future, as per our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md), we prefer to use the mailing list for this sort of feature request/discussion in the first instance - and keep the issue list to actual issues.

**Comment by rafaelamorim** [comment]
Nick,
my bad, i'll move this to the mailing list.

Thanks anyway! :)
