### ISSUE TITLE
0.15.0/bidi: contenteditable divs not sizing properly and overflow content

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#989]
@wajnberg - please take a look at this

Despite issue #988, if you double click on an HTTP Request node enough times it eventually opens.

When it does so, it looks like this:

<img width="622" alt="node-red" src="https://cloud.githubusercontent.com/assets/51083/18453519/98914ff2-7937-11e6-8589-8df0f431f828.png">

 - the content-editable div doesn't have the same width as the regular inputs. By default <inputs> have a width of 70% - this should also apply to these divs
 - the content of the div wraps and overflows unexpectedly.

**Comment by wajnberg** [comment]
Hello @knolleary ,

I tried to reproduce the problem on 3 different browsers: FF, IE and Safari but with no success (apart from the overflow problem that I will handle later on)

Do you try to edit an existing node that was created with the old <input> element (instead of the new <div contenteditable>

Or you can't create a new http request node ?

Do you have the same problem with watch node ? 

Can you please elaborate ?

Thank you

**Comment by knolleary** [comment]
Closed by #993
